### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement
  id: TokenReplayDetectionElement
  children:
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  langs:
  - csharp
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class TokenReplayDetectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TokenReplayDetectionElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  id: Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  id: ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TimeSpan ExpirationPeriod { get; set; }
    return:
      type: System.TimeSpan
      description: To be added.
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.TokenReplayDetectionElement()
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
