### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  id: DownloadFileGroupCompletedEventHandler
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventHandler
  nameWithType: DownloadFileGroupCompletedEventHandler
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public delegate void DownloadFileGroupCompletedEventHandler(object sender, DownloadFileGroupCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
