### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: To be added.
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: To be added.
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: To be added.
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
