### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFramework
  id: CompatibleFramework
  children:
  - System.Deployment.Application.CompatibleFramework.Profile
  - System.Deployment.Application.CompatibleFramework.SupportedRuntime
  - System.Deployment.Application.CompatibleFramework.TargetVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: System.Deployment.Application.CompatibleFramework
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFramework.Profile
  id: Profile
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Profile { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.CompatibleFramework.Profile*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string SupportedRuntime { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  id: TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string TargetVersion { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.CompatibleFramework.TargetVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFramework.Profile
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.Profile*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
