### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentServiceCom
  id: DeploymentServiceCom
  children:
  - System.Deployment.Application.DeploymentServiceCom.#ctor
  - System.Deployment.Application.DeploymentServiceCom.ActivateApplicationExtension(System.String,System.String,System.String)
  - System.Deployment.Application.DeploymentServiceCom.ActivateDeployment(System.String,System.Boolean)
  - System.Deployment.Application.DeploymentServiceCom.ActivateDeploymentEx(System.String,System.Int32,System.Int32)
  - System.Deployment.Application.DeploymentServiceCom.CheckForDeploymentUpdate(System.String)
  - System.Deployment.Application.DeploymentServiceCom.CleanOnlineAppCache
  - System.Deployment.Application.DeploymentServiceCom.EndServiceRightNow
  - System.Deployment.Application.DeploymentServiceCom.MaintainSubscription(System.String)
  langs:
  - csharp
  name: DeploymentServiceCom
  nameWithType: DeploymentServiceCom
  fullName: System.Deployment.Application.DeploymentServiceCom
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.AutoDispatch)]

      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("20FD4E26-8E0F-4F73-A0E0-F27B8C57BE6F")]

      public class DeploymentServiceCom
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: DeploymentServiceCom()
  nameWithType: DeploymentServiceCom.DeploymentServiceCom()
  fullName: System.Deployment.Application.DeploymentServiceCom.DeploymentServiceCom()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DeploymentServiceCom ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateApplicationExtension(System.String,System.String,System.String)
  id: ActivateApplicationExtension(System.String,System.String,System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: ActivateApplicationExtension(String,String,String)
  nameWithType: DeploymentServiceCom.ActivateApplicationExtension(String,String,String)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateApplicationExtension(String,String,String)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ActivateApplicationExtension (string textualSubId, string deploymentProviderUrl, string targetAssociatedFile);
    parameters:
    - id: textualSubId
      type: System.String
      description: To be added.
    - id: deploymentProviderUrl
      type: System.String
      description: To be added.
    - id: targetAssociatedFile
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateDeployment(System.String,System.Boolean)
  id: ActivateDeployment(System.String,System.Boolean)
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: ActivateDeployment(String,Boolean)
  nameWithType: DeploymentServiceCom.ActivateDeployment(String,Boolean)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateDeployment(String,Boolean)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ActivateDeployment (string deploymentLocation, bool isShortcut);
    parameters:
    - id: deploymentLocation
      type: System.String
      description: To be added.
    - id: isShortcut
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateDeploymentEx(System.String,System.Int32,System.Int32)
  id: ActivateDeploymentEx(System.String,System.Int32,System.Int32)
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: ActivateDeploymentEx(String,Int32,Int32)
  nameWithType: DeploymentServiceCom.ActivateDeploymentEx(String,Int32,Int32)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateDeploymentEx(String,Int32,Int32)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ActivateDeploymentEx (string deploymentLocation, int unsignedPolicy, int signedPolicy);
    parameters:
    - id: deploymentLocation
      type: System.String
      description: To be added.
    - id: unsignedPolicy
      type: System.Int32
      description: To be added.
    - id: signedPolicy
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.CheckForDeploymentUpdate(System.String)
  id: CheckForDeploymentUpdate(System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: CheckForDeploymentUpdate(String)
  nameWithType: DeploymentServiceCom.CheckForDeploymentUpdate(String)
  fullName: System.Deployment.Application.DeploymentServiceCom.CheckForDeploymentUpdate(String)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void CheckForDeploymentUpdate (string textualSubId);
    parameters:
    - id: textualSubId
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.CleanOnlineAppCache
  id: CleanOnlineAppCache
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: CleanOnlineAppCache()
  nameWithType: DeploymentServiceCom.CleanOnlineAppCache()
  fullName: System.Deployment.Application.DeploymentServiceCom.CleanOnlineAppCache()
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void CleanOnlineAppCache ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.EndServiceRightNow
  id: EndServiceRightNow
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: EndServiceRightNow()
  nameWithType: DeploymentServiceCom.EndServiceRightNow()
  fullName: System.Deployment.Application.DeploymentServiceCom.EndServiceRightNow()
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void EndServiceRightNow ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentServiceCom.MaintainSubscription(System.String)
  id: MaintainSubscription(System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  langs:
  - csharp
  name: MaintainSubscription(String)
  nameWithType: DeploymentServiceCom.MaintainSubscription(String)
  fullName: System.Deployment.Application.DeploymentServiceCom.MaintainSubscription(String)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void MaintainSubscription (string textualSubId);
    parameters:
    - id: textualSubId
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.DeploymentServiceCom.#ctor
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: DeploymentServiceCom()
  nameWithType: DeploymentServiceCom.DeploymentServiceCom()
  fullName: System.Deployment.Application.DeploymentServiceCom.DeploymentServiceCom()
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateApplicationExtension(System.String,System.String,System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: ActivateApplicationExtension(String,String,String)
  nameWithType: DeploymentServiceCom.ActivateApplicationExtension(String,String,String)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateApplicationExtension(String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateDeployment(System.String,System.Boolean)
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: ActivateDeployment(String,Boolean)
  nameWithType: DeploymentServiceCom.ActivateDeployment(String,Boolean)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateDeployment(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.DeploymentServiceCom.ActivateDeploymentEx(System.String,System.Int32,System.Int32)
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: ActivateDeploymentEx(String,Int32,Int32)
  nameWithType: DeploymentServiceCom.ActivateDeploymentEx(String,Int32,Int32)
  fullName: System.Deployment.Application.DeploymentServiceCom.ActivateDeploymentEx(String,Int32,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Deployment.Application.DeploymentServiceCom.CheckForDeploymentUpdate(System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: CheckForDeploymentUpdate(String)
  nameWithType: DeploymentServiceCom.CheckForDeploymentUpdate(String)
  fullName: System.Deployment.Application.DeploymentServiceCom.CheckForDeploymentUpdate(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentServiceCom.CleanOnlineAppCache
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: CleanOnlineAppCache()
  nameWithType: DeploymentServiceCom.CleanOnlineAppCache()
  fullName: System.Deployment.Application.DeploymentServiceCom.CleanOnlineAppCache()
- uid: System.Deployment.Application.DeploymentServiceCom.EndServiceRightNow
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: EndServiceRightNow()
  nameWithType: DeploymentServiceCom.EndServiceRightNow()
  fullName: System.Deployment.Application.DeploymentServiceCom.EndServiceRightNow()
- uid: System.Deployment.Application.DeploymentServiceCom.MaintainSubscription(System.String)
  parent: System.Deployment.Application.DeploymentServiceCom
  isExternal: false
  name: MaintainSubscription(String)
  nameWithType: DeploymentServiceCom.MaintainSubscription(String)
  fullName: System.Deployment.Application.DeploymentServiceCom.MaintainSubscription(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
