### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
