### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs
  id: DownloadProgressChangedEventArgs
  children:
  - System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  - System.Deployment.Application.DownloadProgressChangedEventArgs.State
  - System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  langs:
  - csharp
  name: DownloadProgressChangedEventArgs
  nameWithType: DownloadProgressChangedEventArgs
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DownloadProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  id: BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public long BytesDownloaded { get; }
    return:
      type: System.Int64
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  id: TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public long TotalBytesToDownload { get; }
    return:
      type: System.Int64
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
