### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworks
  id: CompatibleFrameworks
  children:
  - System.Deployment.Application.CompatibleFrameworks.Frameworks
  - System.Deployment.Application.CompatibleFrameworks.SupportUrl
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class CompatibleFrameworks
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  id: Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework> Frameworks { get; }
    return:
      type: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
- uid: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<CompatibleFramework>
  nameWithType: IList<CompatibleFramework>
  fullName: System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework>
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
