### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
