### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DependentPlatformMissingException
  id: DependentPlatformMissingException
  children:
  - System.Deployment.Application.DependentPlatformMissingException.#ctor
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  - System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  langs:
  - csharp
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException
  fullName: System.Deployment.Application.DependentPlatformMissingException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DependentPlatformMissingException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DependentPlatformMissingException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DependentPlatformMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected DependentPlatformMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DependentPlatformMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  id: '#ctor(System.String,System.Uri)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DependentPlatformMissingException (string message, Uri supportUrl);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: supportUrl
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
