### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  id: CheckForUpdateCompletedEventArgs
  children:
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  langs:
  - csharp
  name: CheckForUpdateCompletedEventArgs
  nameWithType: CheckForUpdateCompletedEventArgs
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class CheckForUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: To be added.
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: To be added.
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: To be added.
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
