### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.SupportedRuntimeMissingException
  id: SupportedRuntimeMissingException
  children:
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  langs:
  - csharp
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException
  fullName: System.Deployment.Application.SupportedRuntimeMissingException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class SupportedRuntimeMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SupportedRuntimeMissingException ();
    parameters: []
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SupportedRuntimeMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected SupportedRuntimeMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SupportedRuntimeMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  overload: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  id: SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string SupportedRuntimeVersion { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: SupportedRuntimeMissingException.GetObjectData
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
