### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  id: DownloadFileGroupCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventArgs
  nameWithType: DownloadFileGroupCompletedEventArgs
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DownloadFileGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  isExternal: false
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
