### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworkMissingException
  id: CompatibleFrameworkMissingException
  children:
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  - System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class CompatibleFrameworkMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CompatibleFrameworkMissingException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CompatibleFrameworkMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected CompatibleFrameworkMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CompatibleFrameworkMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  id: CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Deployment.Application.CompatibleFrameworks CompatibleFrameworks { get; }
    return:
      type: System.Deployment.Application.CompatibleFrameworks
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworks
  parent: System.Deployment.Application
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
