### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentException
  id: DeploymentException
  children:
  - System.Deployment.Application.DeploymentException.#ctor
  - System.Deployment.Application.DeploymentException.#ctor(System.String)
  - System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: DeploymentException
  nameWithType: DeploymentException
  fullName: System.Deployment.Application.DeploymentException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DeploymentException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DeploymentException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected DeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Deployment.Application.DeploymentException.#ctor
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
