### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: InstallEventHandler
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: Represents the method that will handle the <xref href="System.Configuration.Install.Installer.BeforeInstall"></xref>, <xref href="System.Configuration.Install.Installer.AfterInstall"></xref>, <xref href="System.Configuration.Install.Installer.Committing"></xref>, <xref href="System.Configuration.Install.Installer.Committed"></xref>, <xref href="System.Configuration.Install.Installer.BeforeRollback"></xref>, <xref href="System.Configuration.Install.Installer.AfterRollback"></xref>, <xref href="System.Configuration.Install.Installer.BeforeUninstall"></xref>, or <xref href="System.Configuration.Install.Installer.AfterUninstall"></xref> event of an <xref href="System.Configuration.Install.Installer"></xref>.
  remarks: When you create an InstallEventHandler delegate, you identify the method that will handle the event. To associate the event with your event handler, add an instance of the delegate to the event. The event handler is called whenever the event occurs, unless you remove the delegate. For more information about event handler delegates, see [Events](../Topic/Handling%20and%20Raising%20Events.md).
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
