### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  id: XPathMessageFilterElementComparer
  children:
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  langs:
  - csharp
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  type: Class
  summary: Provides functionality to compare two <xref href="System.ServiceModel.Configuration.XPathMessageFilterElement"></xref> instances.
  syntax:
    content: 'public class XPathMessageFilterElementComparer : System.Collections.IComparer'
  inheritance:
  - System.Object
  implements:
  - System.Collections.IComparer
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.XPathMessageFilterElementComparer"></xref> class.
  syntax:
    content: public XPathMessageFilterElementComparer ();
    parameters: []
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  id: System#Collections#IComparer#Compare(System.Object,System.Object)
  isEii: true
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Compare two <xref href="System.ServiceModel.Configuration.XPathMessageFilterElement"></xref> instances.
  syntax:
    content: int IComparer.Compare (object x, object y);
    parameters:
    - id: x
      type: System.Object
      description: A <xref href="System.ServiceModel.Configuration.XPathMessageFilterElement"></xref>.
    - id: y
      type: System.Object
      description: A <xref href="System.ServiceModel.Configuration.XPathMessageFilterElement"></xref>.
    return:
      type: System.Int32
      description: To be added.
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: The XPath filter specified by <code>x</code> or <code>y</code> cannot be parsed.
  - type: System.IndexOutOfRangeException
    commentId: T:System.IndexOutOfRangeException
    description: The XPath namespace prefix specified by <code>x</code> or <code>y</code>.cannot be found.
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare
