### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  id: EnvironmentPermissionAccess
  children:
  - System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.Read
  - System.Security.Permissions.EnvironmentPermissionAccess.Write
  langs:
  - csharp
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Flags]

      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentPermissionAccess
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  id: AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  syntax:
    content: AllAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  id: NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  syntax:
    content: NoAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  syntax:
    content: Read
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: To be added.
  syntax:
    content: Write
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
