### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  id: TypeLib
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion
  langs:
  - csharp
  name: TypeLib
  nameWithType: TypeLib
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public class TypeLib
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: TypeLib()
  nameWithType: TypeLib.TypeLib()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TypeLib()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TypeLib ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags
  id: Flags
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: Flags
  nameWithType: TypeLib.Flags
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Flags { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory
  id: HelpDirectory
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: HelpDirectory
  nameWithType: TypeLib.HelpDirectory
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string HelpDirectory { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId
  id: ResourceId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: ResourceId
  nameWithType: TypeLib.ResourceId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ResourceId { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId
  id: TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: TlbId
  nameWithType: TypeLib.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string TlbId { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version
  id: Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: Version
  nameWithType: TypeLib.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Version { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags
  id: XmlFlags
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: XmlFlags
  nameWithType: TypeLib.XmlFlags
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlFlags { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory
  id: XmlHelpDirectory
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: XmlHelpDirectory
  nameWithType: TypeLib.XmlHelpDirectory
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlHelpDirectory { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId
  id: XmlResourceId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: XmlResourceId
  nameWithType: TypeLib.XmlResourceId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlResourceId { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId
  id: XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: XmlTlbId
  nameWithType: TypeLib.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlTlbId { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion
  id: XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  langs:
  - csharp
  name: XmlVersion
  nameWithType: TypeLib.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlVersion { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: TypeLib()
  nameWithType: TypeLib.TypeLib()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TypeLib()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: Flags
  nameWithType: TypeLib.Flags
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: HelpDirectory
  nameWithType: TypeLib.HelpDirectory
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: ResourceId
  nameWithType: TypeLib.ResourceId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: TlbId
  nameWithType: TypeLib.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: Version
  nameWithType: TypeLib.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlFlags
  nameWithType: TypeLib.XmlFlags
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlHelpDirectory
  nameWithType: TypeLib.XmlHelpDirectory
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlResourceId
  nameWithType: TypeLib.XmlResourceId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlTlbId
  nameWithType: TypeLib.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlVersion
  nameWithType: TypeLib.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: TypeLib
  nameWithType: TypeLib.TypeLib
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Flags*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: Flags
  nameWithType: TypeLib.Flags
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.HelpDirectory*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: HelpDirectory
  nameWithType: TypeLib.HelpDirectory
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.ResourceId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: ResourceId
  nameWithType: TypeLib.ResourceId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.TlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: TlbId
  nameWithType: TypeLib.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.Version*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: Version
  nameWithType: TypeLib.Version
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlFlags*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlFlags
  nameWithType: TypeLib.XmlFlags
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlHelpDirectory*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlHelpDirectory
  nameWithType: TypeLib.XmlHelpDirectory
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlResourceId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlResourceId
  nameWithType: TypeLib.XmlResourceId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlTlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlTlbId
  nameWithType: TypeLib.XmlTlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib.XmlVersion*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  isExternal: false
  name: XmlVersion
  nameWithType: TypeLib.XmlVersion
