### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  id: ProxyStub
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId
  langs:
  - csharp
  name: ProxyStub
  nameWithType: ProxyStub
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public class ProxyStub
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: ProxyStub()
  nameWithType: ProxyStub.ProxyStub()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.ProxyStub()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProxyStub ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface
  id: BaseInterface
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: BaseInterface
  nameWithType: ProxyStub.BaseInterface
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string BaseInterface { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID
  id: IID
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: IID
  nameWithType: ProxyStub.IID
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string IID { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name
  id: Name
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: Name
  nameWithType: ProxyStub.Name
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods
  id: NumMethods
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: NumMethods
  nameWithType: ProxyStub.NumMethods
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string NumMethods { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId
  id: TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: TlbId
  nameWithType: ProxyStub.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string TlbId { get; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface
  id: XmlBaseInterface
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: XmlBaseInterface
  nameWithType: ProxyStub.XmlBaseInterface
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlBaseInterface { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID
  id: XmlIID
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: XmlIID
  nameWithType: ProxyStub.XmlIID
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlIID { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName
  id: XmlName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: XmlName
  nameWithType: ProxyStub.XmlName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlName { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods
  id: XmlNumMethods
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: XmlNumMethods
  nameWithType: ProxyStub.XmlNumMethods
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlNumMethods { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId
  id: XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  langs:
  - csharp
  name: XmlTlbId
  nameWithType: ProxyStub.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlTlbId { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: ProxyStub()
  nameWithType: ProxyStub.ProxyStub()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.ProxyStub()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: BaseInterface
  nameWithType: ProxyStub.BaseInterface
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: IID
  nameWithType: ProxyStub.IID
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: Name
  nameWithType: ProxyStub.Name
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: NumMethods
  nameWithType: ProxyStub.NumMethods
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: TlbId
  nameWithType: ProxyStub.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlBaseInterface
  nameWithType: ProxyStub.XmlBaseInterface
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlIID
  nameWithType: ProxyStub.XmlIID
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlName
  nameWithType: ProxyStub.XmlName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlNumMethods
  nameWithType: ProxyStub.XmlNumMethods
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlTlbId
  nameWithType: ProxyStub.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: ProxyStub
  nameWithType: ProxyStub.ProxyStub
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.BaseInterface*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: BaseInterface
  nameWithType: ProxyStub.BaseInterface
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.IID*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: IID
  nameWithType: ProxyStub.IID
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.Name*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: Name
  nameWithType: ProxyStub.Name
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.NumMethods*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: NumMethods
  nameWithType: ProxyStub.NumMethods
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.TlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: TlbId
  nameWithType: ProxyStub.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlBaseInterface*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlBaseInterface
  nameWithType: ProxyStub.XmlBaseInterface
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlIID*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlIID
  nameWithType: ProxyStub.XmlIID
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlName*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlName
  nameWithType: ProxyStub.XmlName
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlNumMethods*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlNumMethods
  nameWithType: ProxyStub.XmlNumMethods
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub.XmlTlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  isExternal: false
  name: XmlTlbId
  nameWithType: ProxyStub.XmlTlbId
