### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  id: AssemblyReference
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  langs:
  - csharp
  name: AssemblyReference
  nameWithType: AssemblyReference
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class AssemblyReference : Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  inheritance:
  - System.Object
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Group
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Hash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.IsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.ResolvedPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Size
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.SourcePath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.TargetPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlGroup
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHashAlgorithm
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlIsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlSize
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyReference()
  nameWithType: AssemblyReference.AssemblyReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public AssemblyReference ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyReference(String)
  nameWithType: AssemblyReference.AssemblyReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference(String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public AssemblyReference (string path);
    parameters:
    - id: path
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  id: AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyIdentity
  nameWithType: AssemblyReference.AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity AssemblyIdentity { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  id: IsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: IsPrerequisite
  nameWithType: AssemblyReference.IsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsPrerequisite { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  id: ReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: ReferenceType
  nameWithType: AssemblyReference.ReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType ReferenceType { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  id: SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: SortName
  nameWithType: AssemblyReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override string SortName { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  id: ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: ToString()
  nameWithType: AssemblyReference.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  id: XmlAssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlAssemblyIdentity
  nameWithType: AssemblyReference.XmlAssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity XmlAssemblyIdentity { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  id: XmlIsNative
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlIsNative
  nameWithType: AssemblyReference.XmlIsNative
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlIsNative { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  id: XmlIsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlIsPrerequisite
  nameWithType: AssemblyReference.XmlIsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlIsPrerequisite { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  isExternal: false
  name: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyReference()
  nameWithType: AssemblyReference.AssemblyReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyReference(String)
  nameWithType: AssemblyReference.AssemblyReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyReference.AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: IsPrerequisite
  nameWithType: AssemblyReference.IsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ReferenceType
  nameWithType: AssemblyReference.ReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: SortName
  nameWithType: AssemblyReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ToString()
  nameWithType: AssemblyReference.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlAssemblyIdentity
  nameWithType: AssemblyReference.XmlAssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsNative
  nameWithType: AssemblyReference.XmlIsNative
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsPrerequisite
  nameWithType: AssemblyReference.XmlIsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
