### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  id: ManifestReader
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  langs:
  - csharp
  name: ManifestReader
  nameWithType: ManifestReader
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class ManifestReader
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  id: ReadManifest(System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(Stream,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (System.IO.Stream input, bool preserveStream);
    parameters:
    - id: input
      type: System.IO.Stream
      description: To be added.
    - id: preserveStream
      type: System.Boolean
      description: To be added.
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  id: ReadManifest(System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string path, bool preserveStream);
    parameters:
    - id: path
      type: System.String
      description: To be added.
    - id: preserveStream
      type: System.Boolean
      description: To be added.
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  id: ReadManifest(System.String,System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Stream,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string manifestType, System.IO.Stream input, bool preserveStream);
    parameters:
    - id: manifestType
      type: System.String
      description: To be added.
    - id: input
      type: System.IO.Stream
      description: To be added.
    - id: preserveStream
      type: System.Boolean
      description: To be added.
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  id: ReadManifest(System.String,System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,String,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string manifestType, string path, bool preserveStream);
    parameters:
    - id: manifestType
      type: System.String
      description: To be added.
    - id: path
      type: System.String
      description: To be added.
    - id: preserveStream
      type: System.Boolean
      description: To be added.
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: To be added.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(Stream,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Stream,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,String,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest
  nameWithType: ManifestReader.ReadManifest
