### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  id: OutputMessageCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  langs:
  - csharp
  name: OutputMessageCollection
  nameWithType: OutputMessageCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class OutputMessageCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: OutputMessageCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Clear ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  id: ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int ErrorCount { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: OutputMessageCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: OutputMessageCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: To be added.
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  id: WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int WarningCount { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Clear()
  nameWithType: OutputMessageCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: OutputMessageCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: OutputMessageCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessage
  nameWithType: OutputMessage
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
