### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  id: CompatibleFramework
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CompatibleFramework ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  id: Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Profile { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string SupportedRuntime { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  id: Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Version { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  id: XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlProfile { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  id: XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlSupportedRuntime { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  id: XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlVersion { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
