### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  id: FileReference
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ComClasses
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.IsDataFile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ProxyStubs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.SortName
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.TypeLibs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlComClasses
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlProxyStubs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlTypeLibs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlWriteableType
  langs:
  - csharp
  name: FileReference
  nameWithType: FileReference
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class FileReference : Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  inheritance:
  - System.Object
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Group
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Hash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.IsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.ResolvedPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Size
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.SourcePath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.TargetPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.ToString
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlGroup
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHashAlgorithm
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlIsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlSize
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: FileReference()
  nameWithType: FileReference.FileReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.FileReference()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public FileReference ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: FileReference(String)
  nameWithType: FileReference.FileReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.FileReference(String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public FileReference (string path);
    parameters:
    - id: path
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ComClasses
  id: ComClasses
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: ComClasses
  nameWithType: FileReference.ComClasses
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ComClasses
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[] ComClasses { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.IsDataFile
  id: IsDataFile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: IsDataFile
  nameWithType: FileReference.IsDataFile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.IsDataFile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsDataFile { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ProxyStubs
  id: ProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: ProxyStubs
  nameWithType: FileReference.ProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] ProxyStubs { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.SortName
  id: SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: SortName
  nameWithType: FileReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.SortName
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override string SortName { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.TypeLibs
  id: TypeLibs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: TypeLibs
  nameWithType: FileReference.TypeLibs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.TypeLibs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[] TypeLibs { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlComClasses
  id: XmlComClasses
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: XmlComClasses
  nameWithType: FileReference.XmlComClasses
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlComClasses
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[] XmlComClasses { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlProxyStubs
  id: XmlProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: XmlProxyStubs
  nameWithType: FileReference.XmlProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] XmlProxyStubs { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlTypeLibs
  id: XmlTypeLibs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: XmlTypeLibs
  nameWithType: FileReference.XmlTypeLibs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlTypeLibs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[] XmlTypeLibs { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlWriteableType
  id: XmlWriteableType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  langs:
  - csharp
  name: XmlWriteableType
  nameWithType: FileReference.XmlWriteableType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlWriteableType
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string XmlWriteableType { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  isExternal: false
  name: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: FileReference()
  nameWithType: FileReference.FileReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.FileReference()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.#ctor(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: FileReference(String)
  nameWithType: FileReference.FileReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.FileReference(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ComClasses
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: ComClasses
  nameWithType: FileReference.ComClasses
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ComClasses
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ComClass
  nameWithType: ComClass
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.IsDataFile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: IsDataFile
  nameWithType: FileReference.IsDataFile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.IsDataFile
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: ProxyStubs
  nameWithType: FileReference.ProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.ProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ProxyStub
  nameWithType: ProxyStub
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: SortName
  nameWithType: FileReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.SortName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.TypeLibs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: TypeLibs
  nameWithType: FileReference.TypeLibs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.TypeLibs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: TypeLib
  nameWithType: TypeLib
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlComClasses
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: XmlComClasses
  nameWithType: FileReference.XmlComClasses
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlComClasses
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ComClass
  nameWithType: ComClass
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: XmlProxyStubs
  nameWithType: FileReference.XmlProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ProxyStub
  nameWithType: ProxyStub
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlTypeLibs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: XmlTypeLibs
  nameWithType: FileReference.XmlTypeLibs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlTypeLibs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: TypeLib
  nameWithType: TypeLib
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.TypeLib[]
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlWriteableType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  isExternal: false
  name: XmlWriteableType
  nameWithType: FileReference.XmlWriteableType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference.XmlWriteableType
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
