### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSDualHttpSecurity
  id: WSDualHttpSecurity
  children:
  - System.ServiceModel.WSDualHttpSecurity.#ctor
  - System.ServiceModel.WSDualHttpSecurity.Message
  - System.ServiceModel.WSDualHttpSecurity.Mode
  - System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  langs:
  - csharp
  name: WSDualHttpSecurity
  nameWithType: WSDualHttpSecurity
  fullName: System.ServiceModel.WSDualHttpSecurity
  type: Class
  summary: Specifies the security settings for the .
  remarks: This class specifies the security settings for the `wsDualHttpBinding` binding.
  syntax:
    content: public sealed class WSDualHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: WSDualHttpSecurity()
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity()
  fullName: System.ServiceModel.WSDualHttpSecurity.WSDualHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Initializes a new instance of the  class.
  syntax:
    content: public WSDualHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSDualHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.WSDualHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSDualHttpSecurity.Message
  fullName: System.ServiceModel.WSDualHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets the message-level security properties for the .
  remarks: The object returned specifies detailed message-level security properties for the `wsDualHttpBinding` binding.
  example:
  - "The following code shows how to set the <xref:System.ServiceModel.MessageSecurityOverHttp.AlgorithmSuite%2A> property by accessing this property.  \n  \n [!code-cs[S_UEWSDualHttpSecurity#30](~/add/codesnippet/CSharp/p-system.servicemodel.ws_4_1.cs)]\n [!code-vb[S_UEWSDualHttpSecurity#30](~/add/codesnippet/VisualBasic/p-system.servicemodel.ws_4_1.vb)]"
  syntax:
    content: public System.ServiceModel.MessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverHttp
      description: 'A  value. The default values include: <xref:System.ServiceModel.MessageSecurityOverHttp.ClientCredentialType%2A> is <xref:System.ServiceModel.MessageCredentialType>, <xref:System.ServiceModel.MessageSecurityOverHttp.AlgorithmSuite%2A> is <xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256%2A>, and <xref:System.ServiceModel.MessageSecurityOverHttp.NegotiateServiceCredential%2A> is .'
  overload: System.ServiceModel.WSDualHttpSecurity.Message*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.WSDualHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
  fullName: System.ServiceModel.WSDualHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets or sets the security mode for the parent .
  remarks: The value of this property determines whether message-level security is applied to the binding.
  example:
  - "The following code shows how to set this property.  \n  \n [!code-cs[S_UEWSDualHttpSecurity#30](~/add/codesnippet/CSharp/p-system.servicemodel.ws_16_1.cs)]\n [!code-vb[S_UEWSDualHttpSecurity#30](~/add/codesnippet/VisualBasic/p-system.servicemodel.ws_16_1.vb)]"
  syntax:
    content: public System.ServiceModel.WSDualHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSDualHttpSecurityMode
      description: A value from the  enumeration. The default is .
  overload: System.ServiceModel.WSDualHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: The value is not a valid .
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Returns a value that indicates whether the <xref:System.ServiceModel.WSDualHttpSecurity.Message%2A> property has changed from its default value and should be serialized. This is used by WCF for XAML integration.
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: To be added.
  overload: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Returns a value that indicates whether the <xref:System.ServiceModel.WSDualHttpSecurity.Mode%2A> property has changed from its default value and should be serialized. This is used by WCF for XAML integration.
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: To be added.
  overload: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: WSDualHttpSecurity()
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity()
  fullName: System.ServiceModel.WSDualHttpSecurity.WSDualHttpSecurity()
- uid: System.ServiceModel.WSDualHttpSecurity.Message
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurity.Message
  fullName: System.ServiceModel.WSDualHttpSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverHttp
  nameWithType: MessageSecurityOverHttp
  fullName: System.ServiceModel.MessageSecurityOverHttp
- uid: System.ServiceModel.WSDualHttpSecurity.Mode
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
  fullName: System.ServiceModel.WSDualHttpSecurity.Mode
- uid: System.ServiceModel.WSDualHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSDualHttpSecurityMode
  nameWithType: WSDualHttpSecurityMode
  fullName: System.ServiceModel.WSDualHttpSecurityMode
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: WSDualHttpSecurity
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity
- uid: System.ServiceModel.WSDualHttpSecurity.Message*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurity.Message
- uid: System.ServiceModel.WSDualHttpSecurity.Mode*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode
