### YamlMime:ManagedReference
items:
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  id: ApplicationPartitionCollection
  children:
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  langs:
  - csharp
  name: ApplicationPartitionCollection
  nameWithType: ApplicationPartitionCollection
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ApplicationPartitionCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool Contains (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  id: CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void CopyTo (System.DirectoryServices.ActiveDirectory.ApplicationPartition[] applicationPartitions, int index);
    parameters:
    - id: applicationPartitions
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
      description: To be added.
    - id: index
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int IndexOf (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: To be added.
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.DirectoryServices.ActiveDirectory.ApplicationPartition this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: To be added.
    return:
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
