### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  id: FaultPropagationQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultHandlerActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultSourceActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.Properties
  langs:
  - csharp
  name: FaultPropagationQueryElement
  nameWithType: FaultPropagationQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class FaultPropagationQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  langs:
  - csharp
  name: FaultPropagationQueryElement()
  nameWithType: FaultPropagationQueryElement.FaultPropagationQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultPropagationQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public FaultPropagationQueryElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultHandlerActivityName
  id: FaultHandlerActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  langs:
  - csharp
  name: FaultHandlerActivityName
  nameWithType: FaultPropagationQueryElement.FaultHandlerActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultHandlerActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string FaultHandlerActivityName { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultSourceActivityName
  id: FaultSourceActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  langs:
  - csharp
  name: FaultSourceActivityName
  nameWithType: FaultPropagationQueryElement.FaultSourceActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultSourceActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string FaultSourceActivityName { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: FaultPropagationQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: FaultPropagationQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  isExternal: false
  name: FaultPropagationQueryElement()
  nameWithType: FaultPropagationQueryElement.FaultPropagationQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultPropagationQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultHandlerActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  isExternal: false
  name: FaultHandlerActivityName
  nameWithType: FaultPropagationQueryElement.FaultHandlerActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultHandlerActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultSourceActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  isExternal: false
  name: FaultSourceActivityName
  nameWithType: FaultPropagationQueryElement.FaultSourceActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.FaultSourceActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: FaultPropagationQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement
  isExternal: false
  name: Properties
  nameWithType: FaultPropagationQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
