### YamlMime:ManagedReference
items:
- uid: System.Security.Cryptography.CryptoConfig
  id: CryptoConfig
  children:
  - System.Security.Cryptography.CryptoConfig.#ctor
  - System.Security.Cryptography.CryptoConfig.AddAlgorithm(System.Type,System.String[])
  - System.Security.Cryptography.CryptoConfig.AddOID(System.String,System.String[])
  - System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms
  - System.Security.Cryptography.CryptoConfig.CreateFromName(System.String)
  - System.Security.Cryptography.CryptoConfig.CreateFromName(System.String,System.Object[])
  - System.Security.Cryptography.CryptoConfig.EncodeOID(System.String)
  - System.Security.Cryptography.CryptoConfig.MapNameToOID(System.String)
  langs:
  - csharp
  name: CryptoConfig
  nameWithType: CryptoConfig
  fullName: System.Security.Cryptography.CryptoConfig
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class CryptoConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.#ctor
  id: '#ctor'
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: CryptoConfig()
  nameWithType: CryptoConfig.CryptoConfig()
  fullName: System.Security.Cryptography.CryptoConfig.CryptoConfig()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CryptoConfig ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.AddAlgorithm(System.Type,System.String[])
  id: AddAlgorithm(System.Type,System.String[])
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: AddAlgorithm(Type,String[])
  nameWithType: CryptoConfig.AddAlgorithm(Type,String[])
  fullName: System.Security.Cryptography.CryptoConfig.AddAlgorithm(Type,String[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static void AddAlgorithm (Type algorithm, string[] names);
    parameters:
    - id: algorithm
      type: System.Type
      description: To be added.
    - id: names
      type: System.String[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.AddOID(System.String,System.String[])
  id: AddOID(System.String,System.String[])
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: AddOID(String,String[])
  nameWithType: CryptoConfig.AddOID(String,String[])
  fullName: System.Security.Cryptography.CryptoConfig.AddOID(String,String[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static void AddOID (string oid, string[] names);
    parameters:
    - id: oid
      type: System.String
      description: To be added.
    - id: names
      type: System.String[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms
  id: AllowOnlyFipsAlgorithms
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: AllowOnlyFipsAlgorithms
  nameWithType: CryptoConfig.AllowOnlyFipsAlgorithms
  fullName: System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static bool AllowOnlyFipsAlgorithms { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.CreateFromName(System.String)
  id: CreateFromName(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: CreateFromName(String)
  nameWithType: CryptoConfig.CreateFromName(String)
  fullName: System.Security.Cryptography.CryptoConfig.CreateFromName(String)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static object CreateFromName (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Security.Cryptography.CryptoConfig.CreateFromName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.CreateFromName(System.String,System.Object[])
  id: CreateFromName(System.String,System.Object[])
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: CreateFromName(String,Object[])
  nameWithType: CryptoConfig.CreateFromName(String,Object[])
  fullName: System.Security.Cryptography.CryptoConfig.CreateFromName(String,Object[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static object CreateFromName (string name, object[] args);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: args
      type: System.Object[]
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Security.Cryptography.CryptoConfig.CreateFromName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.EncodeOID(System.String)
  id: EncodeOID(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: EncodeOID(String)
  nameWithType: CryptoConfig.EncodeOID(String)
  fullName: System.Security.Cryptography.CryptoConfig.EncodeOID(String)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static byte[] EncodeOID (string str);
    parameters:
    - id: str
      type: System.String
      description: To be added.
    return:
      type: System.Byte[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Cryptography.CryptoConfig.MapNameToOID(System.String)
  id: MapNameToOID(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  langs:
  - csharp
  name: MapNameToOID(String)
  nameWithType: CryptoConfig.MapNameToOID(String)
  fullName: System.Security.Cryptography.CryptoConfig.MapNameToOID(String)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Cryptography
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static string MapNameToOID (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Security.Cryptography.CryptoConfig.#ctor
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: CryptoConfig()
  nameWithType: CryptoConfig.CryptoConfig()
  fullName: System.Security.Cryptography.CryptoConfig.CryptoConfig()
- uid: System.Security.Cryptography.CryptoConfig.AddAlgorithm(System.Type,System.String[])
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: AddAlgorithm(Type,String[])
  nameWithType: CryptoConfig.AddAlgorithm(Type,String[])
  fullName: System.Security.Cryptography.CryptoConfig.AddAlgorithm(Type,String[])
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
- uid: System.Security.Cryptography.CryptoConfig.AddOID(System.String,System.String[])
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: AddOID(String,String[])
  nameWithType: CryptoConfig.AddOID(String,String[])
  fullName: System.Security.Cryptography.CryptoConfig.AddOID(String,String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
- uid: System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: AllowOnlyFipsAlgorithms
  nameWithType: CryptoConfig.AllowOnlyFipsAlgorithms
  fullName: System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Cryptography.CryptoConfig.CreateFromName(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: CreateFromName(String)
  nameWithType: CryptoConfig.CreateFromName(String)
  fullName: System.Security.Cryptography.CryptoConfig.CreateFromName(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Cryptography.CryptoConfig.CreateFromName(System.String,System.Object[])
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: CreateFromName(String,Object[])
  nameWithType: CryptoConfig.CreateFromName(String,Object[])
  fullName: System.Security.Cryptography.CryptoConfig.CreateFromName(String,Object[])
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object[]
- uid: System.Security.Cryptography.CryptoConfig.EncodeOID(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: EncodeOID(String)
  nameWithType: CryptoConfig.EncodeOID(String)
  fullName: System.Security.Cryptography.CryptoConfig.EncodeOID(String)
- uid: System.Byte
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Cryptography.CryptoConfig.MapNameToOID(System.String)
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: MapNameToOID(String)
  nameWithType: CryptoConfig.MapNameToOID(String)
  fullName: System.Security.Cryptography.CryptoConfig.MapNameToOID(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Cryptography.CryptoConfig.CreateFromName*
  parent: System.Security.Cryptography.CryptoConfig
  isExternal: false
  name: CreateFromName
  nameWithType: CryptoConfig.CreateFromName
