### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CodeSubDirectory
  id: CodeSubDirectory
  children:
  - System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  - System.Web.Configuration.CodeSubDirectory.DirectoryName
  - System.Web.Configuration.CodeSubDirectory.Properties
  langs:
  - csharp
  name: CodeSubDirectory
  nameWithType: CodeSubDirectory
  fullName: System.Web.Configuration.CodeSubDirectory
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class CodeSubDirectory : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: CodeSubDirectory(String)
  nameWithType: CodeSubDirectory.CodeSubDirectory(String)
  fullName: System.Web.Configuration.CodeSubDirectory.CodeSubDirectory(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public CodeSubDirectory (string directoryName);
    parameters:
    - id: directoryName
      type: System.String
      description: To be added.
  overload: System.Web.Configuration.CodeSubDirectory.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName
  id: DirectoryName
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
  fullName: System.Web.Configuration.CodeSubDirectory.DirectoryName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string DirectoryName { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Web.Configuration.CodeSubDirectory.DirectoryName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.CodeSubDirectory.Properties
  id: Properties
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: Properties
  nameWithType: CodeSubDirectory.Properties
  fullName: System.Web.Configuration.CodeSubDirectory.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.CodeSubDirectory.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: CodeSubDirectory(String)
  nameWithType: CodeSubDirectory.CodeSubDirectory(String)
  fullName: System.Web.Configuration.CodeSubDirectory.CodeSubDirectory(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
  fullName: System.Web.Configuration.CodeSubDirectory.DirectoryName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.CodeSubDirectory.Properties
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: Properties
  nameWithType: CodeSubDirectory.Properties
  fullName: System.Web.Configuration.CodeSubDirectory.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.CodeSubDirectory.#ctor*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: CodeSubDirectory
  nameWithType: CodeSubDirectory.CodeSubDirectory
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
- uid: System.Web.Configuration.CodeSubDirectory.Properties*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: Properties
  nameWithType: CodeSubDirectory.Properties
