### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  id: VisualBasicSettingsValueSerializer
  children:
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: VisualBasicSettingsValueSerializer
  nameWithType: VisualBasicSettingsValueSerializer
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class VisualBasicSettingsValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: VisualBasicSettingsValueSerializer()
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public VisualBasicSettingsValueSerializer ();
    parameters: []
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.String
      description: To be added.
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: VisualBasicSettingsValueSerializer()
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer()
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: VisualBasicSettingsValueSerializer
  nameWithType: VisualBasicSettingsValueSerializer.VisualBasicSettingsValueSerializer
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString
