### YamlMime:ManagedReference
items:
- uid: System.Data.Services.DataServiceConfiguration
  id: DataServiceConfiguration
  children:
  - System.Data.Services.DataServiceConfiguration.DataServiceBehavior
  - System.Data.Services.DataServiceConfiguration.EnableTypeAccess(System.String)
  - System.Data.Services.DataServiceConfiguration.EnableTypeConversion
  - System.Data.Services.DataServiceConfiguration.MaxBatchCount
  - System.Data.Services.DataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.DataServiceConfiguration.MaxExpandCount
  - System.Data.Services.DataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.DataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.DataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.DataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.DataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.DataServiceConfiguration.SetEntitySetPageSize(System.String,System.Int32)
  - System.Data.Services.DataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.DataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: DataServiceConfiguration
  nameWithType: DataServiceConfiguration
  fullName: System.Data.Services.DataServiceConfiguration
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class DataServiceConfiguration : System.Data.Services.IDataServiceConfiguration'
  inheritance:
  - System.Object
  implements:
  - System.Data.Services.IDataServiceConfiguration
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.DataServiceBehavior
  id: DataServiceBehavior
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: DataServiceBehavior
  nameWithType: DataServiceConfiguration.DataServiceBehavior
  fullName: System.Data.Services.DataServiceConfiguration.DataServiceBehavior
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Data.Services.DataServiceBehavior DataServiceBehavior { get; }
    return:
      type: System.Data.Services.DataServiceBehavior
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.EnableTypeAccess(System.String)
  id: EnableTypeAccess(System.String)
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: EnableTypeAccess(String)
  nameWithType: DataServiceConfiguration.EnableTypeAccess(String)
  fullName: System.Data.Services.DataServiceConfiguration.EnableTypeAccess(String)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void EnableTypeAccess (string typeName);
    parameters:
    - id: typeName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.EnableTypeConversion
  id: EnableTypeConversion
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: EnableTypeConversion
  nameWithType: DataServiceConfiguration.EnableTypeConversion
  fullName: System.Data.Services.DataServiceConfiguration.EnableTypeConversion
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool EnableTypeConversion { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: DataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: DataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: DataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: DataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.DataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: DataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.DataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: DataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.DataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: DataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.DataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: DataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.DataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.SetEntitySetPageSize(System.String,System.Int32)
  id: SetEntitySetPageSize(System.String,System.Int32)
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetPageSize(String,Int32)
  nameWithType: DataServiceConfiguration.SetEntitySetPageSize(String,Int32)
  fullName: System.Data.Services.DataServiceConfiguration.SetEntitySetPageSize(String,Int32)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetEntitySetPageSize (string name, int size);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: size
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: DataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.DataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.DataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.DataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: DataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.DataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Services.DataServiceConfiguration.DataServiceBehavior
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: DataServiceBehavior
  nameWithType: DataServiceConfiguration.DataServiceBehavior
  fullName: System.Data.Services.DataServiceConfiguration.DataServiceBehavior
- uid: System.Data.Services.DataServiceBehavior
  parent: System.Data.Services
  isExternal: false
  name: DataServiceBehavior
  nameWithType: DataServiceBehavior
  fullName: System.Data.Services.DataServiceBehavior
- uid: System.Data.Services.DataServiceConfiguration.EnableTypeAccess(System.String)
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: EnableTypeAccess(String)
  nameWithType: DataServiceConfiguration.EnableTypeAccess(String)
  fullName: System.Data.Services.DataServiceConfiguration.EnableTypeAccess(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.DataServiceConfiguration.EnableTypeConversion
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: EnableTypeConversion
  nameWithType: DataServiceConfiguration.EnableTypeConversion
  fullName: System.Data.Services.DataServiceConfiguration.EnableTypeConversion
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.DataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: DataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: DataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxChangesetCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: DataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.DataServiceConfiguration.MaxExpandCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: DataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.DataServiceConfiguration.MaxExpandDepth
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: DataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.DataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: DataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.DataServiceConfiguration.MaxResultsPerCollection
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: DataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.DataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.DataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: DataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.DataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.DataServiceConfiguration.SetEntitySetPageSize(System.String,System.Int32)
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: SetEntitySetPageSize(String,Int32)
  nameWithType: DataServiceConfiguration.SetEntitySetPageSize(String,Int32)
  fullName: System.Data.Services.DataServiceConfiguration.SetEntitySetPageSize(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.DataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: DataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.DataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.DataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.DataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: DataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.DataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
