### YamlMime:ManagedReference
items:
- uid: System.Data.Services.IDataServiceConfiguration
  id: IDataServiceConfiguration
  children:
  - System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  - System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: IDataServiceConfiguration
  nameWithType: IDataServiceConfiguration
  fullName: System.Data.Services.IDataServiceConfiguration
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public interface IDataServiceConfiguration
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType
  nameWithType: IDataServiceConfiguration.RegisterKnownType
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
