### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  id: Size3DValueSerializer
  children:
  - System.Windows.Media.Media3D.Converters.Size3DValueSerializer.#ctor
  - System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: Size3DValueSerializer
  nameWithType: Size3DValueSerializer
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class Size3DValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  langs:
  - csharp
  name: Size3DValueSerializer()
  nameWithType: Size3DValueSerializer.Size3DValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.Size3DValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Size3DValueSerializer ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Media3D.Converters
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.#ctor
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  isExternal: false
  name: Size3DValueSerializer()
  nameWithType: Size3DValueSerializer.Size3DValueSerializer()
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.Size3DValueSerializer()
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Media3D.Converters.Size3DValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Size3DValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Media3D.Converters.Size3DValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
