### YamlMime:ManagedReference
items:
- uid: System.Activities.Validation.ValidationSettings
  id: ValidationSettings
  children:
  - System.Activities.Validation.ValidationSettings.#ctor
  - System.Activities.Validation.ValidationSettings.AdditionalConstraints
  - System.Activities.Validation.ValidationSettings.CancellationToken
  - System.Activities.Validation.ValidationSettings.Environment
  - System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  - System.Activities.Validation.ValidationSettings.PrepareForRuntime
  - System.Activities.Validation.ValidationSettings.SingleLevel
  - System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Activities.Validation.ValidationSettings
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.#ctor
  id: '#ctor'
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ValidationSettings ();
    parameters: []
  overload: System.Activities.Validation.ValidationSettings.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  id: AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.IDictionary<Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>> AdditionalConstraints { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  id: CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Threading.CancellationToken CancellationToken { get; set; }
    return:
      type: System.Threading.CancellationToken
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.CancellationToken*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.Environment
  id: Environment
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Environment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.Environment*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  id: OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool OnlyUseAdditionalConstraints { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  id: PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool PrepareForRuntime { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  id: SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool SingleLevel { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.SingleLevel*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  id: SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool SkipValidatingRootConfiguration { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Validation.ValidationSettings.#ctor
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
- uid: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<Type,IList<Constraint>>
  nameWithType: IDictionary<Type,IList<Constraint>>
  fullName: System.Collections.Generic.IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.#ctor*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings
  nameWithType: ValidationSettings.ValidationSettings
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.CancellationToken*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
