### YamlMime:ManagedReference
items:
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper
  id: InternalApplicationIdentityHelper
  children:
  - System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  langs:
  - csharp
  name: InternalApplicationIdentityHelper
  nameWithType: InternalApplicationIdentityHelper
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class InternalApplicationIdentityHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  id: GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  langs:
  - csharp
  name: GetInternalAppId(ApplicationIdentity)
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Deployment.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static object GetInternalAppId (ApplicationIdentity id);
    parameters:
    - id: id
      type: System.ApplicationIdentity
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  isExternal: false
  name: GetInternalAppId(ApplicationIdentity)
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ApplicationIdentity
  parent: System
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
