### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  id: X509InitiatorCertificateClientElement
  children:
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class X509InitiatorCertificateClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public X509InitiatorCertificateClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  id: Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509InitiatorCertificateClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: To be added.
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy
  nameWithType: X509InitiatorCertificateClientElement.Copy
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
