### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  id: UseRequestHeadersForMetadataAddressElement
  children:
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.#ctor
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.BehaviorType
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CreateBehavior
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.DefaultPorts
  - System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.Properties
  langs:
  - csharp
  name: UseRequestHeadersForMetadataAddressElement
  nameWithType: UseRequestHeadersForMetadataAddressElement
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class UseRequestHeadersForMetadataAddressElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: UseRequestHeadersForMetadataAddressElement()
  nameWithType: UseRequestHeadersForMetadataAddressElement.UseRequestHeadersForMetadataAddressElement()
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.UseRequestHeadersForMetadataAddressElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public UseRequestHeadersForMetadataAddressElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: UseRequestHeadersForMetadataAddressElement.BehaviorType
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: UseRequestHeadersForMetadataAddressElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: UseRequestHeadersForMetadataAddressElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.DefaultPorts
  id: DefaultPorts
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: DefaultPorts
  nameWithType: UseRequestHeadersForMetadataAddressElement.DefaultPorts
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.DefaultPorts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.ServiceModel.Configuration.DefaultPortElementCollection DefaultPorts { get; }
    return:
      type: System.ServiceModel.Configuration.DefaultPortElementCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  langs:
  - csharp
  name: Properties
  nameWithType: UseRequestHeadersForMetadataAddressElement.Properties
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.#ctor
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: UseRequestHeadersForMetadataAddressElement()
  nameWithType: UseRequestHeadersForMetadataAddressElement.UseRequestHeadersForMetadataAddressElement()
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.UseRequestHeadersForMetadataAddressElement()
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.BehaviorType
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: BehaviorType
  nameWithType: UseRequestHeadersForMetadataAddressElement.BehaviorType
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: UseRequestHeadersForMetadataAddressElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CreateBehavior
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: UseRequestHeadersForMetadataAddressElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.DefaultPorts
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: DefaultPorts
  nameWithType: UseRequestHeadersForMetadataAddressElement.DefaultPorts
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.DefaultPorts
- uid: System.ServiceModel.Configuration.DefaultPortElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: DefaultPortElementCollection
  nameWithType: DefaultPortElementCollection
  fullName: System.ServiceModel.Configuration.DefaultPortElementCollection
- uid: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.Properties
  parent: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement
  isExternal: false
  name: Properties
  nameWithType: UseRequestHeadersForMetadataAddressElement.Properties
  fullName: System.ServiceModel.Configuration.UseRequestHeadersForMetadataAddressElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
