### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ProtocolMappingElement
  id: ProtocolMappingElement
  children:
  - System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  - System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  - System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  - System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  - System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  - System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  langs:
  - csharp
  name: ProtocolMappingElement
  nameWithType: ProtocolMappingElement
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ProtocolMappingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: ProtocolMappingElement()
  nameWithType: ProtocolMappingElement.ProtocolMappingElement()
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProtocolMappingElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: ProtocolMappingElement(String,String,String)
  nameWithType: ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProtocolMappingElement (string schemeType, string binding, string bindingConfiguration);
    parameters:
    - id: schemeType
      type: System.String
      description: To be added.
    - id: binding
      type: System.String
      description: To be added.
    - id: bindingConfiguration
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Binding
  nameWithType: ProtocolMappingElement.Binding
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Binding { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: ProtocolMappingElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProtocolMappingElement.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  id: Scheme
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  langs:
  - csharp
  name: Scheme
  nameWithType: ProtocolMappingElement.Scheme
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Scheme { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: ProtocolMappingElement()
  nameWithType: ProtocolMappingElement.ProtocolMappingElement()
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement()
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.#ctor(System.String,System.String,System.String)
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: ProtocolMappingElement(String,String,String)
  nameWithType: ProtocolMappingElement.ProtocolMappingElement(String,String,String)
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.ProtocolMappingElement(String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Binding
  nameWithType: ProtocolMappingElement.Binding
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Binding
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: ProtocolMappingElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.BindingConfiguration
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Properties
  nameWithType: ProtocolMappingElement.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
  parent: System.ServiceModel.Configuration.ProtocolMappingElement
  isExternal: false
  name: Scheme
  nameWithType: ProtocolMappingElement.Scheme
  fullName: System.ServiceModel.Configuration.ProtocolMappingElement.Scheme
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
