### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  id: ApplicationBase
  children:
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.#ctor
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  langs:
  - csharp
  name: ApplicationBase
  nameWithType: ApplicationBase
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class ApplicationBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: ApplicationBase()
  nameWithType: ApplicationBase.ApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ApplicationBase()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationBase ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  id: ChangeCulture(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: ChangeCulture(String)
  nameWithType: ApplicationBase.ChangeCulture(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(String)
  type: Method
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ChangeCulture (string cultureName);
    parameters:
    - id: cultureName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  id: ChangeUICulture(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: ChangeUICulture(String)
  nameWithType: ApplicationBase.ChangeUICulture(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(String)
  type: Method
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ChangeUICulture (string cultureName);
    parameters:
    - id: cultureName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  id: Culture
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: Culture
  nameWithType: ApplicationBase.Culture
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Globalization.CultureInfo Culture { get; }
    return:
      type: System.Globalization.CultureInfo
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  id: GetEnvironmentVariable(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: GetEnvironmentVariable(String)
  nameWithType: ApplicationBase.GetEnvironmentVariable(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(String)
  type: Method
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string GetEnvironmentVariable (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  id: Info
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: Info
  nameWithType: ApplicationBase.Info
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.VisualBasic.ApplicationServices.AssemblyInfo Info { get; }
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AssemblyInfo
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  id: Log
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: Log
  nameWithType: ApplicationBase.Log
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Microsoft.VisualBasic.Logging.Log Log { get; }
    return:
      type: Microsoft.VisualBasic.Logging.Log
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  id: UICulture
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  langs:
  - csharp
  name: UICulture
  nameWithType: ApplicationBase.UICulture
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Globalization.CultureInfo UICulture { get; }
    return:
      type: System.Globalization.CultureInfo
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: ApplicationBase()
  nameWithType: ApplicationBase.ApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ApplicationBase()
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: ChangeCulture(String)
  nameWithType: ApplicationBase.ChangeCulture(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: ChangeUICulture(String)
  nameWithType: ApplicationBase.ChangeUICulture(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Culture
  nameWithType: ApplicationBase.Culture
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: GetEnvironmentVariable(String)
  nameWithType: ApplicationBase.GetEnvironmentVariable(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Info
  nameWithType: ApplicationBase.Info
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
- uid: Microsoft.VisualBasic.ApplicationServices.AssemblyInfo
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AssemblyInfo
  nameWithType: AssemblyInfo
  fullName: Microsoft.VisualBasic.ApplicationServices.AssemblyInfo
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Log
  nameWithType: ApplicationBase.Log
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
- uid: Microsoft.VisualBasic.Logging.Log
  parent: Microsoft.VisualBasic.Logging
  isExternal: false
  name: Log
  nameWithType: Log
  fullName: Microsoft.VisualBasic.Logging.Log
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  parent: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: UICulture
  nameWithType: ApplicationBase.UICulture
  fullName: Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
