### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventHandler
  id: UnhandledExceptionEventHandler
  langs:
  - csharp
  name: UnhandledExceptionEventHandler
  nameWithType: UnhandledExceptionEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void UnhandledExceptionEventHandler(object sender, UnhandledExceptionEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
