### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  id: StartupNextInstanceEventHandler
  langs:
  - csharp
  name: StartupNextInstanceEventHandler
  nameWithType: StartupNextInstanceEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void StartupNextInstanceEventHandler(object sender, StartupNextInstanceEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
