### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
