### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  id: AuthenticationMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  id: ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  syntax:
    content: ApplicationDefined
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  id: Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  syntax:
    content: Windows
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
