### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventHandler
  id: StartupEventHandler
  langs:
  - csharp
  name: StartupEventHandler
  nameWithType: StartupEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void StartupEventHandler(object sender, StartupEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
