### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public NoStartupFormException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: inner
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
