### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  id: ShutdownEventHandler
  langs:
  - csharp
  name: ShutdownEventHandler
  nameWithType: ShutdownEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void ShutdownEventHandler(object sender, EventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
