### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  id: ConsoleApplicationBase
  children:
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  langs:
  - csharp
  name: ConsoleApplicationBase
  nameWithType: ConsoleApplicationBase
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ConsoleApplicationBase : Microsoft.VisualBasic.ApplicationServices.ApplicationBase'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: ConsoleApplicationBase()
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.ConsoleApplicationBase()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConsoleApplicationBase ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  id: CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLineArgs { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  id: Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Deployment.Application.ApplicationDeployment Deployment { get; }
    return:
      type: System.Deployment.Application.ApplicationDeployment
      description: To be added.
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  id: InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected System.Collections.ObjectModel.ReadOnlyCollection<string> InternalCommandLine { set; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  id: IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsNetworkDeployed { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: ConsoleApplicationBase()
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.ConsoleApplicationBase()
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
- uid: System.Deployment.Application.ApplicationDeployment
  parent: System.Deployment.Application
  isExternal: false
  name: ApplicationDeployment
  nameWithType: ApplicationDeployment
  fullName: System.Deployment.Application.ApplicationDeployment
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: ConsoleApplicationBase
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
