### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  id: StartupNextInstanceEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  langs:
  - csharp
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public class StartupNextInstanceEventArgs : EventArgs
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args, bool bringToForegroundFlag);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
    - id: bringToForegroundFlag
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  id: BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool BringToForeground { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
