### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  id: UnhandledExceptionEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  langs:
  - csharp
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class UnhandledExceptionEventArgs : System.Threading.ThreadExceptionEventArgs
  inheritance:
  - System.EventArgs
  - System.Threading.ThreadExceptionEventArgs
  implements: []
  inheritedMembers:
  - System.Threading.ThreadExceptionEventArgs.Exception
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  id: '#ctor(System.Boolean,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public UnhandledExceptionEventArgs (bool exitApplication, Exception exception);
    parameters:
    - id: exitApplication
      type: System.Boolean
      description: To be added.
    - id: exception
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  id: ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool ExitApplication { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Threading.ThreadExceptionEventArgs
  isExternal: false
  name: System.Threading.ThreadExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
