### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.Design.Data.IDataEnvironment
  id: IDataEnvironment
  children:
  - System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  - System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  - System.ComponentModel.Design.Data.IDataEnvironment.Connections
  - System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  langs:
  - csharp
  name: IDataEnvironment
  nameWithType: IDataEnvironment
  fullName: System.ComponentModel.Design.Data.IDataEnvironment
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public interface IDataEnvironment
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  id: BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: BuildConnection(IWin32Window,DesignerDataConnection)
  nameWithType: IDataEnvironment.BuildConnection(IWin32Window,DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(IWin32Window,DesignerDataConnection)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.ComponentModel.Design.Data.DesignerDataConnection BuildConnection (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection initialConnection);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: To be added.
    - id: initialConnection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    return:
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  id: BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
  nameWithType: IDataEnvironment.BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string BuildQuery (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection connection, System.ComponentModel.Design.Data.QueryBuilderMode mode, string initialQueryText);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: To be added.
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    - id: mode
      type: System.ComponentModel.Design.Data.QueryBuilderMode
      description: To be added.
    - id: initialQueryText
      type: System.String
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  id: ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: ConfigureConnection(IWin32Window,DesignerDataConnection,String)
  nameWithType: IDataEnvironment.ConfigureConnection(IWin32Window,DesignerDataConnection,String)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(IWin32Window,DesignerDataConnection,String)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.ComponentModel.Design.Data.DesignerDataConnection ConfigureConnection (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection connection, string name);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: To be added.
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  id: Connections
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: Connections
  nameWithType: IDataEnvironment.Connections
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  type: Property
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ICollection Connections { get; }
    return:
      type: System.Collections.ICollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: GetCodeExpression(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetCodeExpression(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(DesignerDataConnection)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.CodeDom.CodeExpression GetCodeExpression (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    return:
      type: System.CodeDom.CodeExpression
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: GetConnectionSchema(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetConnectionSchema(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(DesignerDataConnection)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.ComponentModel.Design.Data.IDesignerDataSchema GetConnectionSchema (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    return:
      type: System.ComponentModel.Design.Data.IDesignerDataSchema
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  name: GetDesignTimeConnection(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetDesignTimeConnection(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(DesignerDataConnection)
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Data.Common.DbConnection GetDesignTimeConnection (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: To be added.
    return:
      type: System.Data.Common.DbConnection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: BuildConnection(IWin32Window,DesignerDataConnection)
  nameWithType: IDataEnvironment.BuildConnection(IWin32Window,DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(IWin32Window,DesignerDataConnection)
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.Windows.Forms.IWin32Window
  parent: System.Windows.Forms
  isExternal: false
  name: IWin32Window
  nameWithType: IWin32Window
  fullName: System.Windows.Forms.IWin32Window
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
  nameWithType: IDataEnvironment.BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(IWin32Window,DesignerDataConnection,QueryBuilderMode,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Forms.IWin32Window
  parent: System.Windows.Forms
  isExternal: false
  name: IWin32Window
  nameWithType: IWin32Window
  fullName: System.Windows.Forms.IWin32Window
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.QueryBuilderMode
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: QueryBuilderMode
  nameWithType: QueryBuilderMode
  fullName: System.ComponentModel.Design.Data.QueryBuilderMode
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: ConfigureConnection(IWin32Window,DesignerDataConnection,String)
  nameWithType: IDataEnvironment.ConfigureConnection(IWin32Window,DesignerDataConnection,String)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(IWin32Window,DesignerDataConnection,String)
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.Windows.Forms.IWin32Window
  parent: System.Windows.Forms
  isExternal: false
  name: IWin32Window
  nameWithType: IWin32Window
  fullName: System.Windows.Forms.IWin32Window
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: Connections
  nameWithType: IDataEnvironment.Connections
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.Connections
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: true
  name: ICollection
  nameWithType: ICollection
  fullName: System.Collections.ICollection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetCodeExpression(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetCodeExpression(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(DesignerDataConnection)
- uid: System.CodeDom.CodeExpression
  parent: System.CodeDom
  isExternal: false
  name: CodeExpression
  nameWithType: CodeExpression
  fullName: System.CodeDom.CodeExpression
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetConnectionSchema(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetConnectionSchema(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(DesignerDataConnection)
- uid: System.ComponentModel.Design.Data.IDesignerDataSchema
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: IDesignerDataSchema
  nameWithType: IDesignerDataSchema
  fullName: System.ComponentModel.Design.Data.IDesignerDataSchema
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetDesignTimeConnection(DesignerDataConnection)
  nameWithType: IDataEnvironment.GetDesignTimeConnection(DesignerDataConnection)
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(DesignerDataConnection)
- uid: System.Data.Common.DbConnection
  parent: System.Data.Common
  isExternal: false
  name: DbConnection
  nameWithType: DbConnection
  fullName: System.Data.Common.DbConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
