### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WebServiceProtocols
  id: WebServiceProtocols
  children:
  - System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  - System.Web.Services.Configuration.WebServiceProtocols.Documentation
  - System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  - System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  - System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  - System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  - System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  - System.Web.Services.Configuration.WebServiceProtocols.Unknown
  langs:
  - csharp
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Flags]

      public enum WebServiceProtocols
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  id: AnyHttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: AnyHttpSoap
  nameWithType: WebServiceProtocols.AnyHttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: AnyHttpSoap
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  id: Documentation
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: Documentation
  nameWithType: WebServiceProtocols.Documentation
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: Documentation
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  id: HttpGet
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpGet
  nameWithType: WebServiceProtocols.HttpGet
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: HttpGet
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  id: HttpPost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpPost
  nameWithType: WebServiceProtocols.HttpPost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: HttpPost
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  id: HttpPostLocalhost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpPostLocalhost
  nameWithType: WebServiceProtocols.HttpPostLocalhost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: HttpPostLocalhost
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  id: HttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpSoap
  nameWithType: WebServiceProtocols.HttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: HttpSoap
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  id: HttpSoap12
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: HttpSoap12
  nameWithType: WebServiceProtocols.HttpSoap12
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: HttpSoap12
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  id: Unknown
  parent: System.Web.Services.Configuration.WebServiceProtocols
  langs:
  - csharp
  name: Unknown
  nameWithType: WebServiceProtocols.Unknown
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  syntax:
    content: Unknown
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: AnyHttpSoap
  nameWithType: WebServiceProtocols.AnyHttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.AnyHttpSoap
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.Documentation
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: Documentation
  nameWithType: WebServiceProtocols.Documentation
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Documentation
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpGet
  nameWithType: WebServiceProtocols.HttpGet
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpGet
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpPost
  nameWithType: WebServiceProtocols.HttpPost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPost
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpPostLocalhost
  nameWithType: WebServiceProtocols.HttpPostLocalhost
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpPostLocalhost
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpSoap
  nameWithType: WebServiceProtocols.HttpSoap
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: HttpSoap12
  nameWithType: WebServiceProtocols.HttpSoap12
  fullName: System.Web.Services.Configuration.WebServiceProtocols.HttpSoap12
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.WebServiceProtocols.Unknown
  parent: System.Web.Services.Configuration.WebServiceProtocols
  isExternal: false
  name: Unknown
  nameWithType: WebServiceProtocols.Unknown
  fullName: System.Web.Services.Configuration.WebServiceProtocols.Unknown
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
