### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement
  id: SoapExtensionTypeElement
  children:
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  langs:
  - csharp
  name: SoapExtensionTypeElement
  nameWithType: SoapExtensionTypeElement
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class SoapExtensionTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement()
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement()
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SoapExtensionTypeElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  id: '#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement(String,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SoapExtensionTypeElement (string type, int priority, System.Web.Services.Configuration.PriorityGroup group);
    parameters:
    - id: type
      type: System.String
      description: To be added.
    - id: priority
      type: System.Int32
      description: To be added.
    - id: group
      type: System.Web.Services.Configuration.PriorityGroup
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  id: '#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SoapExtensionTypeElement (Type type, int priority, System.Web.Services.Configuration.PriorityGroup group);
    parameters:
    - id: type
      type: System.Type
      description: To be added.
    - id: priority
      type: System.Int32
      description: To be added.
    - id: group
      type: System.Web.Services.Configuration.PriorityGroup
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  id: Group
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Group
  nameWithType: SoapExtensionTypeElement.Group
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Web.Services.Configuration.PriorityGroup Group { get; set; }
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  id: Priority
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Priority
  nameWithType: SoapExtensionTypeElement.Priority
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int Priority { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapExtensionTypeElement.Properties
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  id: Type
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Type
  nameWithType: SoapExtensionTypeElement.Type
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement()
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement()
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement()
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement(String,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Group
  nameWithType: SoapExtensionTypeElement.Group
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Priority
  nameWithType: SoapExtensionTypeElement.Priority
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Properties
  nameWithType: SoapExtensionTypeElement.Properties
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Type
  nameWithType: SoapExtensionTypeElement.Type
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
