### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.DiagnosticsElement
  id: DiagnosticsElement
  children:
  - System.Web.Services.Configuration.DiagnosticsElement.#ctor
  - System.Web.Services.Configuration.DiagnosticsElement.Properties
  - System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  langs:
  - csharp
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement
  fullName: System.Web.Services.Configuration.DiagnosticsElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class DiagnosticsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DiagnosticsElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  id: SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool SuppressReturningExceptions { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
