### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationTrust
  id: ApplicationTrust
  children:
  - System.Security.Policy.ApplicationTrust.#ctor
  - System.Security.Policy.ApplicationTrust.#ctor(System.ApplicationIdentity)
  - System.Security.Policy.ApplicationTrust.#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})
  - System.Security.Policy.ApplicationTrust.ApplicationIdentity
  - System.Security.Policy.ApplicationTrust.Clone
  - System.Security.Policy.ApplicationTrust.DefaultGrantSet
  - System.Security.Policy.ApplicationTrust.ExtraInfo
  - System.Security.Policy.ApplicationTrust.FromXml(System.Security.SecurityElement)
  - System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  - System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun
  - System.Security.Policy.ApplicationTrust.Persist
  - System.Security.Policy.ApplicationTrust.ToXml
  langs:
  - csharp
  name: ApplicationTrust
  nameWithType: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ApplicationTrust : System.Security.Policy.EvidenceBase, System.Security.ISecurityEncodable
  inheritance:
  - System.Object
  - System.Security.Policy.EvidenceBase
  implements:
  - System.Security.ISecurityEncodable
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.#ctor
  id: '#ctor'
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ApplicationTrust()
  nameWithType: ApplicationTrust.ApplicationTrust()
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationTrust ();
    parameters: []
  overload: System.Security.Policy.ApplicationTrust.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.#ctor(System.ApplicationIdentity)
  id: '#ctor(System.ApplicationIdentity)'
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ApplicationTrust(ApplicationIdentity)
  nameWithType: ApplicationTrust.ApplicationTrust(ApplicationIdentity)
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust(ApplicationIdentity)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationTrust (ApplicationIdentity applicationIdentity);
    parameters:
    - id: applicationIdentity
      type: System.ApplicationIdentity
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})
  id: '#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})'
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
  nameWithType: ApplicationTrust.ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationTrust (System.Security.PermissionSet defaultGrantSet, System.Collections.Generic.IEnumerable<System.Security.Policy.StrongName> fullTrustAssemblies);
    parameters:
    - id: defaultGrantSet
      type: System.Security.PermissionSet
      description: To be added.
    - id: fullTrustAssemblies
      type: System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName}
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.ApplicationIdentity
  id: ApplicationIdentity
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ApplicationIdentity
  nameWithType: ApplicationTrust.ApplicationIdentity
  fullName: System.Security.Policy.ApplicationTrust.ApplicationIdentity
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationIdentity ApplicationIdentity { get; set; }
    return:
      type: System.ApplicationIdentity
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.ApplicationIdentity*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.Clone
  id: Clone
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: Clone()
  nameWithType: ApplicationTrust.Clone()
  fullName: System.Security.Policy.ApplicationTrust.Clone()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.Policy.EvidenceBase Clone ();
    parameters: []
    return:
      type: System.Security.Policy.EvidenceBase
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.Clone*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.DefaultGrantSet
  id: DefaultGrantSet
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: DefaultGrantSet
  nameWithType: ApplicationTrust.DefaultGrantSet
  fullName: System.Security.Policy.ApplicationTrust.DefaultGrantSet
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Policy.PolicyStatement DefaultGrantSet { get; set; }
    return:
      type: System.Security.Policy.PolicyStatement
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.DefaultGrantSet*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.ExtraInfo
  id: ExtraInfo
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ExtraInfo
  nameWithType: ApplicationTrust.ExtraInfo
  fullName: System.Security.Policy.ApplicationTrust.ExtraInfo
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object ExtraInfo { get; set; }
    return:
      type: System.Object
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.ExtraInfo*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: FromXml(SecurityElement)
  nameWithType: ApplicationTrust.FromXml(SecurityElement)
  fullName: System.Security.Policy.ApplicationTrust.FromXml(SecurityElement)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void FromXml (System.Security.SecurityElement element);
    parameters:
    - id: element
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.FromXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  id: FullTrustAssemblies
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: FullTrustAssemblies
  nameWithType: ApplicationTrust.FullTrustAssemblies
  fullName: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.IList<System.Security.Policy.StrongName> FullTrustAssemblies { get; }
    return:
      type: System.Collections.Generic.IList{System.Security.Policy.StrongName}
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.FullTrustAssemblies*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun
  id: IsApplicationTrustedToRun
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: IsApplicationTrustedToRun
  nameWithType: ApplicationTrust.IsApplicationTrustedToRun
  fullName: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsApplicationTrustedToRun { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.Persist
  id: Persist
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: Persist
  nameWithType: ApplicationTrust.Persist
  fullName: System.Security.Policy.ApplicationTrust.Persist
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool Persist { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.Persist*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationTrust.ToXml
  id: ToXml
  parent: System.Security.Policy.ApplicationTrust
  langs:
  - csharp
  name: ToXml()
  nameWithType: ApplicationTrust.ToXml()
  fullName: System.Security.Policy.ApplicationTrust.ToXml()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Security.Policy.ApplicationTrust.ToXml*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Security.Policy.EvidenceBase
  isExternal: false
  name: System.Security.Policy.EvidenceBase
- uid: System.Security.Policy.ApplicationTrust.#ctor
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationTrust()
  nameWithType: ApplicationTrust.ApplicationTrust()
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust()
- uid: System.Security.Policy.ApplicationTrust.#ctor(System.ApplicationIdentity)
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationTrust(ApplicationIdentity)
  nameWithType: ApplicationTrust.ApplicationTrust(ApplicationIdentity)
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust(ApplicationIdentity)
- uid: System.ApplicationIdentity
  parent: System
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
- uid: System.Security.Policy.ApplicationTrust.#ctor(System.Security.PermissionSet,System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName})
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
  nameWithType: ApplicationTrust.ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
  fullName: System.Security.Policy.ApplicationTrust.ApplicationTrust(PermissionSet,IEnumerable<StrongName>)
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: System.Security.PermissionSet
- uid: System.Collections.Generic.IEnumerable{System.Security.Policy.StrongName}
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<StrongName>
  nameWithType: IEnumerable<StrongName>
  fullName: System.Collections.Generic.IEnumerable<System.Security.Policy.StrongName>
- uid: System.Security.Policy.ApplicationTrust.ApplicationIdentity
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationTrust.ApplicationIdentity
  fullName: System.Security.Policy.ApplicationTrust.ApplicationIdentity
- uid: System.ApplicationIdentity
  parent: System
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
- uid: System.Security.Policy.ApplicationTrust.Clone
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: Clone()
  nameWithType: ApplicationTrust.Clone()
  fullName: System.Security.Policy.ApplicationTrust.Clone()
- uid: System.Security.Policy.EvidenceBase
  parent: System.Security.Policy
  isExternal: false
  name: EvidenceBase
  nameWithType: EvidenceBase
  fullName: System.Security.Policy.EvidenceBase
- uid: System.Security.Policy.ApplicationTrust.DefaultGrantSet
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: DefaultGrantSet
  nameWithType: ApplicationTrust.DefaultGrantSet
  fullName: System.Security.Policy.ApplicationTrust.DefaultGrantSet
- uid: System.Security.Policy.PolicyStatement
  parent: System.Security.Policy
  isExternal: false
  name: PolicyStatement
  nameWithType: PolicyStatement
  fullName: System.Security.Policy.PolicyStatement
- uid: System.Security.Policy.ApplicationTrust.ExtraInfo
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ExtraInfo
  nameWithType: ApplicationTrust.ExtraInfo
  fullName: System.Security.Policy.ApplicationTrust.ExtraInfo
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Security.Policy.ApplicationTrust.FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: FromXml(SecurityElement)
  nameWithType: ApplicationTrust.FromXml(SecurityElement)
  fullName: System.Security.Policy.ApplicationTrust.FromXml(SecurityElement)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: FullTrustAssemblies
  nameWithType: ApplicationTrust.FullTrustAssemblies
  fullName: System.Security.Policy.ApplicationTrust.FullTrustAssemblies
- uid: System.Collections.Generic.IList{System.Security.Policy.StrongName}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<StrongName>
  nameWithType: IList<StrongName>
  fullName: System.Collections.Generic.IList<System.Security.Policy.StrongName>
- uid: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: IsApplicationTrustedToRun
  nameWithType: ApplicationTrust.IsApplicationTrustedToRun
  fullName: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Policy.ApplicationTrust.Persist
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: Persist
  nameWithType: ApplicationTrust.Persist
  fullName: System.Security.Policy.ApplicationTrust.Persist
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Policy.ApplicationTrust.ToXml
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ToXml()
  nameWithType: ApplicationTrust.ToXml()
  fullName: System.Security.Policy.ApplicationTrust.ToXml()
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationTrust.#ctor*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationTrust
  nameWithType: ApplicationTrust.ApplicationTrust
- uid: System.Security.Policy.ApplicationTrust.ApplicationIdentity*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationTrust.ApplicationIdentity
- uid: System.Security.Policy.ApplicationTrust.Clone*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: Clone
  nameWithType: ApplicationTrust.Clone
- uid: System.Security.Policy.ApplicationTrust.DefaultGrantSet*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: DefaultGrantSet
  nameWithType: ApplicationTrust.DefaultGrantSet
- uid: System.Security.Policy.ApplicationTrust.ExtraInfo*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ExtraInfo
  nameWithType: ApplicationTrust.ExtraInfo
- uid: System.Security.Policy.ApplicationTrust.FromXml*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: FromXml
  nameWithType: ApplicationTrust.FromXml
- uid: System.Security.Policy.ApplicationTrust.FullTrustAssemblies*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: FullTrustAssemblies
  nameWithType: ApplicationTrust.FullTrustAssemblies
- uid: System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: IsApplicationTrustedToRun
  nameWithType: ApplicationTrust.IsApplicationTrustedToRun
- uid: System.Security.Policy.ApplicationTrust.Persist*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: Persist
  nameWithType: ApplicationTrust.Persist
- uid: System.Security.Policy.ApplicationTrust.ToXml*
  parent: System.Security.Policy.ApplicationTrust
  isExternal: false
  name: ToXml
  nameWithType: ApplicationTrust.ToXml
