### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationVersionMatch
  id: ApplicationVersionMatch
  children:
  - System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  - System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  langs:
  - csharp
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum ApplicationVersionMatch
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  id: MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  syntax:
    content: MatchAllVersions
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  id: MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  syntax:
    content: MatchExactVersion
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
- uid: System.Security.Policy.ApplicationVersionMatch
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
- uid: System.Security.Policy.ApplicationVersionMatch
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
