### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationSecurityInfo
  id: ApplicationSecurityInfo
  children:
  - System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  - System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  - System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  - System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  - System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  langs:
  - csharp
  name: ApplicationSecurityInfo
  nameWithType: ApplicationSecurityInfo
  fullName: System.Security.Policy.ApplicationSecurityInfo
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Security.SecurityCritical]

      public sealed class ApplicationSecurityInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  id: '#ctor(System.ActivationContext)'
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationSecurityInfo(ActivationContext)
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationSecurityInfo (ActivationContext activationContext);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: To be added.
  overload: System.Security.Policy.ApplicationSecurityInfo.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  id: ApplicationEvidence
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Policy.Evidence ApplicationEvidence { get; set; }
    return:
      type: System.Security.Policy.Evidence
      description: To be added.
  overload: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  id: ApplicationId
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationId ApplicationId { get; set; }
    return:
      type: System.ApplicationId
      description: To be added.
  overload: System.Security.Policy.ApplicationSecurityInfo.ApplicationId*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  id: DefaultRequestSet
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
  fullName: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.PermissionSet DefaultRequestSet { get; set; }
    return:
      type: System.Security.PermissionSet
      description: To be added.
  overload: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  id: DeploymentId
  parent: System.Security.Policy.ApplicationSecurityInfo
  langs:
  - csharp
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
  fullName: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationId DeploymentId { get; set; }
    return:
      type: System.ApplicationId
      description: To be added.
  overload: System.Security.Policy.ApplicationSecurityInfo.DeploymentId*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor(System.ActivationContext)
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationSecurityInfo(ActivationContext)
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationSecurityInfo(ActivationContext)
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence
- uid: System.Security.Policy.Evidence
  parent: System.Security.Policy
  isExternal: false
  name: Evidence
  nameWithType: Evidence
  fullName: System.Security.Policy.Evidence
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
  fullName: System.Security.Policy.ApplicationSecurityInfo.ApplicationId
- uid: System.ApplicationId
  parent: System
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationId
  fullName: System.ApplicationId
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
  fullName: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: System.Security.PermissionSet
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
  fullName: System.Security.Policy.ApplicationSecurityInfo.DeploymentId
- uid: System.ApplicationId
  parent: System
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationId
  fullName: System.ApplicationId
- uid: System.Security.Policy.ApplicationSecurityInfo.#ctor*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationSecurityInfo
  nameWithType: ApplicationSecurityInfo.ApplicationSecurityInfo
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationEvidence*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationEvidence
  nameWithType: ApplicationSecurityInfo.ApplicationEvidence
- uid: System.Security.Policy.ApplicationSecurityInfo.ApplicationId*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationSecurityInfo.ApplicationId
- uid: System.Security.Policy.ApplicationSecurityInfo.DefaultRequestSet*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DefaultRequestSet
  nameWithType: ApplicationSecurityInfo.DefaultRequestSet
- uid: System.Security.Policy.ApplicationSecurityInfo.DeploymentId*
  parent: System.Security.Policy.ApplicationSecurityInfo
  isExternal: false
  name: DeploymentId
  nameWithType: ApplicationSecurityInfo.DeploymentId
