### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition
  id: ApplicationDirectoryMembershipCondition
  children:
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  langs:
  - csharp
  name: ApplicationDirectoryMembershipCondition
  nameWithType: ApplicationDirectoryMembershipCondition
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ApplicationDirectoryMembershipCondition
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  id: '#ctor'
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: ApplicationDirectoryMembershipCondition()
  nameWithType: ApplicationDirectoryMembershipCondition.ApplicationDirectoryMembershipCondition()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ApplicationDirectoryMembershipCondition()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationDirectoryMembershipCondition ();
    parameters: []
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  id: Check(System.Security.Policy.Evidence)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: Check(Evidence)
  nameWithType: ApplicationDirectoryMembershipCondition.Check(Evidence)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(Evidence)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool Check (System.Security.Policy.Evidence evidence);
    parameters:
    - id: evidence
      type: System.Security.Policy.Evidence
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  id: Copy
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: Copy()
  nameWithType: ApplicationDirectoryMembershipCondition.Copy()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.Policy.IMembershipCondition Copy ();
    parameters: []
    return:
      type: System.Security.Policy.IMembershipCondition
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: ApplicationDirectoryMembershipCondition.Equals(Object)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(Object)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: FromXml(SecurityElement)
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml(SecurityElement)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(SecurityElement)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void FromXml (System.Security.SecurityElement e);
    parameters:
    - id: e
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  id: FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: FromXml(SecurityElement,PolicyLevel)
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml(SecurityElement,PolicyLevel)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(SecurityElement,PolicyLevel)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void FromXml (System.Security.SecurityElement e, System.Security.Policy.PolicyLevel level);
    parameters:
    - id: e
      type: System.Security.SecurityElement
      description: To be added.
    - id: level
      type: System.Security.Policy.PolicyLevel
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  id: GetHashCode
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: ApplicationDirectoryMembershipCondition.GetHashCode()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  id: ToString
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationDirectoryMembershipCondition.ToString()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  id: ToXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: ToXml()
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  id: ToXml(System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  name: ToXml(PolicyLevel)
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml(PolicyLevel)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(PolicyLevel)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Security.SecurityElement ToXml (System.Security.Policy.PolicyLevel level);
    parameters:
    - id: level
      type: System.Security.Policy.PolicyLevel
      description: To be added.
    return:
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ApplicationDirectoryMembershipCondition()
  nameWithType: ApplicationDirectoryMembershipCondition.ApplicationDirectoryMembershipCondition()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ApplicationDirectoryMembershipCondition()
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Check(Evidence)
  nameWithType: ApplicationDirectoryMembershipCondition.Check(Evidence)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(Evidence)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Policy.Evidence
  parent: System.Security.Policy
  isExternal: false
  name: Evidence
  nameWithType: Evidence
  fullName: System.Security.Policy.Evidence
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Copy()
  nameWithType: ApplicationDirectoryMembershipCondition.Copy()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy()
- uid: System.Security.Policy.IMembershipCondition
  parent: System.Security.Policy
  isExternal: false
  name: IMembershipCondition
  nameWithType: IMembershipCondition
  fullName: System.Security.Policy.IMembershipCondition
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Equals(Object)
  nameWithType: ApplicationDirectoryMembershipCondition.Equals(Object)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: FromXml(SecurityElement)
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml(SecurityElement)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(SecurityElement)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: FromXml(SecurityElement,PolicyLevel)
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml(SecurityElement,PolicyLevel)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(SecurityElement,PolicyLevel)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.PolicyLevel
  parent: System.Security.Policy
  isExternal: false
  name: PolicyLevel
  nameWithType: PolicyLevel
  fullName: System.Security.Policy.PolicyLevel
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: GetHashCode()
  nameWithType: ApplicationDirectoryMembershipCondition.GetHashCode()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToString()
  nameWithType: ApplicationDirectoryMembershipCondition.ToString()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToXml()
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml()
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml()
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToXml(PolicyLevel)
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml(PolicyLevel)
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(PolicyLevel)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.PolicyLevel
  parent: System.Security.Policy
  isExternal: false
  name: PolicyLevel
  nameWithType: PolicyLevel
  fullName: System.Security.Policy.PolicyLevel
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ApplicationDirectoryMembershipCondition
  nameWithType: ApplicationDirectoryMembershipCondition.ApplicationDirectoryMembershipCondition
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Check
  nameWithType: ApplicationDirectoryMembershipCondition.Check
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Copy
  nameWithType: ApplicationDirectoryMembershipCondition.Copy
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Equals
  nameWithType: ApplicationDirectoryMembershipCondition.Equals
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: FromXml
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: GetHashCode
  nameWithType: ApplicationDirectoryMembershipCondition.GetHashCode
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToString
  nameWithType: ApplicationDirectoryMembershipCondition.ToString
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml*
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToXml
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml
