### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  id: SystemIdentityModelServicesSection
  children:
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  langs:
  - csharp
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class SystemIdentityModelServicesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: SystemIdentityModelServicesSection()
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SystemIdentityModelServicesSection ();
    parameters: []
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  id: Current
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection Current { get; }
    return:
      type: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
      description: To be added.
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  id: DefaultFederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.IdentityModel.Services.Configuration.FederationConfigurationElement DefaultFederationConfigurationElement { get; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfigurationElement
      description: To be added.
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  id: FederationConfigurationElements
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection FederationConfigurationElements { get; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
      description: To be added.
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  id: SectionName
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: SectionName
  nameWithType: SystemIdentityModelServicesSection.SectionName
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  type: Field
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public const string SectionName;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SystemIdentityModelServicesSection()
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfigurationElement
  nameWithType: FederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfigurationElementCollection
  nameWithType: FederationConfigurationElementCollection
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SectionName
  nameWithType: SystemIdentityModelServicesSection.SectionName
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
