### YamlMime:ManagedReference
items:
- uid: System.ApplicationId
  id: ApplicationId
  children:
  - System.ApplicationId.#ctor(System.Byte[],System.String,System.Version,System.String,System.String)
  - System.ApplicationId.Copy
  - System.ApplicationId.Culture
  - System.ApplicationId.Equals(System.Object)
  - System.ApplicationId.GetHashCode
  - System.ApplicationId.Name
  - System.ApplicationId.ProcessorArchitecture
  - System.ApplicationId.PublicKeyToken
  - System.ApplicationId.ToString
  - System.ApplicationId.Version
  langs:
  - csharp
  name: ApplicationId
  nameWithType: ApplicationId
  fullName: System.ApplicationId
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ApplicationId
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.#ctor(System.Byte[],System.String,System.Version,System.String,System.String)
  id: '#ctor(System.Byte[],System.String,System.Version,System.String,System.String)'
  parent: System.ApplicationId
  langs:
  - csharp
  name: ApplicationId(Byte[],String,Version,String,String)
  nameWithType: ApplicationId.ApplicationId(Byte[],String,Version,String,String)
  fullName: System.ApplicationId.ApplicationId(Byte[],String,Version,String,String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationId (byte[] publicKeyToken, string name, Version version, string processorArchitecture, string culture);
    parameters:
    - id: publicKeyToken
      type: System.Byte[]
      description: To be added.
    - id: name
      type: System.String
      description: To be added.
    - id: version
      type: System.Version
      description: To be added.
    - id: processorArchitecture
      type: System.String
      description: To be added.
    - id: culture
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.Copy
  id: Copy
  parent: System.ApplicationId
  langs:
  - csharp
  name: Copy()
  nameWithType: ApplicationId.Copy()
  fullName: System.ApplicationId.Copy()
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ApplicationId Copy ();
    parameters: []
    return:
      type: System.ApplicationId
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.Culture
  id: Culture
  parent: System.ApplicationId
  langs:
  - csharp
  name: Culture
  nameWithType: ApplicationId.Culture
  fullName: System.ApplicationId.Culture
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Culture { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ApplicationId
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: ApplicationId.Equals(Object)
  fullName: System.ApplicationId.Equals(Object)
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.GetHashCode
  id: GetHashCode
  parent: System.ApplicationId
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: ApplicationId.GetHashCode()
  fullName: System.ApplicationId.GetHashCode()
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.Name
  id: Name
  parent: System.ApplicationId
  langs:
  - csharp
  name: Name
  nameWithType: ApplicationId.Name
  fullName: System.ApplicationId.Name
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.ProcessorArchitecture
  id: ProcessorArchitecture
  parent: System.ApplicationId
  langs:
  - csharp
  name: ProcessorArchitecture
  nameWithType: ApplicationId.ProcessorArchitecture
  fullName: System.ApplicationId.ProcessorArchitecture
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ProcessorArchitecture { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.PublicKeyToken
  id: PublicKeyToken
  parent: System.ApplicationId
  langs:
  - csharp
  name: PublicKeyToken
  nameWithType: ApplicationId.PublicKeyToken
  fullName: System.ApplicationId.PublicKeyToken
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public byte[] PublicKeyToken { get; }
    return:
      type: System.Byte[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.ToString
  id: ToString
  parent: System.ApplicationId
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationId.ToString()
  fullName: System.ApplicationId.ToString()
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ApplicationId.Version
  id: Version
  parent: System.ApplicationId
  langs:
  - csharp
  name: Version
  nameWithType: ApplicationId.Version
  fullName: System.ApplicationId.Version
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Version Version { get; }
    return:
      type: System.Version
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ApplicationId.#ctor(System.Byte[],System.String,System.Version,System.String,System.String)
  parent: System.ApplicationId
  isExternal: false
  name: ApplicationId(Byte[],String,Version,String,String)
  nameWithType: ApplicationId.ApplicationId(Byte[],String,Version,String,String)
  fullName: System.ApplicationId.ApplicationId(Byte[],String,Version,String,String)
- uid: System.Byte
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationId.Copy
  parent: System.ApplicationId
  isExternal: false
  name: Copy()
  nameWithType: ApplicationId.Copy()
  fullName: System.ApplicationId.Copy()
- uid: System.ApplicationId
  parent: System
  isExternal: false
  name: ApplicationId
  nameWithType: ApplicationId
  fullName: System.ApplicationId
- uid: System.ApplicationId.Culture
  parent: System.ApplicationId
  isExternal: false
  name: Culture
  nameWithType: ApplicationId.Culture
  fullName: System.ApplicationId.Culture
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationId.Equals(System.Object)
  parent: System.ApplicationId
  isExternal: false
  name: Equals(Object)
  nameWithType: ApplicationId.Equals(Object)
  fullName: System.ApplicationId.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ApplicationId.GetHashCode
  parent: System.ApplicationId
  isExternal: false
  name: GetHashCode()
  nameWithType: ApplicationId.GetHashCode()
  fullName: System.ApplicationId.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ApplicationId.Name
  parent: System.ApplicationId
  isExternal: false
  name: Name
  nameWithType: ApplicationId.Name
  fullName: System.ApplicationId.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationId.ProcessorArchitecture
  parent: System.ApplicationId
  isExternal: false
  name: ProcessorArchitecture
  nameWithType: ApplicationId.ProcessorArchitecture
  fullName: System.ApplicationId.ProcessorArchitecture
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationId.PublicKeyToken
  parent: System.ApplicationId
  isExternal: false
  name: PublicKeyToken
  nameWithType: ApplicationId.PublicKeyToken
  fullName: System.ApplicationId.PublicKeyToken
- uid: System.Byte
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
- uid: System.ApplicationId.ToString
  parent: System.ApplicationId
  isExternal: false
  name: ToString()
  nameWithType: ApplicationId.ToString()
  fullName: System.ApplicationId.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationId.Version
  parent: System.ApplicationId
  isExternal: false
  name: Version
  nameWithType: ApplicationId.Version
  fullName: System.ApplicationId.Version
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
