### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: To be added.
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
