### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  langs:
  - csharp
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyVersionCompatibility
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SameDomain
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SameMachine
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SameProcess
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
