### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  id: AssemblyHashAlgorithm
  children:
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  - System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  langs:
  - csharp
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyHashAlgorithm
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  id: MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: MD5
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  id: None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: None
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  id: SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SHA1
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  id: SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SHA256
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  id: SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SHA384
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  id: SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  langs:
  - csharp
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: To be added.
  syntax:
    content: SHA512
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: MD5
  nameWithType: AssemblyHashAlgorithm.MD5
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: None
  nameWithType: AssemblyHashAlgorithm.None
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.None
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA1
  nameWithType: AssemblyHashAlgorithm.SHA1
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA256
  nameWithType: AssemblyHashAlgorithm.SHA256
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA384
  nameWithType: AssemblyHashAlgorithm.SHA384
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
  parent: System.Configuration.Assemblies.AssemblyHashAlgorithm
  isExternal: false
  name: SHA512
  nameWithType: AssemblyHashAlgorithm.SHA512
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
