### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.StreamChangeCallback
  id: StreamChangeCallback
  langs:
  - csharp
  name: StreamChangeCallback
  nameWithType: StreamChangeCallback
  fullName: System.Configuration.Internal.StreamChangeCallback
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public delegate void StreamChangeCallback(string streamName);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
