### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigClientHost
  id: IInternalConfigClientHost
  children:
  - System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigClientHost
  nameWithType: IInternalConfigClientHost
  fullName: System.Configuration.Internal.IInternalConfigClientHost
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigClientHost
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  id: GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string GetExeConfigPath ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  id: GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string GetLocalUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  id: GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string GetRoamingUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  id: IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsExeConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  id: IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsLocalUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  id: IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsRoamingUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
