### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory
  id: IInternalConfigConfigurationFactory
  children:
  - System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  - System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  langs:
  - csharp
  name: IInternalConfigConfigurationFactory
  nameWithType: IInternalConfigConfigurationFactory
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigConfigurationFactory
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  id: Create(System.Type,System.Object[])
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  langs:
  - csharp
  name: Create(Type,Object[])
  nameWithType: IInternalConfigConfigurationFactory.Create(Type,Object[])
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type,Object[])
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Configuration Create (Type typeConfigHost, object[] hostInitConfigurationParams);
    parameters:
    - id: typeConfigHost
      type: System.Type
      description: To be added.
    - id: hostInitConfigurationParams
      type: System.Object[]
      description: To be added.
    return:
      type: System.Configuration.Configuration
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  id: NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  langs:
  - csharp
  name: NormalizeLocationSubPath(String,IConfigErrorInfo)
  nameWithType: IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string NormalizeLocationSubPath (string subPath, System.Configuration.Internal.IConfigErrorInfo errorInfo);
    parameters:
    - id: subPath
      type: System.String
      description: To be added.
    - id: errorInfo
      type: System.Configuration.Internal.IConfigErrorInfo
      description: To be added.
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: Create(Type,Object[])
  nameWithType: IInternalConfigConfigurationFactory.Create(Type,Object[])
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type,Object[])
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object[]
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: NormalizeLocationSubPath(String,IConfigErrorInfo)
  nameWithType: IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigErrorInfo
  parent: System.Configuration.Internal
  isExternal: false
  name: IConfigErrorInfo
  nameWithType: IConfigErrorInfo
  fullName: System.Configuration.Internal.IConfigErrorInfo
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create*
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: Create
  nameWithType: IInternalConfigConfigurationFactory.Create
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath*
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: NormalizeLocationSubPath
  nameWithType: IInternalConfigConfigurationFactory.NormalizeLocationSubPath
