### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigRecord
  id: IInternalConfigRecord
  children:
  - System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  - System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  - System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.Remove
  - System.Configuration.Internal.IInternalConfigRecord.StreamName
  - System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  langs:
  - csharp
  name: IInternalConfigRecord
  nameWithType: IInternalConfigRecord
  fullName: System.Configuration.Internal.IInternalConfigRecord
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigRecord
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  id: ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ConfigPath { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  id: GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object GetLkgSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  id: HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool HasInitErrors { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  id: RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void RefreshSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  id: Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Remove ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.Remove*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  id: StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string StreamName { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  id: ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ThrowIfInitErrors ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection
  nameWithType: IInternalConfigRecord.GetLkgSection
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigRecord.GetSection
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection
  nameWithType: IInternalConfigRecord.RefreshSection
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove
  nameWithType: IInternalConfigRecord.Remove
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors
