### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventArgs
  id: InternalConfigEventArgs
  children:
  - System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  - System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  langs:
  - csharp
  name: InternalConfigEventArgs
  nameWithType: InternalConfigEventArgs
  fullName: System.Configuration.Internal.InternalConfigEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class InternalConfigEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Internal.InternalConfigEventArgs
  langs:
  - csharp
  name: InternalConfigEventArgs(String)
  nameWithType: InternalConfigEventArgs.InternalConfigEventArgs(String)
  fullName: System.Configuration.Internal.InternalConfigEventArgs.InternalConfigEventArgs(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InternalConfigEventArgs (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  id: ConfigPath
  parent: System.Configuration.Internal.InternalConfigEventArgs
  langs:
  - csharp
  name: ConfigPath
  nameWithType: InternalConfigEventArgs.ConfigPath
  fullName: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ConfigPath { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: InternalConfigEventArgs(String)
  nameWithType: InternalConfigEventArgs.InternalConfigEventArgs(String)
  fullName: System.Configuration.Internal.InternalConfigEventArgs.InternalConfigEventArgs(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: ConfigPath
  nameWithType: InternalConfigEventArgs.ConfigPath
  fullName: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
