### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigErrorInfo
  id: IConfigErrorInfo
  children:
  - System.Configuration.Internal.IConfigErrorInfo.Filename
  - System.Configuration.Internal.IConfigErrorInfo.LineNumber
  langs:
  - csharp
  name: IConfigErrorInfo
  nameWithType: IConfigErrorInfo
  fullName: System.Configuration.Internal.IConfigErrorInfo
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public interface IConfigErrorInfo
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  id: Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Filename { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  id: LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
