### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigSystem
  id: IInternalConfigSystem
  children:
  - System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  langs:
  - csharp
  name: IInternalConfigSystem
  nameWithType: IInternalConfigSystem
  fullName: System.Configuration.Internal.IInternalConfigSystem
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigSystem
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: IInternalConfigSystem.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  id: RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: RefreshConfig(String)
  nameWithType: IInternalConfigSystem.RefreshConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void RefreshConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: GetSection(String)
  nameWithType: IInternalConfigSystem.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: RefreshConfig(String)
  nameWithType: IInternalConfigSystem.RefreshConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
