### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigSystem
  id: IConfigSystem
  children:
  - System.Configuration.Internal.IConfigSystem.Host
  - System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  - System.Configuration.Internal.IConfigSystem.Root
  langs:
  - csharp
  name: IConfigSystem
  nameWithType: IConfigSystem
  fullName: System.Configuration.Internal.IConfigSystem
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public interface IConfigSystem
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigSystem.Host
  id: Host
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Host
  nameWithType: IConfigSystem.Host
  fullName: System.Configuration.Internal.IConfigSystem.Host
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Internal.IInternalConfigHost Host { get; }
    return:
      type: System.Configuration.Internal.IInternalConfigHost
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  id: Init(System.Type,System.Object[])
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Init(Type,Object[])
  nameWithType: IConfigSystem.Init(Type,Object[])
  fullName: System.Configuration.Internal.IConfigSystem.Init(Type,Object[])
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Init (Type typeConfigHost, object[] hostInitParams);
    parameters:
    - id: typeConfigHost
      type: System.Type
      description: To be added.
    - id: hostInitParams
      type: System.Object[]
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigSystem.Root
  id: Root
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Root
  nameWithType: IConfigSystem.Root
  fullName: System.Configuration.Internal.IConfigSystem.Root
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRoot Root { get; }
    return:
      type: System.Configuration.Internal.IInternalConfigRoot
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IConfigSystem.Host
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Host
  nameWithType: IConfigSystem.Host
  fullName: System.Configuration.Internal.IConfigSystem.Host
- uid: System.Configuration.Internal.IInternalConfigHost
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigHost
  nameWithType: IInternalConfigHost
  fullName: System.Configuration.Internal.IInternalConfigHost
- uid: System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Init(Type,Object[])
  nameWithType: IConfigSystem.Init(Type,Object[])
  fullName: System.Configuration.Internal.IConfigSystem.Init(Type,Object[])
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object[]
- uid: System.Configuration.Internal.IConfigSystem.Root
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Root
  nameWithType: IConfigSystem.Root
  fullName: System.Configuration.Internal.IConfigSystem.Root
- uid: System.Configuration.Internal.IInternalConfigRoot
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigRoot
  nameWithType: IInternalConfigRoot
  fullName: System.Configuration.Internal.IInternalConfigRoot
