### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventHandler
  id: InternalConfigEventHandler
  langs:
  - csharp
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public delegate void InternalConfigEventHandler(object sender, InternalConfigEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
