### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedException
  id: WorkflowApplicationAbortedException
  children:
  - System.Activities.WorkflowApplicationAbortedException.#ctor
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationAbortedException
  nameWithType: WorkflowApplicationAbortedException
  fullName: System.Activities.WorkflowApplicationAbortedException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class WorkflowApplicationAbortedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationAbortedException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationAbortedException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected WorkflowApplicationAbortedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: instanceId
      type: System.Guid
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: instanceId
      type: System.Guid
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
