### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedEventArgs
  id: WorkflowApplicationCompletedEventArgs
  children:
  - System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  - System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  - System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  langs:
  - csharp
  name: WorkflowApplicationCompletedEventArgs
  nameWithType: WorkflowApplicationCompletedEventArgs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class WorkflowApplicationCompletedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  id: CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Activities.ActivityInstanceState CompletionState { get; }
    return:
      type: System.Activities.ActivityInstanceState
      description: To be added.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  id: Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Outputs { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: To be added.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  id: TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Exception TerminationException { get; }
    return:
      type: System.Exception
      description: To be added.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.ActivityInstanceState
  parent: System.Activities
  isExternal: false
  name: ActivityInstanceState
  nameWithType: ActivityInstanceState
  fullName: System.Activities.ActivityInstanceState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
