### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationIdleEventArgs
  id: WorkflowApplicationIdleEventArgs
  children:
  - System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  langs:
  - csharp
  name: WorkflowApplicationIdleEventArgs
  nameWithType: WorkflowApplicationIdleEventArgs
  fullName: System.Activities.WorkflowApplicationIdleEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class WorkflowApplicationIdleEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  id: Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  langs:
  - csharp
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo> Bookmarks { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  isExternal: false
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<BookmarkInfo>
  nameWithType: ReadOnlyCollection<BookmarkInfo>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo>
