### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  id: WorkflowApplicationUnhandledExceptionEventArgs
  children:
  - System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  - System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  - System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  langs:
  - csharp
  name: WorkflowApplicationUnhandledExceptionEventArgs
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class WorkflowApplicationUnhandledExceptionEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  id: ExceptionSource
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExceptionSource
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Activities.Activity ExceptionSource { get; }
    return:
      type: System.Activities.Activity
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  id: ExceptionSourceInstanceId
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExceptionSourceInstanceId
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ExceptionSourceInstanceId { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  id: UnhandledException
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  langs:
  - csharp
  name: UnhandledException
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Exception UnhandledException { get; }
    return:
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  isExternal: false
  name: ExceptionSource
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource
- uid: System.Activities.Activity
  parent: System.Activities
  isExternal: false
  name: Activity
  nameWithType: Activity
  fullName: System.Activities.Activity
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  isExternal: false
  name: ExceptionSourceInstanceId
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  parent: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledException
  nameWithType: WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
  fullName: System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
