### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationInstance
  id: WorkflowApplicationInstance
  children:
  - System.Activities.WorkflowApplicationInstance.Abandon
  - System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  - System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  - System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  - System.Activities.WorkflowApplicationInstance.InstanceId
  - System.Activities.WorkflowApplicationInstance.InstanceStore
  langs:
  - csharp
  name: WorkflowApplicationInstance
  nameWithType: WorkflowApplicationInstance
  fullName: System.Activities.WorkflowApplicationInstance
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class WorkflowApplicationInstance
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  id: Abandon
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Abandon ();
    parameters: []
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  id: Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Abandon (TimeSpan timeout);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: To be added.
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  id: BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public IAsyncResult BeginAbandon (AsyncCallback callback, object state);
    parameters:
    - id: callback
      type: System.AsyncCallback
      description: To be added.
    - id: state
      type: System.Object
      description: To be added.
    return:
      type: System.IAsyncResult
      description: To be added.
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  id: BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public IAsyncResult BeginAbandon (TimeSpan timeout, AsyncCallback callback, object state);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: To be added.
    - id: callback
      type: System.AsyncCallback
      description: To be added.
    - id: state
      type: System.Object
      description: To be added.
    return:
      type: System.IAsyncResult
      description: To be added.
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  id: CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool CanApplyUpdate (System.Activities.DynamicUpdate.DynamicUpdateMap updateMap, out System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate> activitiesBlockingUpdate);
    parameters:
    - id: updateMap
      type: System.Activities.DynamicUpdate.DynamicUpdateMap
      description: To be added.
    - id: activitiesBlockingUpdate
      type: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  id: DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Activities.WorkflowIdentity DefinitionIdentity { get; }
    return:
      type: System.Activities.WorkflowIdentity
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  id: EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void EndAbandon (IAsyncResult asyncResult);
    parameters:
    - id: asyncResult
      type: System.IAsyncResult
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  id: InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Runtime.DurableInstancing.InstanceStore InstanceStore { get; }
    return:
      type: System.Runtime.DurableInstancing.InstanceStore
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
- uid: System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
- uid: System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.DynamicUpdate.DynamicUpdateMap
  parent: System.Activities.DynamicUpdate
  isExternal: false
  name: DynamicUpdateMap
  nameWithType: DynamicUpdateMap
  fullName: System.Activities.DynamicUpdate.DynamicUpdateMap
- uid: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<ActivityBlockingUpdate>
  nameWithType: IList<ActivityBlockingUpdate>
  fullName: System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate>
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
- uid: System.Activities.WorkflowIdentity
  parent: System.Activities
  isExternal: false
  name: WorkflowIdentity
  nameWithType: WorkflowIdentity
  fullName: System.Activities.WorkflowIdentity
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
- uid: System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
- uid: System.Runtime.DurableInstancing.InstanceStore
  parent: System.Runtime.DurableInstancing
  isExternal: false
  name: InstanceStore
  nameWithType: InstanceStore
  fullName: System.Runtime.DurableInstancing.InstanceStore
- uid: System.Activities.WorkflowApplicationInstance.Abandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon
  nameWithType: WorkflowApplicationInstance.Abandon
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon
  nameWithType: WorkflowApplicationInstance.BeginAbandon
