### YamlMime:ManagedReference
items:
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  id: CodeActivityPublicEnvironmentAccessor
  children:
  - System.Activities.CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  - System.Activities.CodeActivityPublicEnvironmentAccessor.Create(System.Activities.CodeActivityMetadata)
  - System.Activities.CodeActivityPublicEnvironmentAccessor.Equals(System.Object)
  - System.Activities.CodeActivityPublicEnvironmentAccessor.GetHashCode
  - System.Activities.CodeActivityPublicEnvironmentAccessor.op_Equality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  - System.Activities.CodeActivityPublicEnvironmentAccessor.op_Inequality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  - System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(System.Activities.LocationReference,System.Activities.ArgumentDirection,System.Activities.LocationReference@)
  - System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(System.Activities.LocationReference,System.Activities.LocationReference@)
  langs:
  - csharp
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
  type: Struct
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public struct CodeActivityPublicEnvironmentAccessor
  inheritance:
  - System.ValueType
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  id: ActivityMetadata
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: ActivityMetadata
  nameWithType: CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Activities.CodeActivityMetadata ActivityMetadata { get; }
    return:
      type: System.Activities.CodeActivityMetadata
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.Create(System.Activities.CodeActivityMetadata)
  id: Create(System.Activities.CodeActivityMetadata)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: Create(CodeActivityMetadata)
  nameWithType: CodeActivityPublicEnvironmentAccessor.Create(CodeActivityMetadata)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.Create(CodeActivityMetadata)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.Activities.CodeActivityPublicEnvironmentAccessor Create (System.Activities.CodeActivityMetadata metadata);
    parameters:
    - id: metadata
      type: System.Activities.CodeActivityMetadata
      description: To be added.
    return:
      type: System.Activities.CodeActivityPublicEnvironmentAccessor
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: CodeActivityPublicEnvironmentAccessor.Equals(Object)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.Equals(Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.GetHashCode
  id: GetHashCode
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: CodeActivityPublicEnvironmentAccessor.GetHashCode()
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.GetHashCode()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Equality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  id: op_Equality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  nameWithType: CodeActivityPublicEnvironmentAccessor.op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  type: Operator
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static bool op_Equality (System.Activities.CodeActivityPublicEnvironmentAccessor left, System.Activities.CodeActivityPublicEnvironmentAccessor right);
    parameters:
    - id: left
      type: System.Activities.CodeActivityPublicEnvironmentAccessor
      description: To be added.
    - id: right
      type: System.Activities.CodeActivityPublicEnvironmentAccessor
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Inequality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  id: op_Inequality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  nameWithType: CodeActivityPublicEnvironmentAccessor.op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  type: Operator
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static bool op_Inequality (System.Activities.CodeActivityPublicEnvironmentAccessor left, System.Activities.CodeActivityPublicEnvironmentAccessor right);
    parameters:
    - id: left
      type: System.Activities.CodeActivityPublicEnvironmentAccessor
      description: To be added.
    - id: right
      type: System.Activities.CodeActivityPublicEnvironmentAccessor
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(System.Activities.LocationReference,System.Activities.ArgumentDirection,System.Activities.LocationReference@)
  id: TryGetAccessToPublicLocation(System.Activities.LocationReference,System.Activities.ArgumentDirection,System.Activities.LocationReference@)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
  nameWithType: CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool TryGetAccessToPublicLocation (System.Activities.LocationReference publicLocation, System.Activities.ArgumentDirection accessDirection, out System.Activities.LocationReference equivalentLocation);
    parameters:
    - id: publicLocation
      type: System.Activities.LocationReference
      description: To be added.
    - id: accessDirection
      type: System.Activities.ArgumentDirection
      description: To be added.
    - id: equivalentLocation
      type: System.Activities.LocationReference
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(System.Activities.LocationReference,System.Activities.LocationReference@)
  id: TryGetReferenceToPublicLocation(System.Activities.LocationReference,System.Activities.LocationReference@)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  langs:
  - csharp
  name: TryGetReferenceToPublicLocation(LocationReference,LocationReference)
  nameWithType: CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(LocationReference,LocationReference)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(LocationReference,LocationReference)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool TryGetReferenceToPublicLocation (System.Activities.LocationReference publicReference, out System.Activities.LocationReference equivalentReference);
    parameters:
    - id: publicReference
      type: System.Activities.LocationReference
      description: To be added.
    - id: equivalentReference
      type: System.Activities.LocationReference
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: ActivityMetadata
  nameWithType: CodeActivityPublicEnvironmentAccessor.ActivityMetadata
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.ActivityMetadata
- uid: System.Activities.CodeActivityMetadata
  parent: System.Activities
  isExternal: false
  name: CodeActivityMetadata
  nameWithType: CodeActivityMetadata
  fullName: System.Activities.CodeActivityMetadata
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.Create(System.Activities.CodeActivityMetadata)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: Create(CodeActivityMetadata)
  nameWithType: CodeActivityPublicEnvironmentAccessor.Create(CodeActivityMetadata)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.Create(CodeActivityMetadata)
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  parent: System.Activities
  isExternal: false
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
- uid: System.Activities.CodeActivityMetadata
  parent: System.Activities
  isExternal: false
  name: CodeActivityMetadata
  nameWithType: CodeActivityMetadata
  fullName: System.Activities.CodeActivityMetadata
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.Equals(System.Object)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: Equals(Object)
  nameWithType: CodeActivityPublicEnvironmentAccessor.Equals(Object)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.GetHashCode
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: GetHashCode()
  nameWithType: CodeActivityPublicEnvironmentAccessor.GetHashCode()
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Equality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  nameWithType: CodeActivityPublicEnvironmentAccessor.op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Equality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  parent: System.Activities
  isExternal: false
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  parent: System.Activities
  isExternal: false
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Inequality(System.Activities.CodeActivityPublicEnvironmentAccessor,System.Activities.CodeActivityPublicEnvironmentAccessor)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  nameWithType: CodeActivityPublicEnvironmentAccessor.op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.op_Inequality(CodeActivityPublicEnvironmentAccessor,CodeActivityPublicEnvironmentAccessor)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  parent: System.Activities
  isExternal: false
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor
  parent: System.Activities
  isExternal: false
  name: CodeActivityPublicEnvironmentAccessor
  nameWithType: CodeActivityPublicEnvironmentAccessor
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(System.Activities.LocationReference,System.Activities.ArgumentDirection,System.Activities.LocationReference@)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
  nameWithType: CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetAccessToPublicLocation(LocationReference,ArgumentDirection,LocationReference)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.ArgumentDirection
  parent: System.Activities
  isExternal: false
  name: ArgumentDirection
  nameWithType: ArgumentDirection
  fullName: System.Activities.ArgumentDirection
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(System.Activities.LocationReference,System.Activities.LocationReference@)
  parent: System.Activities.CodeActivityPublicEnvironmentAccessor
  isExternal: false
  name: TryGetReferenceToPublicLocation(LocationReference,LocationReference)
  nameWithType: CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(LocationReference,LocationReference)
  fullName: System.Activities.CodeActivityPublicEnvironmentAccessor.TryGetReferenceToPublicLocation(LocationReference,LocationReference)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
