### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationException
  id: WorkflowApplicationException
  children:
  - System.Activities.WorkflowApplicationException.#ctor
  - System.Activities.WorkflowApplicationException.#ctor(System.String)
  - System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  langs:
  - csharp
  name: WorkflowApplicationException
  nameWithType: WorkflowApplicationException
  fullName: System.Activities.WorkflowApplicationException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class WorkflowApplicationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException()
  nameWithType: WorkflowApplicationException.WorkflowApplicationException()
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected WorkflowApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Guid)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: instanceId
      type: System.Guid
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Guid,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public WorkflowApplicationException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: instanceId
      type: System.Guid
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationException.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationException.InstanceId
  fullName: System.Activities.WorkflowApplicationException.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Activities.WorkflowApplicationException.#ctor
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException()
  nameWithType: WorkflowApplicationException.WorkflowApplicationException()
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException()
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Guid)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Guid,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationException.InstanceId
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationException.InstanceId
  fullName: System.Activities.WorkflowApplicationException.InstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
