### YamlMime:ManagedReference
items:
- uid: System.Runtime.InteropServices.RuntimeEnvironment
  id: RuntimeEnvironment
  children:
  - System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  - System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  - System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  langs:
  - csharp
  name: RuntimeEnvironment
  nameWithType: RuntimeEnvironment
  fullName: System.Runtime.InteropServices.RuntimeEnvironment
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RuntimeEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: RuntimeEnvironment()
  nameWithType: RuntimeEnvironment.RuntimeEnvironment()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.RuntimeEnvironment()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public RuntimeEnvironment ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  id: FromGlobalAccessCache(System.Reflection.Assembly)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: FromGlobalAccessCache(Assembly)
  nameWithType: RuntimeEnvironment.FromGlobalAccessCache(Assembly)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(Assembly)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static bool FromGlobalAccessCache (System.Reflection.Assembly a);
    parameters:
    - id: a
      type: System.Reflection.Assembly
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  id: GetRuntimeDirectory
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: GetRuntimeDirectory()
  nameWithType: RuntimeEnvironment.GetRuntimeDirectory()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static string GetRuntimeDirectory ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  id: GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: GetRuntimeInterfaceAsIntPtr(Guid,Guid)
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(Guid,Guid)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(Guid,Guid)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static IntPtr GetRuntimeInterfaceAsIntPtr (Guid clsid, Guid riid);
    parameters:
    - id: clsid
      type: System.Guid
      description: To be added.
    - id: riid
      type: System.Guid
      description: To be added.
    return:
      type: System.IntPtr
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  id: GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: GetRuntimeInterfaceAsObject(Guid,Guid)
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid,Guid)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid,Guid)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static object GetRuntimeInterfaceAsObject (Guid clsid, Guid riid);
    parameters:
    - id: clsid
      type: System.Guid
      description: To be added.
    - id: riid
      type: System.Guid
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  id: GetSystemVersion
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: GetSystemVersion()
  nameWithType: RuntimeEnvironment.GetSystemVersion()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static string GetSystemVersion ();
    parameters: []
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  id: SystemConfigurationFile
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  name: SystemConfigurationFile
  nameWithType: RuntimeEnvironment.SystemConfigurationFile
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static string SystemConfigurationFile { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: RuntimeEnvironment()
  nameWithType: RuntimeEnvironment.RuntimeEnvironment()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.RuntimeEnvironment()
- uid: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: FromGlobalAccessCache(Assembly)
  nameWithType: RuntimeEnvironment.FromGlobalAccessCache(Assembly)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(Assembly)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeDirectory()
  nameWithType: RuntimeEnvironment.GetRuntimeDirectory()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeInterfaceAsIntPtr(Guid,Guid)
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(Guid,Guid)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(Guid,Guid)
- uid: System.IntPtr
  parent: System
  isExternal: true
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeInterfaceAsObject(Guid,Guid)
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid,Guid)
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid,Guid)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetSystemVersion()
  nameWithType: RuntimeEnvironment.GetSystemVersion()
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: SystemConfigurationFile
  nameWithType: RuntimeEnvironment.SystemConfigurationFile
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
