### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.SettingsSection
  id: SettingsSection
  children:
  - System.Net.Configuration.SettingsSection.#ctor
  - System.Net.Configuration.SettingsSection.HttpListener
  - System.Net.Configuration.SettingsSection.HttpWebRequest
  - System.Net.Configuration.SettingsSection.Ipv6
  - System.Net.Configuration.SettingsSection.PerformanceCounters
  - System.Net.Configuration.SettingsSection.Properties
  - System.Net.Configuration.SettingsSection.ServicePointManager
  - System.Net.Configuration.SettingsSection.Socket
  - System.Net.Configuration.SettingsSection.WebProxyScript
  - System.Net.Configuration.SettingsSection.WebUtility
  langs:
  - csharp
  name: SettingsSection
  nameWithType: SettingsSection
  fullName: System.Net.Configuration.SettingsSection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class SettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: SettingsSection()
  nameWithType: SettingsSection.SettingsSection()
  fullName: System.Net.Configuration.SettingsSection.SettingsSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public SettingsSection ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.HttpListener
  id: HttpListener
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: HttpListener
  nameWithType: SettingsSection.HttpListener
  fullName: System.Net.Configuration.SettingsSection.HttpListener
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.HttpListenerElement HttpListener { get; }
    return:
      type: System.Net.Configuration.HttpListenerElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.HttpWebRequest
  id: HttpWebRequest
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: HttpWebRequest
  nameWithType: SettingsSection.HttpWebRequest
  fullName: System.Net.Configuration.SettingsSection.HttpWebRequest
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.HttpWebRequestElement HttpWebRequest { get; }
    return:
      type: System.Net.Configuration.HttpWebRequestElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.Ipv6
  id: Ipv6
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: Ipv6
  nameWithType: SettingsSection.Ipv6
  fullName: System.Net.Configuration.SettingsSection.Ipv6
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.Ipv6Element Ipv6 { get; }
    return:
      type: System.Net.Configuration.Ipv6Element
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.PerformanceCounters
  id: PerformanceCounters
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: PerformanceCounters
  nameWithType: SettingsSection.PerformanceCounters
  fullName: System.Net.Configuration.SettingsSection.PerformanceCounters
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.PerformanceCountersElement PerformanceCounters { get; }
    return:
      type: System.Net.Configuration.PerformanceCountersElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.Properties
  id: Properties
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: SettingsSection.Properties
  fullName: System.Net.Configuration.SettingsSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.ServicePointManager
  id: ServicePointManager
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: ServicePointManager
  nameWithType: SettingsSection.ServicePointManager
  fullName: System.Net.Configuration.SettingsSection.ServicePointManager
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.ServicePointManagerElement ServicePointManager { get; }
    return:
      type: System.Net.Configuration.ServicePointManagerElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.Socket
  id: Socket
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: Socket
  nameWithType: SettingsSection.Socket
  fullName: System.Net.Configuration.SettingsSection.Socket
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.SocketElement Socket { get; }
    return:
      type: System.Net.Configuration.SocketElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.WebProxyScript
  id: WebProxyScript
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: WebProxyScript
  nameWithType: SettingsSection.WebProxyScript
  fullName: System.Net.Configuration.SettingsSection.WebProxyScript
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.WebProxyScriptElement WebProxyScript { get; }
    return:
      type: System.Net.Configuration.WebProxyScriptElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.SettingsSection.WebUtility
  id: WebUtility
  parent: System.Net.Configuration.SettingsSection
  langs:
  - csharp
  name: WebUtility
  nameWithType: SettingsSection.WebUtility
  fullName: System.Net.Configuration.SettingsSection.WebUtility
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.WebUtilityElement WebUtility { get; }
    return:
      type: System.Net.Configuration.WebUtilityElement
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.SettingsSection.#ctor
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: SettingsSection()
  nameWithType: SettingsSection.SettingsSection()
  fullName: System.Net.Configuration.SettingsSection.SettingsSection()
- uid: System.Net.Configuration.SettingsSection.HttpListener
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: HttpListener
  nameWithType: SettingsSection.HttpListener
  fullName: System.Net.Configuration.SettingsSection.HttpListener
- uid: System.Net.Configuration.HttpListenerElement
  parent: System.Net.Configuration
  isExternal: false
  name: HttpListenerElement
  nameWithType: HttpListenerElement
  fullName: System.Net.Configuration.HttpListenerElement
- uid: System.Net.Configuration.SettingsSection.HttpWebRequest
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: HttpWebRequest
  nameWithType: SettingsSection.HttpWebRequest
  fullName: System.Net.Configuration.SettingsSection.HttpWebRequest
- uid: System.Net.Configuration.HttpWebRequestElement
  parent: System.Net.Configuration
  isExternal: false
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement
  fullName: System.Net.Configuration.HttpWebRequestElement
- uid: System.Net.Configuration.SettingsSection.Ipv6
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: Ipv6
  nameWithType: SettingsSection.Ipv6
  fullName: System.Net.Configuration.SettingsSection.Ipv6
- uid: System.Net.Configuration.Ipv6Element
  parent: System.Net.Configuration
  isExternal: false
  name: Ipv6Element
  nameWithType: Ipv6Element
  fullName: System.Net.Configuration.Ipv6Element
- uid: System.Net.Configuration.SettingsSection.PerformanceCounters
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: PerformanceCounters
  nameWithType: SettingsSection.PerformanceCounters
  fullName: System.Net.Configuration.SettingsSection.PerformanceCounters
- uid: System.Net.Configuration.PerformanceCountersElement
  parent: System.Net.Configuration
  isExternal: false
  name: PerformanceCountersElement
  nameWithType: PerformanceCountersElement
  fullName: System.Net.Configuration.PerformanceCountersElement
- uid: System.Net.Configuration.SettingsSection.Properties
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: Properties
  nameWithType: SettingsSection.Properties
  fullName: System.Net.Configuration.SettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.SettingsSection.ServicePointManager
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: ServicePointManager
  nameWithType: SettingsSection.ServicePointManager
  fullName: System.Net.Configuration.SettingsSection.ServicePointManager
- uid: System.Net.Configuration.ServicePointManagerElement
  parent: System.Net.Configuration
  isExternal: false
  name: ServicePointManagerElement
  nameWithType: ServicePointManagerElement
  fullName: System.Net.Configuration.ServicePointManagerElement
- uid: System.Net.Configuration.SettingsSection.Socket
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: Socket
  nameWithType: SettingsSection.Socket
  fullName: System.Net.Configuration.SettingsSection.Socket
- uid: System.Net.Configuration.SocketElement
  parent: System.Net.Configuration
  isExternal: false
  name: SocketElement
  nameWithType: SocketElement
  fullName: System.Net.Configuration.SocketElement
- uid: System.Net.Configuration.SettingsSection.WebProxyScript
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: WebProxyScript
  nameWithType: SettingsSection.WebProxyScript
  fullName: System.Net.Configuration.SettingsSection.WebProxyScript
- uid: System.Net.Configuration.WebProxyScriptElement
  parent: System.Net.Configuration
  isExternal: false
  name: WebProxyScriptElement
  nameWithType: WebProxyScriptElement
  fullName: System.Net.Configuration.WebProxyScriptElement
- uid: System.Net.Configuration.SettingsSection.WebUtility
  parent: System.Net.Configuration.SettingsSection
  isExternal: false
  name: WebUtility
  nameWithType: SettingsSection.WebUtility
  fullName: System.Net.Configuration.SettingsSection.WebUtility
- uid: System.Net.Configuration.WebUtilityElement
  parent: System.Net.Configuration
  isExternal: false
  name: WebUtilityElement
  nameWithType: WebUtilityElement
  fullName: System.Net.Configuration.WebUtilityElement
