### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ProxyElement
  id: ProxyElement
  children:
  - System.Net.Configuration.ProxyElement.#ctor
  - System.Net.Configuration.ProxyElement.AutoDetect
  - System.Net.Configuration.ProxyElement.BypassOnLocal
  - System.Net.Configuration.ProxyElement.Properties
  - System.Net.Configuration.ProxyElement.ProxyAddress
  - System.Net.Configuration.ProxyElement.ScriptLocation
  - System.Net.Configuration.ProxyElement.UseSystemDefault
  langs:
  - csharp
  name: ProxyElement
  nameWithType: ProxyElement
  fullName: System.Net.Configuration.ProxyElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ProxyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProxyElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  id: AutoDetect
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.ProxyElement.AutoDetectValues AutoDetect { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.AutoDetectValues
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  id: BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.ProxyElement.BypassOnLocalValues BypassOnLocal { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.Properties
  id: Properties
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  id: ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Uri ProxyAddress { get; set; }
    return:
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  id: ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Uri ScriptLocation { get; set; }
    return:
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  id: UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Net.Configuration.ProxyElement.UseSystemDefaultValues UseSystemDefault { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ProxyElement.#ctor
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
- uid: System.Net.Configuration.ProxyElement.AutoDetectValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+AutoDetectValues
  nameWithType: ProxyElement+AutoDetectValues
  fullName: System.Net.Configuration.ProxyElement+AutoDetectValues
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+BypassOnLocalValues
  nameWithType: ProxyElement+BypassOnLocalValues
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues
- uid: System.Net.Configuration.ProxyElement.Properties
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
- uid: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+UseSystemDefaultValues
  nameWithType: ProxyElement+UseSystemDefaultValues
  fullName: System.Net.Configuration.ProxyElement+UseSystemDefaultValues
