### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.AuthenticationModuleElement
  id: AuthenticationModuleElement
  children:
  - System.Net.Configuration.AuthenticationModuleElement.#ctor
  - System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  - System.Net.Configuration.AuthenticationModuleElement.Properties
  - System.Net.Configuration.AuthenticationModuleElement.Type
  langs:
  - csharp
  name: AuthenticationModuleElement
  nameWithType: AuthenticationModuleElement
  fullName: System.Net.Configuration.AuthenticationModuleElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class AuthenticationModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: AuthenticationModuleElement()
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement()
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public AuthenticationModuleElement ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: AuthenticationModuleElement(String)
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement(String)
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public AuthenticationModuleElement (string typeName);
    parameters:
    - id: typeName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: AuthenticationModuleElement.Properties
  fullName: System.Net.Configuration.AuthenticationModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.Type
  id: Type
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: AuthenticationModuleElement.Type
  fullName: System.Net.Configuration.AuthenticationModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: AuthenticationModuleElement()
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement()
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement()
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: AuthenticationModuleElement(String)
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement(String)
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.AuthenticationModuleElement.Properties
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Properties
  nameWithType: AuthenticationModuleElement.Properties
  fullName: System.Net.Configuration.AuthenticationModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.AuthenticationModuleElement.Type
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Type
  nameWithType: AuthenticationModuleElement.Type
  fullName: System.Net.Configuration.AuthenticationModuleElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
