### YamlMime:ManagedReference
items:
- uid: System.Web.UnvalidatedRequestValuesBase
  id: UnvalidatedRequestValuesBase
  children:
  - System.Web.UnvalidatedRequestValuesBase.#ctor
  - System.Web.UnvalidatedRequestValuesBase.Cookies
  - System.Web.UnvalidatedRequestValuesBase.Files
  - System.Web.UnvalidatedRequestValuesBase.Form
  - System.Web.UnvalidatedRequestValuesBase.Headers
  - System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  - System.Web.UnvalidatedRequestValuesBase.Path
  - System.Web.UnvalidatedRequestValuesBase.PathInfo
  - System.Web.UnvalidatedRequestValuesBase.QueryString
  - System.Web.UnvalidatedRequestValuesBase.RawUrl
  - System.Web.UnvalidatedRequestValuesBase.Url
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase
  nameWithType: UnvalidatedRequestValuesBase
  fullName: System.Web.UnvalidatedRequestValuesBase
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public abstract class UnvalidatedRequestValuesBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  id: '#ctor'
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected UnvalidatedRequestValuesBase ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  id: Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual System.Web.HttpCookieCollection Cookies { get; }
    return:
      type: System.Web.HttpCookieCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  id: Files
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual System.Web.HttpFileCollectionBase Files { get; }
    return:
      type: System.Web.HttpFileCollectionBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  id: Form
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Form { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  id: Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Headers { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual string this[string field] { get; }
    parameters:
    - id: field
      type: System.String
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  id: Path
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual string Path { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  id: PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual string PathInfo { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  id: QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection QueryString { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  id: RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual string RawUrl { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  id: Url
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual Uri Url { get; }
    return:
      type: System.Uri
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
- uid: System.Web.HttpCookieCollection
  parent: System.Web
  isExternal: false
  name: HttpCookieCollection
  nameWithType: HttpCookieCollection
  fullName: System.Web.HttpCookieCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
- uid: System.Web.HttpFileCollectionBase
  parent: System.Web
  isExternal: true
  name: HttpFileCollectionBase
  nameWithType: HttpFileCollectionBase
  fullName: System.Web.HttpFileCollectionBase
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
