### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
