### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer
  id: ArgumentValueSerializer
  children:
  - System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  - System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: ArgumentValueSerializer
  nameWithType: ArgumentValueSerializer
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ArgumentValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: ArgumentValueSerializer()
  nameWithType: ArgumentValueSerializer.ArgumentValueSerializer()
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ArgumentValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ArgumentValueSerializer ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ArgumentValueSerializer()
  nameWithType: ArgumentValueSerializer.ArgumentValueSerializer()
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ArgumentValueSerializer()
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
