### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventArgs
  id: InstallEventArgs
  children:
  - System.Configuration.Install.InstallEventArgs.#ctor
  - System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  - System.Configuration.Install.InstallEventArgs.SavedState
  langs:
  - csharp
  name: InstallEventArgs
  nameWithType: InstallEventArgs
  fullName: System.Configuration.Install.InstallEventArgs
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class InstallEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: InstallEventArgs()
  nameWithType: InstallEventArgs.InstallEventArgs()
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InstallEventArgs ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  id: '#ctor(System.Collections.IDictionary)'
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: InstallEventArgs(IDictionary)
  nameWithType: InstallEventArgs.InstallEventArgs(IDictionary)
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs(IDictionary)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InstallEventArgs (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.SavedState
  id: SavedState
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: SavedState
  nameWithType: InstallEventArgs.SavedState
  fullName: System.Configuration.Install.InstallEventArgs.SavedState
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.IDictionary SavedState { get; }
    return:
      type: System.Collections.IDictionary
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.Install.InstallEventArgs.#ctor
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: InstallEventArgs()
  nameWithType: InstallEventArgs.InstallEventArgs()
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs()
- uid: System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: InstallEventArgs(IDictionary)
  nameWithType: InstallEventArgs.InstallEventArgs(IDictionary)
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs(IDictionary)
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.InstallEventArgs.SavedState
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: SavedState
  nameWithType: InstallEventArgs.SavedState
  fullName: System.Configuration.Install.InstallEventArgs.SavedState
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
