### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.TransactedInstaller
  id: TransactedInstaller
  children:
  - System.Configuration.Install.TransactedInstaller.#ctor
  - System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  - System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  langs:
  - csharp
  name: TransactedInstaller
  nameWithType: TransactedInstaller
  fullName: System.Configuration.Install.TransactedInstaller
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class TransactedInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.Object
  - System.MarshalByRefObject
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  implements: []
  inheritedMembers:
  - System.ComponentModel.Component.CanRaiseEvents
  - System.ComponentModel.Component.Container
  - System.ComponentModel.Component.DesignMode
  - System.ComponentModel.Component.Dispose
  - System.ComponentModel.Component.Dispose(System.Boolean)
  - System.ComponentModel.Component.Disposed
  - System.ComponentModel.Component.Events
  - System.ComponentModel.Component.GetService(System.Type)
  - System.ComponentModel.Component.Site
  - System.ComponentModel.Component.ToString
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.HelpText
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
  - System.Configuration.Install.Installer.Rollback(System.Collections.IDictionary)
  - System.MarshalByRefObject.CreateObjRef(System.Type)
  - System.MarshalByRefObject.GetLifetimeService
  - System.MarshalByRefObject.InitializeLifetimeService
  - System.MarshalByRefObject.MemberwiseClone(System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.TransactedInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  name: TransactedInstaller()
  nameWithType: TransactedInstaller.TransactedInstaller()
  fullName: System.Configuration.Install.TransactedInstaller.TransactedInstaller()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public TransactedInstaller ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  id: Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  name: Install(IDictionary)
  nameWithType: TransactedInstaller.Install(IDictionary)
  fullName: System.Configuration.Install.TransactedInstaller.Install(IDictionary)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void Install (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  id: Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  name: Uninstall(IDictionary)
  nameWithType: TransactedInstaller.Uninstall(IDictionary)
  fullName: System.Configuration.Install.TransactedInstaller.Uninstall(IDictionary)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void Uninstall (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Install.Installer
  isExternal: false
  name: System.Configuration.Install.Installer
- uid: System.Configuration.Install.TransactedInstaller.#ctor
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: TransactedInstaller()
  nameWithType: TransactedInstaller.TransactedInstaller()
  fullName: System.Configuration.Install.TransactedInstaller.TransactedInstaller()
- uid: System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: Install(IDictionary)
  nameWithType: TransactedInstaller.Install(IDictionary)
  fullName: System.Configuration.Install.TransactedInstaller.Install(IDictionary)
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: Uninstall(IDictionary)
  nameWithType: TransactedInstaller.Uninstall(IDictionary)
  fullName: System.Configuration.Install.TransactedInstaller.Uninstall(IDictionary)
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
