### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: InstallEventHandler
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
