### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.ManagedInstallerClass
  id: ManagedInstallerClass
  children:
  - System.Configuration.Install.ManagedInstallerClass.#ctor
  - System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  - System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  langs:
  - csharp
  name: ManagedInstallerClass
  nameWithType: ManagedInstallerClass
  fullName: System.Configuration.Install.ManagedInstallerClass
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("42EB0342-0393-448f-84AA-D4BEB0283595")]

      public class ManagedInstallerClass : System.Configuration.Install.IManagedInstaller
  inheritance:
  - System.Object
  implements:
  - System.Configuration.Install.IManagedInstaller
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: ManagedInstallerClass()
  nameWithType: ManagedInstallerClass.ManagedInstallerClass()
  fullName: System.Configuration.Install.ManagedInstallerClass.ManagedInstallerClass()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ManagedInstallerClass ();
    parameters: []
  overload: System.Configuration.Install.ManagedInstallerClass.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  id: InstallHelper(System.String[])
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: InstallHelper(String[])
  nameWithType: ManagedInstallerClass.InstallHelper(String[])
  fullName: System.Configuration.Install.ManagedInstallerClass.InstallHelper(String[])
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static void InstallHelper (string[] args);
    parameters:
    - id: args
      type: System.String[]
      description: To be added.
  overload: System.Configuration.Install.ManagedInstallerClass.InstallHelper*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  id: System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  isEii: true
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: int IManagedInstaller.ManagedInstall (string argString, int hInstall);
    parameters:
    - id: argString
      type: System.String
      description: To be added.
    - id: hInstall
      type: System.Int32
      description: To be added.
    return:
      type: System.Int32
      description: To be added.
  overload: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: ManagedInstallerClass()
  nameWithType: ManagedInstallerClass.ManagedInstallerClass()
  fullName: System.Configuration.Install.ManagedInstallerClass.ManagedInstallerClass()
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: InstallHelper(String[])
  nameWithType: ManagedInstallerClass.InstallHelper(String[])
  fullName: System.Configuration.Install.ManagedInstallerClass.InstallHelper(String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: ManagedInstallerClass
  nameWithType: ManagedInstallerClass.ManagedInstallerClass
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: InstallHelper
  nameWithType: ManagedInstallerClass.InstallHelper
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall
