### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.IManagedInstaller
  id: IManagedInstaller
  children:
  - System.Configuration.Install.IManagedInstaller.ManagedInstall(System.String,System.Int32)
  langs:
  - csharp
  name: IManagedInstaller
  nameWithType: IManagedInstaller
  fullName: System.Configuration.Install.IManagedInstaller
  type: Interface
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("1E233FE7-C16D-4512-8C3B-2E9988F08D38")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IManagedInstaller
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.IManagedInstaller.ManagedInstall(System.String,System.Int32)
  id: ManagedInstall(System.String,System.Int32)
  parent: System.Configuration.Install.IManagedInstaller
  langs:
  - csharp
  name: ManagedInstall(String,Int32)
  nameWithType: IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int ManagedInstall (string commandLine, int hInstall);
    parameters:
    - id: commandLine
      type: System.String
      description: To be added.
    - id: hInstall
      type: System.Int32
      description: To be added.
    return:
      type: System.Int32
      description: To be added.
  overload: System.Configuration.Install.IManagedInstaller.ManagedInstall*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Install.IManagedInstaller.ManagedInstall(System.String,System.Int32)
  parent: System.Configuration.Install.IManagedInstaller
  isExternal: false
  name: ManagedInstall(String,Int32)
  nameWithType: IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Install.IManagedInstaller.ManagedInstall*
  parent: System.Configuration.Install.IManagedInstaller
  isExternal: false
  name: ManagedInstall
  nameWithType: IManagedInstaller.ManagedInstall
