### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.UninstallAction
  id: UninstallAction
  children:
  - System.Configuration.Install.UninstallAction.NoAction
  - System.Configuration.Install.UninstallAction.Remove
  langs:
  - csharp
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum UninstallAction
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.UninstallAction.NoAction
  id: NoAction
  parent: System.Configuration.Install.UninstallAction
  langs:
  - csharp
  name: NoAction
  nameWithType: UninstallAction.NoAction
  fullName: System.Configuration.Install.UninstallAction.NoAction
  type: Field
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  syntax:
    content: NoAction
    return:
      type: System.Configuration.Install.UninstallAction
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.UninstallAction.Remove
  id: Remove
  parent: System.Configuration.Install.UninstallAction
  langs:
  - csharp
  name: Remove
  nameWithType: UninstallAction.Remove
  fullName: System.Configuration.Install.UninstallAction.Remove
  type: Field
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  syntax:
    content: Remove
    return:
      type: System.Configuration.Install.UninstallAction
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Install.UninstallAction.NoAction
  parent: System.Configuration.Install.UninstallAction
  isExternal: false
  name: NoAction
  nameWithType: UninstallAction.NoAction
  fullName: System.Configuration.Install.UninstallAction.NoAction
- uid: System.Configuration.Install.UninstallAction
  parent: System.Configuration.Install
  isExternal: false
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
- uid: System.Configuration.Install.UninstallAction.Remove
  parent: System.Configuration.Install.UninstallAction
  isExternal: false
  name: Remove
  nameWithType: UninstallAction.Remove
  fullName: System.Configuration.Install.UninstallAction.Remove
- uid: System.Configuration.Install.UninstallAction
  parent: System.Configuration.Install
  isExternal: false
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
