### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.ComponentInstaller
  id: ComponentInstaller
  children:
  - System.Configuration.Install.ComponentInstaller.#ctor
  - System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  - System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  langs:
  - csharp
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public abstract class ComponentInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.Object
  - System.MarshalByRefObject
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  implements: []
  inheritedMembers:
  - System.ComponentModel.Component.CanRaiseEvents
  - System.ComponentModel.Component.Container
  - System.ComponentModel.Component.DesignMode
  - System.ComponentModel.Component.Dispose
  - System.ComponentModel.Component.Dispose(System.Boolean)
  - System.ComponentModel.Component.Disposed
  - System.ComponentModel.Component.Events
  - System.ComponentModel.Component.GetService(System.Type)
  - System.ComponentModel.Component.Site
  - System.ComponentModel.Component.ToString
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.HelpText
  - System.Configuration.Install.Installer.Install(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
  - System.Configuration.Install.Installer.Rollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Uninstall(System.Collections.IDictionary)
  - System.MarshalByRefObject.CreateObjRef(System.Type)
  - System.MarshalByRefObject.GetLifetimeService
  - System.MarshalByRefObject.InitializeLifetimeService
  - System.MarshalByRefObject.MemberwiseClone(System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected ComponentInstaller ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  id: CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public abstract void CopyFromComponent (System.ComponentModel.IComponent component);
    parameters:
    - id: component
      type: System.ComponentModel.IComponent
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  id: IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual bool IsEquivalentInstaller (System.Configuration.Install.ComponentInstaller otherInstaller);
    parameters:
    - id: otherInstaller
      type: System.Configuration.Install.ComponentInstaller
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Install.Installer
  isExternal: false
  name: System.Configuration.Install.Installer
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
- uid: System.ComponentModel.IComponent
  parent: System.ComponentModel
  isExternal: false
  name: IComponent
  nameWithType: IComponent
  fullName: System.ComponentModel.IComponent
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Install.ComponentInstaller
  parent: System.Configuration.Install
  isExternal: false
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
