### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallException
  id: InstallException
  children:
  - System.Configuration.Install.InstallException.#ctor
  - System.Configuration.Install.InstallException.#ctor(System.String)
  - System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InstallException
  nameWithType: InstallException
  fullName: System.Configuration.Install.InstallException
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class InstallException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallException.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: System.Configuration.Install.InstallException.InstallException()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InstallException ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: System.Configuration.Install.InstallException.InstallException(String)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InstallException (string message);
    parameters:
    - id: message
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(SerializationInfo,StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Install.InstallException.InstallException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected InstallException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: To be added.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String,Exception)
  nameWithType: InstallException.InstallException(String,Exception)
  fullName: System.Configuration.Install.InstallException.InstallException(String,Exception)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public InstallException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: To be added.
    - id: innerException
      type: System.Exception
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Configuration.Install.InstallException.#ctor
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: System.Configuration.Install.InstallException.InstallException()
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: System.Configuration.Install.InstallException.InstallException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(SerializationInfo,StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Install.InstallException.InstallException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String,Exception)
  nameWithType: InstallException.InstallException(String,Exception)
  fullName: System.Configuration.Install.InstallException.InstallException(String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
