### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.KeyGestureValueSerializer
  id: KeyGestureValueSerializer
  children:
  - System.Windows.Input.KeyGestureValueSerializer.#ctor
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer
  fullName: System.Windows.Input.KeyGestureValueSerializer
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class KeyGestureValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public KeyGestureValueSerializer ();
    parameters: []
  overload: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: To be added.
    return:
      type: System.String
      description: To be added.
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: KeyGestureValueSerializer.CanConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: KeyGestureValueSerializer.CanConvertToString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: KeyGestureValueSerializer.ConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: KeyGestureValueSerializer.ConvertToString
