### YamlMime:ManagedReference
items:
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  id: PropertyValueSource
  children:
  - System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  langs:
  - csharp
  name: PropertyValueSource
  nameWithType: PropertyValueSource
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public abstract class PropertyValueSource
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  id: '#ctor'
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  langs:
  - csharp
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
  type: Constructor
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected PropertyValueSource ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
