### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationSection
  id: ProtectedConfigurationSection
  children:
  - System.Configuration.ProtectedConfigurationSection.#ctor
  - System.Configuration.ProtectedConfigurationSection.DefaultProvider
  - System.Configuration.ProtectedConfigurationSection.Properties
  - System.Configuration.ProtectedConfigurationSection.Providers
  langs:
  - csharp
  name: ProtectedConfigurationSection
  nameWithType: ProtectedConfigurationSection
  fullName: System.Configuration.ProtectedConfigurationSection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ProtectedConfigurationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: ProtectedConfigurationSection()
  nameWithType: ProtectedConfigurationSection.ProtectedConfigurationSection()
  fullName: System.Configuration.ProtectedConfigurationSection.ProtectedConfigurationSection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProtectedConfigurationSection ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationSection.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfigurationSection.DefaultProvider
  fullName: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ProtectedConfigurationSection.DefaultProvider*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.Properties
  id: Properties
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: Properties
  nameWithType: ProtectedConfigurationSection.Properties
  fullName: System.Configuration.ProtectedConfigurationSection.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.ProtectedConfigurationSection.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfigurationSection.Providers
  fullName: System.Configuration.ProtectedConfigurationSection.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: To be added.
  overload: System.Configuration.ProtectedConfigurationSection.Providers*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.ProtectedConfigurationSection.#ctor
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: ProtectedConfigurationSection()
  nameWithType: ProtectedConfigurationSection.ProtectedConfigurationSection()
  fullName: System.Configuration.ProtectedConfigurationSection.ProtectedConfigurationSection()
- uid: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfigurationSection.DefaultProvider
  fullName: System.Configuration.ProtectedConfigurationSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationSection.Properties
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Properties
  nameWithType: ProtectedConfigurationSection.Properties
  fullName: System.Configuration.ProtectedConfigurationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ProtectedConfigurationSection.Providers
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfigurationSection.Providers
  fullName: System.Configuration.ProtectedConfigurationSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Configuration.ProtectedConfigurationSection.#ctor*
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: ProtectedConfigurationSection
  nameWithType: ProtectedConfigurationSection.ProtectedConfigurationSection
- uid: System.Configuration.ProtectedConfigurationSection.DefaultProvider*
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfigurationSection.DefaultProvider
- uid: System.Configuration.ProtectedConfigurationSection.Properties*
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Properties
  nameWithType: ProtectedConfigurationSection.Properties
- uid: System.Configuration.ProtectedConfigurationSection.Providers*
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfigurationSection.Providers
