### YamlMime:ManagedReference
items:
- uid: System.Configuration.KeyValueConfigurationElement
  id: KeyValueConfigurationElement
  children:
  - System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  - System.Configuration.KeyValueConfigurationElement.Init
  - System.Configuration.KeyValueConfigurationElement.Key
  - System.Configuration.KeyValueConfigurationElement.Properties
  - System.Configuration.KeyValueConfigurationElement.Value
  langs:
  - csharp
  name: KeyValueConfigurationElement
  nameWithType: KeyValueConfigurationElement
  fullName: System.Configuration.KeyValueConfigurationElement
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class KeyValueConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: KeyValueConfigurationElement(String,String)
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  fullName: System.Configuration.KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public KeyValueConfigurationElement (string key, string value);
    parameters:
    - id: key
      type: System.String
      description: To be added.
    - id: value
      type: System.String
      description: To be added.
  overload: System.Configuration.KeyValueConfigurationElement.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.KeyValueConfigurationElement.Init
  id: Init
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Init()
  nameWithType: KeyValueConfigurationElement.Init()
  fullName: System.Configuration.KeyValueConfigurationElement.Init()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override void Init ();
    parameters: []
  overload: System.Configuration.KeyValueConfigurationElement.Init*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.KeyValueConfigurationElement.Key
  id: Key
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
  fullName: System.Configuration.KeyValueConfigurationElement.Key
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Key { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.KeyValueConfigurationElement.Key*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.KeyValueConfigurationElement.Properties
  id: Properties
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
  fullName: System.Configuration.KeyValueConfigurationElement.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.KeyValueConfigurationElement.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.KeyValueConfigurationElement.Value
  id: Value
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
  fullName: System.Configuration.KeyValueConfigurationElement.Value
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.KeyValueConfigurationElement.Value*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: KeyValueConfigurationElement(String,String)
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  fullName: System.Configuration.KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.KeyValueConfigurationElement.Init
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Init()
  nameWithType: KeyValueConfigurationElement.Init()
  fullName: System.Configuration.KeyValueConfigurationElement.Init()
- uid: System.Configuration.KeyValueConfigurationElement.Key
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
  fullName: System.Configuration.KeyValueConfigurationElement.Key
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.KeyValueConfigurationElement.Properties
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
  fullName: System.Configuration.KeyValueConfigurationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.KeyValueConfigurationElement.Value
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
  fullName: System.Configuration.KeyValueConfigurationElement.Value
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.KeyValueConfigurationElement.#ctor*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: KeyValueConfigurationElement
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement
- uid: System.Configuration.KeyValueConfigurationElement.Init*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Init
  nameWithType: KeyValueConfigurationElement.Init
- uid: System.Configuration.KeyValueConfigurationElement.Key*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
- uid: System.Configuration.KeyValueConfigurationElement.Properties*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
- uid: System.Configuration.KeyValueConfigurationElement.Value*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
