### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementCollectionType
  id: ConfigurationElementCollectionType
  children:
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  - System.Configuration.ConfigurationElementCollectionType.BasicMap
  - System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  langs:
  - csharp
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum ConfigurationElementCollectionType
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  id: AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: AddRemoveClearMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  id: AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: AddRemoveClearMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  id: BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: BasicMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  id: BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: BasicMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
