### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPermission
  id: ConfigurationPermission
  children:
  - System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  - System.Configuration.ConfigurationPermission.Copy
  - System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  - System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsUnrestricted
  - System.Configuration.ConfigurationPermission.ToXml
  - System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  langs:
  - csharp
  name: ConfigurationPermission
  nameWithType: ConfigurationPermission
  fullName: System.Configuration.ConfigurationPermission
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ConfigurationPermission : System.Security.CodeAccessPermission, System.Security.Permissions.IUnrestrictedPermission'
  inheritance:
  - System.Object
  - System.Security.CodeAccessPermission
  implements:
  - System.Security.Permissions.IUnrestrictedPermission
  inheritedMembers:
  - System.Security.CodeAccessPermission.Assert
  - System.Security.CodeAccessPermission.Demand
  - System.Security.CodeAccessPermission.Deny
  - System.Security.CodeAccessPermission.Equals(System.Object)
  - System.Security.CodeAccessPermission.GetHashCode
  - System.Security.CodeAccessPermission.PermitOnly
  - System.Security.CodeAccessPermission.RevertAll
  - System.Security.CodeAccessPermission.RevertAssert
  - System.Security.CodeAccessPermission.RevertDeny
  - System.Security.CodeAccessPermission.RevertPermitOnly
  - System.Security.CodeAccessPermission.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  id: '#ctor(System.Security.Permissions.PermissionState)'
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: ConfigurationPermission(PermissionState)
  nameWithType: ConfigurationPermission.ConfigurationPermission(PermissionState)
  fullName: System.Configuration.ConfigurationPermission.ConfigurationPermission(PermissionState)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConfigurationPermission (System.Security.Permissions.PermissionState state);
    parameters:
    - id: state
      type: System.Security.Permissions.PermissionState
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.Copy
  id: Copy
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Copy()
  nameWithType: ConfigurationPermission.Copy()
  fullName: System.Configuration.ConfigurationPermission.Copy()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.IPermission Copy ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.Copy*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: FromXml(SecurityElement)
  nameWithType: ConfigurationPermission.FromXml(SecurityElement)
  fullName: System.Configuration.ConfigurationPermission.FromXml(SecurityElement)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void FromXml (System.Security.SecurityElement securityElement);
    parameters:
    - id: securityElement
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.FromXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  id: Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Intersect(IPermission)
  nameWithType: ConfigurationPermission.Intersect(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Intersect(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.IPermission Intersect (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: To be added.
    return:
      type: System.Security.IPermission
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.Intersect*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  id: IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: IsSubsetOf(IPermission)
  nameWithType: ConfigurationPermission.IsSubsetOf(IPermission)
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool IsSubsetOf (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.IsSubsetOf*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  id: IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: IsUnrestricted()
  nameWithType: ConfigurationPermission.IsUnrestricted()
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsUnrestricted ();
    parameters: []
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.IsUnrestricted*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.ToXml
  id: ToXml
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: ToXml()
  nameWithType: ConfigurationPermission.ToXml()
  fullName: System.Configuration.ConfigurationPermission.ToXml()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.ToXml*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  id: Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Union(IPermission)
  nameWithType: ConfigurationPermission.Union(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Union(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Security.IPermission Union (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: To be added.
    return:
      type: System.Security.IPermission
      description: To be added.
  overload: System.Configuration.ConfigurationPermission.Union*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Security.CodeAccessPermission
  isExternal: false
  name: System.Security.CodeAccessPermission
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ConfigurationPermission(PermissionState)
  nameWithType: ConfigurationPermission.ConfigurationPermission(PermissionState)
  fullName: System.Configuration.ConfigurationPermission.ConfigurationPermission(PermissionState)
- uid: System.Security.Permissions.PermissionState
  parent: System.Security.Permissions
  isExternal: false
  name: PermissionState
  nameWithType: PermissionState
  fullName: System.Security.Permissions.PermissionState
- uid: System.Configuration.ConfigurationPermission.Copy
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Copy()
  nameWithType: ConfigurationPermission.Copy()
  fullName: System.Configuration.ConfigurationPermission.Copy()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: FromXml(SecurityElement)
  nameWithType: ConfigurationPermission.FromXml(SecurityElement)
  fullName: System.Configuration.ConfigurationPermission.FromXml(SecurityElement)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Intersect(IPermission)
  nameWithType: ConfigurationPermission.Intersect(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Intersect(IPermission)
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsSubsetOf(IPermission)
  nameWithType: ConfigurationPermission.IsSubsetOf(IPermission)
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf(IPermission)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsUnrestricted()
  nameWithType: ConfigurationPermission.IsUnrestricted()
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPermission.ToXml
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ToXml()
  nameWithType: ConfigurationPermission.ToXml()
  fullName: System.Configuration.ConfigurationPermission.ToXml()
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Union(IPermission)
  nameWithType: ConfigurationPermission.Union(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Union(IPermission)
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.#ctor*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ConfigurationPermission
  nameWithType: ConfigurationPermission.ConfigurationPermission
- uid: System.Configuration.ConfigurationPermission.Copy*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Copy
  nameWithType: ConfigurationPermission.Copy
- uid: System.Configuration.ConfigurationPermission.FromXml*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: FromXml
  nameWithType: ConfigurationPermission.FromXml
- uid: System.Configuration.ConfigurationPermission.Intersect*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Intersect
  nameWithType: ConfigurationPermission.Intersect
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsSubsetOf
  nameWithType: ConfigurationPermission.IsSubsetOf
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsUnrestricted
  nameWithType: ConfigurationPermission.IsUnrestricted
- uid: System.Configuration.ConfigurationPermission.ToXml*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ToXml
  nameWithType: ConfigurationPermission.ToXml
- uid: System.Configuration.ConfigurationPermission.Union*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Union
  nameWithType: ConfigurationPermission.Union
