### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationFileMap
  id: ConfigurationFileMap
  children:
  - System.Configuration.ConfigurationFileMap.#ctor
  - System.Configuration.ConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ConfigurationFileMap.Clone
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  langs:
  - csharp
  name: ConfigurationFileMap
  nameWithType: ConfigurationFileMap
  fullName: System.Configuration.ConfigurationFileMap
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ConfigurationFileMap : ICloneable'
  inheritance:
  - System.Object
  implements:
  - System.ICloneable
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: ConfigurationFileMap()
  nameWithType: ConfigurationFileMap.ConfigurationFileMap()
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConfigurationFileMap ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: ConfigurationFileMap(String)
  nameWithType: ConfigurationFileMap.ConfigurationFileMap(String)
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConfigurationFileMap (string machineConfigFilename);
    parameters:
    - id: machineConfigFilename
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: ConfigurationFileMap.Clone()
  fullName: System.Configuration.ConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual object Clone ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  id: MachineConfigFilename
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: MachineConfigFilename
  nameWithType: ConfigurationFileMap.MachineConfigFilename
  fullName: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string MachineConfigFilename { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationFileMap.#ctor
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: ConfigurationFileMap()
  nameWithType: ConfigurationFileMap.ConfigurationFileMap()
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap()
- uid: System.Configuration.ConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: ConfigurationFileMap(String)
  nameWithType: ConfigurationFileMap.ConfigurationFileMap(String)
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationFileMap.Clone
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: ConfigurationFileMap.Clone()
  fullName: System.Configuration.ConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: MachineConfigFilename
  nameWithType: ConfigurationFileMap.MachineConfigFilename
  fullName: System.Configuration.ConfigurationFileMap.MachineConfigFilename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
