### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProviderSettings
  id: ProviderSettings
  children:
  - System.Configuration.ProviderSettings.#ctor
  - System.Configuration.ProviderSettings.#ctor(System.String,System.String)
  - System.Configuration.ProviderSettings.IsModified
  - System.Configuration.ProviderSettings.Name
  - System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ProviderSettings.Parameters
  - System.Configuration.ProviderSettings.Properties
  - System.Configuration.ProviderSettings.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ProviderSettings.Type
  - System.Configuration.ProviderSettings.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  langs:
  - csharp
  name: ProviderSettings
  nameWithType: ProviderSettings
  fullName: System.Configuration.ProviderSettings
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ProviderSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.#ctor
  id: '#ctor'
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: ProviderSettings()
  nameWithType: ProviderSettings.ProviderSettings()
  fullName: System.Configuration.ProviderSettings.ProviderSettings()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProviderSettings ();
    parameters: []
  overload: System.Configuration.ProviderSettings.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: ProviderSettings(String,String)
  nameWithType: ProviderSettings.ProviderSettings(String,String)
  fullName: System.Configuration.ProviderSettings.ProviderSettings(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProviderSettings (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: type
      type: System.String
      description: To be added.
  overload: System.Configuration.ProviderSettings.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.IsModified
  id: IsModified
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: IsModified()
  nameWithType: ProviderSettings.IsModified()
  fullName: System.Configuration.ProviderSettings.IsModified()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override bool IsModified ();
    parameters: []
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ProviderSettings.IsModified*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Name
  id: Name
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Name
  nameWithType: ProviderSettings.Name
  fullName: System.Configuration.ProviderSettings.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ProviderSettings.Name*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ProviderSettings.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: value
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Parameters
  id: Parameters
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Parameters
  nameWithType: ProviderSettings.Parameters
  fullName: System.Configuration.ProviderSettings.Parameters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Parameters { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: To be added.
  overload: System.Configuration.ProviderSettings.Parameters*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Properties
  id: Properties
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProviderSettings.Properties
  fullName: System.Configuration.ProviderSettings.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.ProviderSettings.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ProviderSettings.Reset(ConfigurationElement)
  fullName: System.Configuration.ProviderSettings.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: To be added.
  overload: System.Configuration.ProviderSettings.Reset*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Type
  id: Type
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Type
  nameWithType: ProviderSettings.Type
  fullName: System.Configuration.ProviderSettings.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ProviderSettings.Type*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProviderSettings.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  id: Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  parent: System.Configuration.ProviderSettings
  langs:
  - csharp
  name: Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
  nameWithType: ProviderSettings.Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
  fullName: System.Configuration.ProviderSettings.Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override void Unmerge (System.Configuration.ConfigurationElement sourceElement, System.Configuration.ConfigurationElement parentElement, System.Configuration.ConfigurationSaveMode saveMode);
    parameters:
    - id: sourceElement
      type: System.Configuration.ConfigurationElement
      description: To be added.
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: To be added.
    - id: saveMode
      type: System.Configuration.ConfigurationSaveMode
      description: To be added.
  overload: System.Configuration.ProviderSettings.Unmerge*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.ProviderSettings.#ctor
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: ProviderSettings()
  nameWithType: ProviderSettings.ProviderSettings()
  fullName: System.Configuration.ProviderSettings.ProviderSettings()
- uid: System.Configuration.ProviderSettings.#ctor(System.String,System.String)
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: ProviderSettings(String,String)
  nameWithType: ProviderSettings.ProviderSettings(String,String)
  fullName: System.Configuration.ProviderSettings.ProviderSettings(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProviderSettings.IsModified
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: IsModified()
  nameWithType: ProviderSettings.IsModified()
  fullName: System.Configuration.ProviderSettings.IsModified()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ProviderSettings.Name
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Name
  nameWithType: ProviderSettings.Name
  fullName: System.Configuration.ProviderSettings.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ProviderSettings.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProviderSettings.Parameters
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Parameters
  nameWithType: ProviderSettings.Parameters
  fullName: System.Configuration.ProviderSettings.Parameters
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ProviderSettings.Properties
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProviderSettings.Properties
  fullName: System.Configuration.ProviderSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ProviderSettings.Reset(System.Configuration.ConfigurationElement)
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ProviderSettings.Reset(ConfigurationElement)
  fullName: System.Configuration.ProviderSettings.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.ProviderSettings.Type
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Type
  nameWithType: ProviderSettings.Type
  fullName: System.Configuration.ProviderSettings.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProviderSettings.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
  nameWithType: ProviderSettings.Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
  fullName: System.Configuration.ProviderSettings.Unmerge(ConfigurationElement,ConfigurationElement,ConfigurationSaveMode)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ProviderSettings.#ctor*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: ProviderSettings
  nameWithType: ProviderSettings.ProviderSettings
- uid: System.Configuration.ProviderSettings.IsModified*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: IsModified
  nameWithType: ProviderSettings.IsModified
- uid: System.Configuration.ProviderSettings.Name*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Name
  nameWithType: ProviderSettings.Name
- uid: System.Configuration.ProviderSettings.OnDeserializeUnrecognizedAttribute*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: ProviderSettings.OnDeserializeUnrecognizedAttribute
- uid: System.Configuration.ProviderSettings.Parameters*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Parameters
  nameWithType: ProviderSettings.Parameters
- uid: System.Configuration.ProviderSettings.Properties*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProviderSettings.Properties
- uid: System.Configuration.ProviderSettings.Reset*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Reset
  nameWithType: ProviderSettings.Reset
- uid: System.Configuration.ProviderSettings.Type*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Type
  nameWithType: ProviderSettings.Type
- uid: System.Configuration.ProviderSettings.Unmerge*
  parent: System.Configuration.ProviderSettings
  isExternal: false
  name: Unmerge
  nameWithType: ProviderSettings.Unmerge
