### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSaveMode
  id: ConfigurationSaveMode
  children:
  - System.Configuration.ConfigurationSaveMode.Full
  - System.Configuration.ConfigurationSaveMode.Minimal
  - System.Configuration.ConfigurationSaveMode.Modified
  langs:
  - csharp
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum ConfigurationSaveMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSaveMode.Full
  id: Full
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Full
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  id: Minimal
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Minimal
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSaveMode.Modified
  id: Modified
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Modified
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationSaveMode.Full
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Modified
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
