### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationUserLevel
  id: ConfigurationUserLevel
  children:
  - System.Configuration.ConfigurationUserLevel.None
  - System.Configuration.ConfigurationUserLevel.PerUserRoaming
  - System.Configuration.ConfigurationUserLevel.PerUserRoamingAndLocal
  langs:
  - csharp
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum ConfigurationUserLevel
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationUserLevel.None
  id: None
  parent: System.Configuration.ConfigurationUserLevel
  langs:
  - csharp
  name: None
  nameWithType: ConfigurationUserLevel.None
  fullName: System.Configuration.ConfigurationUserLevel.None
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: None
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationUserLevel.PerUserRoaming
  id: PerUserRoaming
  parent: System.Configuration.ConfigurationUserLevel
  langs:
  - csharp
  name: PerUserRoaming
  nameWithType: ConfigurationUserLevel.PerUserRoaming
  fullName: System.Configuration.ConfigurationUserLevel.PerUserRoaming
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: PerUserRoaming
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationUserLevel.PerUserRoamingAndLocal
  id: PerUserRoamingAndLocal
  parent: System.Configuration.ConfigurationUserLevel
  langs:
  - csharp
  name: PerUserRoamingAndLocal
  nameWithType: ConfigurationUserLevel.PerUserRoamingAndLocal
  fullName: System.Configuration.ConfigurationUserLevel.PerUserRoamingAndLocal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: PerUserRoamingAndLocal
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationUserLevel.None
  parent: System.Configuration.ConfigurationUserLevel
  isExternal: false
  name: None
  nameWithType: ConfigurationUserLevel.None
  fullName: System.Configuration.ConfigurationUserLevel.None
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
- uid: System.Configuration.ConfigurationUserLevel.PerUserRoaming
  parent: System.Configuration.ConfigurationUserLevel
  isExternal: false
  name: PerUserRoaming
  nameWithType: ConfigurationUserLevel.PerUserRoaming
  fullName: System.Configuration.ConfigurationUserLevel.PerUserRoaming
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
- uid: System.Configuration.ConfigurationUserLevel.PerUserRoamingAndLocal
  parent: System.Configuration.ConfigurationUserLevel
  isExternal: false
  name: PerUserRoamingAndLocal
  nameWithType: ConfigurationUserLevel.PerUserRoamingAndLocal
  fullName: System.Configuration.ConfigurationUserLevel.PerUserRoamingAndLocal
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
