### YamlMime:ManagedReference
items:
- uid: System.Configuration.DpapiProtectedConfigurationProvider
  id: DpapiProtectedConfigurationProvider
  children:
  - System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  - System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider
  fullName: System.Configuration.DpapiProtectedConfigurationProvider
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class DpapiProtectedConfigurationProvider : System.Configuration.ProtectedConfigurationProvider'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  - System.Configuration.ProtectedConfigurationProvider
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DpapiProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: To be added.
    return:
      type: System.Xml.XmlNode
      description: To be added.
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: To be added.
    return:
      type: System.Xml.XmlNode
      description: To be added.
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void Initialize (string name, System.Collections.Specialized.NameValueCollection configurationValues);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    - id: configurationValues
      type: System.Collections.Specialized.NameValueCollection
      description: To be added.
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  id: UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool UseMachineProtection { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: System.Configuration.ProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize
  nameWithType: DpapiProtectedConfigurationProvider.Initialize
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
