### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowDefinition
  id: ConfigurationAllowDefinition
  children:
  - System.Configuration.ConfigurationAllowDefinition.Everywhere
  - System.Configuration.ConfigurationAllowDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  langs:
  - csharp
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum ConfigurationAllowDefinition
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  id: Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Everywhere
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  id: MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: MachineToWebRoot
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
