### YamlMime:ManagedReference
items:
- uid: System.Configuration.ValidatorCallback
  id: ValidatorCallback
  langs:
  - csharp
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
  type: Delegate
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public delegate void ValidatorCallback(object value);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
