### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeConfigurationFileMap
  id: ExeConfigurationFileMap
  children:
  - System.Configuration.ExeConfigurationFileMap.#ctor
  - System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ExeConfigurationFileMap.Clone
  - System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  - System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  - System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  langs:
  - csharp
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap
  fullName: System.Configuration.ExeConfigurationFileMap
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ExeConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ExeConfigurationFileMap ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ExeConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  id: ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ExeConfigFilename { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  id: LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string LocalUserConfigFilename { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  id: RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string RoamingUserConfigFilename { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap()
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap()
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap()
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigurationFileMap(String)
  nameWithType: ExeConfigurationFileMap.ExeConfigurationFileMap(String)
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: ExeConfigurationFileMap.Clone()
  fullName: System.Configuration.ExeConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
