### YamlMime:ManagedReference
items:
- uid: System.Configuration.ElementInformation
  id: ElementInformation
  children:
  - System.Configuration.ElementInformation.Errors
  - System.Configuration.ElementInformation.IsCollection
  - System.Configuration.ElementInformation.IsLocked
  - System.Configuration.ElementInformation.IsPresent
  - System.Configuration.ElementInformation.LineNumber
  - System.Configuration.ElementInformation.Properties
  - System.Configuration.ElementInformation.Source
  - System.Configuration.ElementInformation.Type
  - System.Configuration.ElementInformation.Validator
  langs:
  - csharp
  name: ElementInformation
  nameWithType: ElementInformation
  fullName: System.Configuration.ElementInformation
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public sealed class ElementInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Errors
  id: Errors
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.ICollection Errors { get; }
    return:
      type: System.Collections.ICollection
      description: To be added.
  overload: System.Configuration.ElementInformation.Errors*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsCollection
  id: IsCollection
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsCollection { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ElementInformation.IsCollection*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsLocked
  id: IsLocked
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsLocked { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ElementInformation.IsLocked*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsPresent
  id: IsPresent
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsPresent { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ElementInformation.IsPresent*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.LineNumber
  id: LineNumber
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: To be added.
  overload: System.Configuration.ElementInformation.LineNumber*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Properties
  id: Properties
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.PropertyInformationCollection Properties { get; }
    return:
      type: System.Configuration.PropertyInformationCollection
      description: To be added.
  overload: System.Configuration.ElementInformation.Properties*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Source
  id: Source
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Source { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ElementInformation.Source*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Type
  id: Type
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: To be added.
  overload: System.Configuration.ElementInformation.Type*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Validator
  id: Validator
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  overload: System.Configuration.ElementInformation.Validator*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ElementInformation.Errors
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: true
  name: ICollection
  nameWithType: ICollection
  fullName: System.Collections.ICollection
- uid: System.Configuration.ElementInformation.IsCollection
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.IsLocked
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.IsPresent
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.LineNumber
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ElementInformation.Properties
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
- uid: System.Configuration.PropertyInformationCollection
  parent: System.Configuration
  isExternal: false
  name: PropertyInformationCollection
  nameWithType: PropertyInformationCollection
  fullName: System.Configuration.PropertyInformationCollection
- uid: System.Configuration.ElementInformation.Source
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ElementInformation.Type
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ElementInformation.Validator
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ElementInformation.Errors*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Errors
  nameWithType: ElementInformation.Errors
- uid: System.Configuration.ElementInformation.IsCollection*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
- uid: System.Configuration.ElementInformation.IsLocked*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
- uid: System.Configuration.ElementInformation.IsPresent*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
- uid: System.Configuration.ElementInformation.LineNumber*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
- uid: System.Configuration.ElementInformation.Properties*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Properties
  nameWithType: ElementInformation.Properties
- uid: System.Configuration.ElementInformation.Source*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Source
  nameWithType: ElementInformation.Source
- uid: System.Configuration.ElementInformation.Type*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Type
  nameWithType: ElementInformation.Type
- uid: System.Configuration.ElementInformation.Validator*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Validator
  nameWithType: ElementInformation.Validator
