### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyInformation
  id: PropertyInformation
  children:
  - System.Configuration.PropertyInformation.Converter
  - System.Configuration.PropertyInformation.DefaultValue
  - System.Configuration.PropertyInformation.Description
  - System.Configuration.PropertyInformation.IsKey
  - System.Configuration.PropertyInformation.IsLocked
  - System.Configuration.PropertyInformation.IsModified
  - System.Configuration.PropertyInformation.IsRequired
  - System.Configuration.PropertyInformation.LineNumber
  - System.Configuration.PropertyInformation.Name
  - System.Configuration.PropertyInformation.Source
  - System.Configuration.PropertyInformation.Type
  - System.Configuration.PropertyInformation.Validator
  - System.Configuration.PropertyInformation.Value
  - System.Configuration.PropertyInformation.ValueOrigin
  langs:
  - csharp
  name: PropertyInformation
  nameWithType: PropertyInformation
  fullName: System.Configuration.PropertyInformation
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public sealed class PropertyInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Converter
  id: Converter
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Converter
  nameWithType: PropertyInformation.Converter
  fullName: System.Configuration.PropertyInformation.Converter
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.ComponentModel.TypeConverter Converter { get; }
    return:
      type: System.ComponentModel.TypeConverter
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.DefaultValue
  id: DefaultValue
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: DefaultValue
  nameWithType: PropertyInformation.DefaultValue
  fullName: System.Configuration.PropertyInformation.DefaultValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object DefaultValue { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Description
  id: Description
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Description
  nameWithType: PropertyInformation.Description
  fullName: System.Configuration.PropertyInformation.Description
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.IsKey
  id: IsKey
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: IsKey
  nameWithType: PropertyInformation.IsKey
  fullName: System.Configuration.PropertyInformation.IsKey
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsKey { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.IsLocked
  id: IsLocked
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: IsLocked
  nameWithType: PropertyInformation.IsLocked
  fullName: System.Configuration.PropertyInformation.IsLocked
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsLocked { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.IsModified
  id: IsModified
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: IsModified
  nameWithType: PropertyInformation.IsModified
  fullName: System.Configuration.PropertyInformation.IsModified
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsModified { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.IsRequired
  id: IsRequired
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: IsRequired
  nameWithType: PropertyInformation.IsRequired
  fullName: System.Configuration.PropertyInformation.IsRequired
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsRequired { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.LineNumber
  id: LineNumber
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: LineNumber
  nameWithType: PropertyInformation.LineNumber
  fullName: System.Configuration.PropertyInformation.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Name
  id: Name
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Name
  nameWithType: PropertyInformation.Name
  fullName: System.Configuration.PropertyInformation.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Source
  id: Source
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Source
  nameWithType: PropertyInformation.Source
  fullName: System.Configuration.PropertyInformation.Source
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Source { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Type
  id: Type
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Type
  nameWithType: PropertyInformation.Type
  fullName: System.Configuration.PropertyInformation.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Validator
  id: Validator
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Validator
  nameWithType: PropertyInformation.Validator
  fullName: System.Configuration.PropertyInformation.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.Value
  id: Value
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: Value
  nameWithType: PropertyInformation.Value
  fullName: System.Configuration.PropertyInformation.Value
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object Value { get; set; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformation.ValueOrigin
  id: ValueOrigin
  parent: System.Configuration.PropertyInformation
  langs:
  - csharp
  name: ValueOrigin
  nameWithType: PropertyInformation.ValueOrigin
  fullName: System.Configuration.PropertyInformation.ValueOrigin
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.PropertyValueOrigin ValueOrigin { get; }
    return:
      type: System.Configuration.PropertyValueOrigin
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.PropertyInformation.Converter
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Converter
  nameWithType: PropertyInformation.Converter
  fullName: System.Configuration.PropertyInformation.Converter
- uid: System.ComponentModel.TypeConverter
  parent: System.ComponentModel
  isExternal: false
  name: TypeConverter
  nameWithType: TypeConverter
  fullName: System.ComponentModel.TypeConverter
- uid: System.Configuration.PropertyInformation.DefaultValue
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: DefaultValue
  nameWithType: PropertyInformation.DefaultValue
  fullName: System.Configuration.PropertyInformation.DefaultValue
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.PropertyInformation.Description
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Description
  nameWithType: PropertyInformation.Description
  fullName: System.Configuration.PropertyInformation.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.PropertyInformation.IsKey
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: IsKey
  nameWithType: PropertyInformation.IsKey
  fullName: System.Configuration.PropertyInformation.IsKey
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.PropertyInformation.IsLocked
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: IsLocked
  nameWithType: PropertyInformation.IsLocked
  fullName: System.Configuration.PropertyInformation.IsLocked
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.PropertyInformation.IsModified
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: IsModified
  nameWithType: PropertyInformation.IsModified
  fullName: System.Configuration.PropertyInformation.IsModified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.PropertyInformation.IsRequired
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: IsRequired
  nameWithType: PropertyInformation.IsRequired
  fullName: System.Configuration.PropertyInformation.IsRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.PropertyInformation.LineNumber
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: LineNumber
  nameWithType: PropertyInformation.LineNumber
  fullName: System.Configuration.PropertyInformation.LineNumber
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.PropertyInformation.Name
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Name
  nameWithType: PropertyInformation.Name
  fullName: System.Configuration.PropertyInformation.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.PropertyInformation.Source
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Source
  nameWithType: PropertyInformation.Source
  fullName: System.Configuration.PropertyInformation.Source
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.PropertyInformation.Type
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Type
  nameWithType: PropertyInformation.Type
  fullName: System.Configuration.PropertyInformation.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.PropertyInformation.Validator
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Validator
  nameWithType: PropertyInformation.Validator
  fullName: System.Configuration.PropertyInformation.Validator
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PropertyInformation.Value
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: Value
  nameWithType: PropertyInformation.Value
  fullName: System.Configuration.PropertyInformation.Value
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.PropertyInformation.ValueOrigin
  parent: System.Configuration.PropertyInformation
  isExternal: false
  name: ValueOrigin
  nameWithType: PropertyInformation.ValueOrigin
  fullName: System.Configuration.PropertyInformation.ValueOrigin
- uid: System.Configuration.PropertyValueOrigin
  parent: System.Configuration
  isExternal: false
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
