### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSectionGroup
  id: ConfigurationSectionGroup
  children:
  - System.Configuration.ConfigurationSectionGroup.#ctor
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  langs:
  - csharp
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public class ConfigurationSectionGroup
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: ConfigurationSectionGroup()
  nameWithType: ConfigurationSectionGroup.ConfigurationSectionGroup()
  fullName: System.Configuration.ConfigurationSectionGroup.ConfigurationSectionGroup()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConfigurationSectionGroup ();
    parameters: []
  overload: System.Configuration.ConfigurationSectionGroup.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  id: ForceDeclaration
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: ForceDeclaration()
  nameWithType: ConfigurationSectionGroup.ForceDeclaration()
  fullName: System.Configuration.ConfigurationSectionGroup.ForceDeclaration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ForceDeclaration ();
    parameters: []
  overload: System.Configuration.ConfigurationSectionGroup.ForceDeclaration*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  id: ForceDeclaration(System.Boolean)
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: ForceDeclaration(Boolean)
  nameWithType: ConfigurationSectionGroup.ForceDeclaration(Boolean)
  fullName: System.Configuration.ConfigurationSectionGroup.ForceDeclaration(Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void ForceDeclaration (bool force);
    parameters:
    - id: force
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.ForceDeclaration*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  id: IsDeclarationRequired
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: IsDeclarationRequired
  nameWithType: ConfigurationSectionGroup.IsDeclarationRequired
  fullName: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsDeclarationRequired { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclared
  id: IsDeclared
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: IsDeclared
  nameWithType: ConfigurationSectionGroup.IsDeclared
  fullName: System.Configuration.ConfigurationSectionGroup.IsDeclared
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsDeclared { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.IsDeclared*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.Name
  id: Name
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: Name
  nameWithType: ConfigurationSectionGroup.Name
  fullName: System.Configuration.ConfigurationSectionGroup.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.Name*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroupName
  id: SectionGroupName
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: SectionGroupName
  nameWithType: ConfigurationSectionGroup.SectionGroupName
  fullName: System.Configuration.ConfigurationSectionGroup.SectionGroupName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string SectionGroupName { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.SectionGroupName*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroups
  id: SectionGroups
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: SectionGroups
  nameWithType: ConfigurationSectionGroup.SectionGroups
  fullName: System.Configuration.ConfigurationSectionGroup.SectionGroups
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationSectionGroupCollection SectionGroups { get; }
    return:
      type: System.Configuration.ConfigurationSectionGroupCollection
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.SectionGroups*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.Sections
  id: Sections
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: Sections
  nameWithType: ConfigurationSectionGroup.Sections
  fullName: System.Configuration.ConfigurationSectionGroup.Sections
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationSectionCollection Sections { get; }
    return:
      type: System.Configuration.ConfigurationSectionCollection
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.Sections*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  id: ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
  nameWithType: ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
  fullName: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected virtual bool ShouldSerializeSectionGroupInTargetVersion (System.Runtime.Versioning.FrameworkName targetFramework);
    parameters:
    - id: targetFramework
      type: System.Runtime.Versioning.FrameworkName
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSectionGroup.Type
  id: Type
  parent: System.Configuration.ConfigurationSectionGroup
  langs:
  - csharp
  name: Type
  nameWithType: ConfigurationSectionGroup.Type
  fullName: System.Configuration.ConfigurationSectionGroup.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ConfigurationSectionGroup.Type*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationSectionGroup.#ctor
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ConfigurationSectionGroup()
  nameWithType: ConfigurationSectionGroup.ConfigurationSectionGroup()
  fullName: System.Configuration.ConfigurationSectionGroup.ConfigurationSectionGroup()
- uid: System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ForceDeclaration()
  nameWithType: ConfigurationSectionGroup.ForceDeclaration()
  fullName: System.Configuration.ConfigurationSectionGroup.ForceDeclaration()
- uid: System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ForceDeclaration(Boolean)
  nameWithType: ConfigurationSectionGroup.ForceDeclaration(Boolean)
  fullName: System.Configuration.ConfigurationSectionGroup.ForceDeclaration(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: IsDeclarationRequired
  nameWithType: ConfigurationSectionGroup.IsDeclarationRequired
  fullName: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclared
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: IsDeclared
  nameWithType: ConfigurationSectionGroup.IsDeclared
  fullName: System.Configuration.ConfigurationSectionGroup.IsDeclared
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationSectionGroup.Name
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Name
  nameWithType: ConfigurationSectionGroup.Name
  fullName: System.Configuration.ConfigurationSectionGroup.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroupName
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: SectionGroupName
  nameWithType: ConfigurationSectionGroup.SectionGroupName
  fullName: System.Configuration.ConfigurationSectionGroup.SectionGroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroups
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: SectionGroups
  nameWithType: ConfigurationSectionGroup.SectionGroups
  fullName: System.Configuration.ConfigurationSectionGroup.SectionGroups
- uid: System.Configuration.ConfigurationSectionGroupCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroupCollection
  nameWithType: ConfigurationSectionGroupCollection
  fullName: System.Configuration.ConfigurationSectionGroupCollection
- uid: System.Configuration.ConfigurationSectionGroup.Sections
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Sections
  nameWithType: ConfigurationSectionGroup.Sections
  fullName: System.Configuration.ConfigurationSectionGroup.Sections
- uid: System.Configuration.ConfigurationSectionCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionCollection
  nameWithType: ConfigurationSectionCollection
  fullName: System.Configuration.ConfigurationSectionCollection
- uid: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
  nameWithType: ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
  fullName: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(FrameworkName)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.Versioning.FrameworkName
  parent: System.Runtime.Versioning
  isExternal: true
  name: FrameworkName
  nameWithType: FrameworkName
  fullName: System.Runtime.Versioning.FrameworkName
- uid: System.Configuration.ConfigurationSectionGroup.Type
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Type
  nameWithType: ConfigurationSectionGroup.Type
  fullName: System.Configuration.ConfigurationSectionGroup.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSectionGroup.#ctor*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup.ConfigurationSectionGroup
- uid: System.Configuration.ConfigurationSectionGroup.ForceDeclaration*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ForceDeclaration
  nameWithType: ConfigurationSectionGroup.ForceDeclaration
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: IsDeclarationRequired
  nameWithType: ConfigurationSectionGroup.IsDeclarationRequired
- uid: System.Configuration.ConfigurationSectionGroup.IsDeclared*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: IsDeclared
  nameWithType: ConfigurationSectionGroup.IsDeclared
- uid: System.Configuration.ConfigurationSectionGroup.Name*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Name
  nameWithType: ConfigurationSectionGroup.Name
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroupName*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: SectionGroupName
  nameWithType: ConfigurationSectionGroup.SectionGroupName
- uid: System.Configuration.ConfigurationSectionGroup.SectionGroups*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: SectionGroups
  nameWithType: ConfigurationSectionGroup.SectionGroups
- uid: System.Configuration.ConfigurationSectionGroup.Sections*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Sections
  nameWithType: ConfigurationSectionGroup.Sections
- uid: System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: ShouldSerializeSectionGroupInTargetVersion
  nameWithType: ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion
- uid: System.Configuration.ConfigurationSectionGroup.Type*
  parent: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: Type
  nameWithType: ConfigurationSectionGroup.Type
