### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeContext
  id: ExeContext
  children:
  - System.Configuration.ExeContext.ExePath
  - System.Configuration.ExeContext.UserLevel
  langs:
  - csharp
  name: ExeContext
  nameWithType: ExeContext
  fullName: System.Configuration.ExeContext
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public sealed class ExeContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeContext.ExePath
  id: ExePath
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string ExePath { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ExeContext.UserLevel
  id: UserLevel
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationUserLevel UserLevel { get; }
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ExeContext.ExePath
  parent: System.Configuration.ExeContext
  isExternal: false
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeContext.UserLevel
  parent: System.Configuration.ExeContext
  isExternal: false
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
