### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocationCollection
  id: ConfigurationLocationCollection
  children:
  - System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  langs:
  - csharp
  name: ConfigurationLocationCollection
  nameWithType: ConfigurationLocationCollection
  fullName: System.Configuration.ConfigurationLocationCollection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ConfigurationLocationCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationLocation this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: To be added.
    return:
      type: System.Configuration.ConfigurationLocation
      description: To be added.
  overload: System.Configuration.ConfigurationLocationCollection.Item*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
- uid: System.Configuration.ConfigurationLocation
  parent: System.Configuration
  isExternal: false
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLocationCollection.Item*
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item
  nameWithType: ConfigurationLocationCollection.Item
