### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorBase
  id: ConfigurationValidatorBase
  children:
  - System.Configuration.ConfigurationValidatorBase.#ctor
  - System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  - System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  langs:
  - csharp
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public abstract class ConfigurationValidatorBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected ConfigurationValidatorBase ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public abstract void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
