### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementProperty
  id: ConfigurationElementProperty
  children:
  - System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  - System.Configuration.ConfigurationElementProperty.Validator
  langs:
  - csharp
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public sealed class ConfigurationElementProperty
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  id: '#ctor(System.Configuration.ConfigurationValidatorBase)'
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ConfigurationElementProperty (System.Configuration.ConfigurationValidatorBase validator);
    parameters:
    - id: validator
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationElementProperty.Validator
  id: Validator
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationElementProperty.Validator
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
