### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
