### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidator
  id: StringValidator
  children:
  - System.Configuration.StringValidator.#ctor(System.Int32)
  - System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  - System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  - System.Configuration.StringValidator.CanValidate(System.Type)
  - System.Configuration.StringValidator.Validate(System.Object)
  langs:
  - csharp
  name: StringValidator
  nameWithType: StringValidator
  fullName: System.Configuration.StringValidator
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class StringValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.StringValidator.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32)
  nameWithType: StringValidator.StringValidator(Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public StringValidator (int minLength);
    parameters:
    - id: minLength
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  id: '#ctor(System.Int32,System.Int32)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32,Int32)
  nameWithType: StringValidator.StringValidator(Int32,Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public StringValidator (int minLength, int maxLength);
    parameters:
    - id: minLength
      type: System.Int32
      description: To be added.
    - id: maxLength
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  id: '#ctor(System.Int32,System.Int32,System.String)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32,Int32,String)
  nameWithType: StringValidator.StringValidator(Int32,Int32,String)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public StringValidator (int minLength, int maxLength, string invalidCharacters);
    parameters:
    - id: minLength
      type: System.Int32
      description: To be added.
    - id: maxLength
      type: System.Int32
      description: To be added.
    - id: invalidCharacters
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.StringValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: StringValidator.CanValidate(Type)
  fullName: System.Configuration.StringValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.StringValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: StringValidator.Validate(Object)
  fullName: System.Configuration.StringValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidator.#ctor(System.Int32)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32)
  nameWithType: StringValidator.StringValidator(Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32,Int32)
  nameWithType: StringValidator.StringValidator(Int32,Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32,Int32,String)
  nameWithType: StringValidator.StringValidator(Int32,Int32,String)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidator.CanValidate(System.Type)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: StringValidator.CanValidate(Type)
  fullName: System.Configuration.StringValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.StringValidator.Validate(System.Object)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: StringValidator.Validate(Object)
  fullName: System.Configuration.StringValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
