### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfiguration
  id: ProtectedConfiguration
  children:
  - System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  - System.Configuration.ProtectedConfiguration.DefaultProvider
  - System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  - System.Configuration.ProtectedConfiguration.Providers
  - System.Configuration.ProtectedConfiguration.RsaProviderName
  langs:
  - csharp
  name: ProtectedConfiguration
  nameWithType: ProtectedConfiguration
  fullName: System.Configuration.ProtectedConfiguration
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static class ProtectedConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  id: DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public const string DataProtectionProviderName;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static string DefaultProvider { get; }
    return:
      type: System.String
      description: To be added.
  overload: System.Configuration.ProtectedConfiguration.DefaultProvider*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  id: ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public const string ProtectedDataSectionName;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public static System.Configuration.ProtectedConfigurationProviderCollection Providers { get; }
    return:
      type: System.Configuration.ProtectedConfigurationProviderCollection
      description: To be added.
  overload: System.Configuration.ProtectedConfiguration.Providers*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  id: RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public const string RsaProviderName;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.Providers
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.Providers*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
