### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
