### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLockCollection
  id: ConfigurationLockCollection
  children:
  - System.Configuration.ConfigurationLockCollection.Add(System.String)
  - System.Configuration.ConfigurationLockCollection.AttributeList
  - System.Configuration.ConfigurationLockCollection.Clear
  - System.Configuration.ConfigurationLockCollection.Contains(System.String)
  - System.Configuration.ConfigurationLockCollection.CopyTo(System.String[],System.Int32)
  - System.Configuration.ConfigurationLockCollection.Count
  - System.Configuration.ConfigurationLockCollection.GetEnumerator
  - System.Configuration.ConfigurationLockCollection.HasParentElements
  - System.Configuration.ConfigurationLockCollection.IsModified
  - System.Configuration.ConfigurationLockCollection.IsReadOnly(System.String)
  - System.Configuration.ConfigurationLockCollection.IsSynchronized
  - System.Configuration.ConfigurationLockCollection.Remove(System.String)
  - System.Configuration.ConfigurationLockCollection.SetFromList(System.String)
  - System.Configuration.ConfigurationLockCollection.SyncRoot
  - System.Configuration.ConfigurationLockCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  langs:
  - csharp
  name: ConfigurationLockCollection
  nameWithType: ConfigurationLockCollection
  fullName: System.Configuration.ConfigurationLockCollection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public sealed class ConfigurationLockCollection : System.Collections.ICollection'
  inheritance:
  - System.Object
  implements:
  - System.Collections.ICollection
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.Add(System.String)
  id: Add(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: Add(String)
  nameWithType: ConfigurationLockCollection.Add(String)
  fullName: System.Configuration.ConfigurationLockCollection.Add(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Add (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.AttributeList
  id: AttributeList
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: AttributeList
  nameWithType: ConfigurationLockCollection.AttributeList
  fullName: System.Configuration.ConfigurationLockCollection.AttributeList
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public string AttributeList { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.Clear
  id: Clear
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: ConfigurationLockCollection.Clear()
  fullName: System.Configuration.ConfigurationLockCollection.Clear()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Clear ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.Contains(System.String)
  id: Contains(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: Contains(String)
  nameWithType: ConfigurationLockCollection.Contains(String)
  fullName: System.Configuration.ConfigurationLockCollection.Contains(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool Contains (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.CopyTo(System.String[],System.Int32)
  id: CopyTo(System.String[],System.Int32)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: CopyTo(String[],Int32)
  nameWithType: ConfigurationLockCollection.CopyTo(String[],Int32)
  fullName: System.Configuration.ConfigurationLockCollection.CopyTo(String[],Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void CopyTo (string[] array, int index);
    parameters:
    - id: array
      type: System.String[]
      description: To be added.
    - id: index
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.Count
  id: Count
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: Count
  nameWithType: ConfigurationLockCollection.Count
  fullName: System.Configuration.ConfigurationLockCollection.Count
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: ConfigurationLockCollection.GetEnumerator()
  fullName: System.Configuration.ConfigurationLockCollection.GetEnumerator()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.HasParentElements
  id: HasParentElements
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: HasParentElements
  nameWithType: ConfigurationLockCollection.HasParentElements
  fullName: System.Configuration.ConfigurationLockCollection.HasParentElements
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool HasParentElements { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.IsModified
  id: IsModified
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: IsModified
  nameWithType: ConfigurationLockCollection.IsModified
  fullName: System.Configuration.ConfigurationLockCollection.IsModified
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsModified { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.IsReadOnly(System.String)
  id: IsReadOnly(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: IsReadOnly(String)
  nameWithType: ConfigurationLockCollection.IsReadOnly(String)
  fullName: System.Configuration.ConfigurationLockCollection.IsReadOnly(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsReadOnly (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.IsSynchronized
  id: IsSynchronized
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: IsSynchronized
  nameWithType: ConfigurationLockCollection.IsSynchronized
  fullName: System.Configuration.ConfigurationLockCollection.IsSynchronized
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsSynchronized { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.Remove(System.String)
  id: Remove(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: Remove(String)
  nameWithType: ConfigurationLockCollection.Remove(String)
  fullName: System.Configuration.ConfigurationLockCollection.Remove(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Remove (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.SetFromList(System.String)
  id: SetFromList(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: SetFromList(String)
  nameWithType: ConfigurationLockCollection.SetFromList(String)
  fullName: System.Configuration.ConfigurationLockCollection.SetFromList(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetFromList (string attributeList);
    parameters:
    - id: attributeList
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.SyncRoot
  id: SyncRoot
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: SyncRoot
  nameWithType: ConfigurationLockCollection.SyncRoot
  fullName: System.Configuration.ConfigurationLockCollection.SyncRoot
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object SyncRoot { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLockCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  id: System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  isEii: true
  parent: System.Configuration.ConfigurationLockCollection
  langs:
  - csharp
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ConfigurationLockCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.ConfigurationLockCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: void ICollection.CopyTo (Array array, int index);
    parameters:
    - id: array
      type: System.Array
      description: To be added.
    - id: index
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLockCollection.Add(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: Add(String)
  nameWithType: ConfigurationLockCollection.Add(String)
  fullName: System.Configuration.ConfigurationLockCollection.Add(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.AttributeList
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: AttributeList
  nameWithType: ConfigurationLockCollection.AttributeList
  fullName: System.Configuration.ConfigurationLockCollection.AttributeList
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.Clear
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: Clear()
  nameWithType: ConfigurationLockCollection.Clear()
  fullName: System.Configuration.ConfigurationLockCollection.Clear()
- uid: System.Configuration.ConfigurationLockCollection.Contains(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: Contains(String)
  nameWithType: ConfigurationLockCollection.Contains(String)
  fullName: System.Configuration.ConfigurationLockCollection.Contains(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.CopyTo(System.String[],System.Int32)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: CopyTo(String[],Int32)
  nameWithType: ConfigurationLockCollection.CopyTo(String[],Int32)
  fullName: System.Configuration.ConfigurationLockCollection.CopyTo(String[],Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLockCollection.Count
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: Count
  nameWithType: ConfigurationLockCollection.Count
  fullName: System.Configuration.ConfigurationLockCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLockCollection.GetEnumerator
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: ConfigurationLockCollection.GetEnumerator()
  fullName: System.Configuration.ConfigurationLockCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.ConfigurationLockCollection.HasParentElements
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: HasParentElements
  nameWithType: ConfigurationLockCollection.HasParentElements
  fullName: System.Configuration.ConfigurationLockCollection.HasParentElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationLockCollection.IsModified
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: IsModified
  nameWithType: ConfigurationLockCollection.IsModified
  fullName: System.Configuration.ConfigurationLockCollection.IsModified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationLockCollection.IsReadOnly(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: IsReadOnly(String)
  nameWithType: ConfigurationLockCollection.IsReadOnly(String)
  fullName: System.Configuration.ConfigurationLockCollection.IsReadOnly(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.IsSynchronized
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: IsSynchronized
  nameWithType: ConfigurationLockCollection.IsSynchronized
  fullName: System.Configuration.ConfigurationLockCollection.IsSynchronized
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationLockCollection.Remove(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: Remove(String)
  nameWithType: ConfigurationLockCollection.Remove(String)
  fullName: System.Configuration.ConfigurationLockCollection.Remove(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.SetFromList(System.String)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: SetFromList(String)
  nameWithType: ConfigurationLockCollection.SetFromList(String)
  fullName: System.Configuration.ConfigurationLockCollection.SetFromList(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLockCollection.SyncRoot
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: SyncRoot
  nameWithType: ConfigurationLockCollection.SyncRoot
  fullName: System.Configuration.ConfigurationLockCollection.SyncRoot
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationLockCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  parent: System.Configuration.ConfigurationLockCollection
  isExternal: false
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ConfigurationLockCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.ConfigurationLockCollection.System.Collections.ICollection.CopyTo(Array,Int32)
- uid: System.Array
  parent: System
  isExternal: true
  name: Array
  nameWithType: Array
  fullName: System.Array
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
