### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderCollection
  id: ProviderCollection
  children:
  - System.Configuration.Provider.ProviderCollection.#ctor
  - System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Item(System.String)
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  langs:
  - csharp
  name: ProviderCollection
  nameWithType: ProviderCollection
  fullName: System.Configuration.Provider.ProviderCollection
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class ProviderCollection : System.Collections.ICollection'
  inheritance:
  - System.Object
  implements:
  - System.Collections.ICollection
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: ProviderCollection()
  nameWithType: ProviderCollection.ProviderCollection()
  fullName: System.Configuration.Provider.ProviderCollection.ProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public ProviderCollection ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.Provider.ProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Clear
  id: Clear
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: ProviderCollection.Clear()
  fullName: System.Configuration.Provider.ProviderCollection.Clear()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Clear ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  id: CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: CopyTo(ProviderBase[],Int32)
  nameWithType: ProviderCollection.CopyTo(ProviderBase[],Int32)
  fullName: System.Configuration.Provider.ProviderCollection.CopyTo(ProviderBase[],Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void CopyTo (System.Configuration.Provider.ProviderBase[] array, int index);
    parameters:
    - id: array
      type: System.Configuration.Provider.ProviderBase[]
      description: To be added.
    - id: index
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Count
  id: Count
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Count
  nameWithType: ProviderCollection.Count
  fullName: System.Configuration.Provider.ProviderCollection.Count
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: ProviderCollection.GetEnumerator()
  fullName: System.Configuration.Provider.ProviderCollection.GetEnumerator()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.IsSynchronized
  id: IsSynchronized
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: IsSynchronized
  nameWithType: ProviderCollection.IsSynchronized
  fullName: System.Configuration.Provider.ProviderCollection.IsSynchronized
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public bool IsSynchronized { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProviderCollection.Item(String)
  fullName: System.Configuration.Provider.ProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Provider.ProviderBase this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: To be added.
    return:
      type: System.Configuration.Provider.ProviderBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Remove(System.String)
  id: Remove(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Remove(String)
  nameWithType: ProviderCollection.Remove(String)
  fullName: System.Configuration.Provider.ProviderCollection.Remove(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void Remove (string name);
    parameters:
    - id: name
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.SetReadOnly
  id: SetReadOnly
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: SetReadOnly()
  nameWithType: ProviderCollection.SetReadOnly()
  fullName: System.Configuration.Provider.ProviderCollection.SetReadOnly()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public void SetReadOnly ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.SyncRoot
  id: SyncRoot
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: SyncRoot
  nameWithType: ProviderCollection.SyncRoot
  fullName: System.Configuration.Provider.ProviderCollection.SyncRoot
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public object SyncRoot { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  id: System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  isEii: true
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.Provider.ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: To be added.
  remarks: To be added.
  syntax:
    content: void ICollection.CopyTo (Array array, int index);
    parameters:
    - id: array
      type: System.Array
      description: To be added.
    - id: index
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Provider.ProviderCollection.#ctor
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: ProviderCollection()
  nameWithType: ProviderCollection.ProviderCollection()
  fullName: System.Configuration.Provider.ProviderCollection.ProviderCollection()
- uid: System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.Provider.ProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.Provider.ProviderCollection.Clear
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Clear()
  nameWithType: ProviderCollection.Clear()
  fullName: System.Configuration.Provider.ProviderCollection.Clear()
- uid: System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: CopyTo(ProviderBase[],Int32)
  nameWithType: ProviderCollection.CopyTo(ProviderBase[],Int32)
  fullName: System.Configuration.Provider.ProviderCollection.CopyTo(ProviderBase[],Int32)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase[]
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Provider.ProviderCollection.Count
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Count
  nameWithType: ProviderCollection.Count
  fullName: System.Configuration.Provider.ProviderCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Provider.ProviderCollection.GetEnumerator
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: ProviderCollection.GetEnumerator()
  fullName: System.Configuration.Provider.ProviderCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.Provider.ProviderCollection.IsSynchronized
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: IsSynchronized
  nameWithType: ProviderCollection.IsSynchronized
  fullName: System.Configuration.Provider.ProviderCollection.IsSynchronized
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Provider.ProviderCollection.Item(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProviderCollection.Item(String)
  fullName: System.Configuration.Provider.ProviderCollection.Item(String)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderCollection.Remove(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Remove(String)
  nameWithType: ProviderCollection.Remove(String)
  fullName: System.Configuration.Provider.ProviderCollection.Remove(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderCollection.SetReadOnly
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: SetReadOnly()
  nameWithType: ProviderCollection.SetReadOnly()
  fullName: System.Configuration.Provider.ProviderCollection.SetReadOnly()
- uid: System.Configuration.Provider.ProviderCollection.SyncRoot
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: SyncRoot
  nameWithType: ProviderCollection.SyncRoot
  fullName: System.Configuration.Provider.ProviderCollection.SyncRoot
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.Provider.ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
- uid: System.Array
  parent: System
  isExternal: true
  name: Array
  nameWithType: Array
  fullName: System.Array
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
