### YamlMime:ManagedReference
items:
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler
  id: DbProviderFactoriesConfigurationHandler
  children:
  - System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  - System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DbProviderFactoriesConfigurationHandler
  nameWithType: DbProviderFactoriesConfigurationHandler
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DbProviderFactoriesConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  langs:
  - csharp
  name: DbProviderFactoriesConfigurationHandler()
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  type: Constructor
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DbProviderFactoriesConfigurationHandler ();
    parameters: []
  overload: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: To be added.
    - id: configContext
      type: System.Object
      description: To be added.
    - id: section
      type: System.Xml.XmlNode
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: DbProviderFactoriesConfigurationHandler()
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler()
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.#ctor*
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: DbProviderFactoriesConfigurationHandler
  nameWithType: DbProviderFactoriesConfigurationHandler.DbProviderFactoriesConfigurationHandler
- uid: System.Data.Common.DbProviderFactoriesConfigurationHandler.Create*
  parent: System.Data.Common.DbProviderFactoriesConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DbProviderFactoriesConfigurationHandler.Create
