### YamlMime:ManagedReference
items:
- uid: System.Data.Common.DbProviderConfigurationHandler
  id: DbProviderConfigurationHandler
  children:
  - System.Data.Common.DbProviderConfigurationHandler.#ctor
  - System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DbProviderConfigurationHandler
  nameWithType: DbProviderConfigurationHandler
  fullName: System.Data.Common.DbProviderConfigurationHandler
  type: Class
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public class DbProviderConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  name: DbProviderConfigurationHandler()
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  fullName: System.Data.Common.DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  type: Constructor
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public DbProviderConfigurationHandler ();
    parameters: []
  overload: System.Data.Common.DbProviderConfigurationHandler.#ctor*
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Data
  namespace: System.Data.Common
  summary: To be added.
  remarks: To be added.
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: To be added.
    - id: configContext
      type: System.Object
      description: To be added.
    - id: section
      type: System.Xml.XmlNode
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.Data.Common.DbProviderConfigurationHandler.Create*
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: DbProviderConfigurationHandler()
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler()
  fullName: System.Data.Common.DbProviderConfigurationHandler.DbProviderConfigurationHandler()
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor*
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: DbProviderConfigurationHandler
  nameWithType: DbProviderConfigurationHandler.DbProviderConfigurationHandler
- uid: System.Data.Common.DbProviderConfigurationHandler.Create*
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DbProviderConfigurationHandler.Create
